Web Scraping Assignment (Exception Handeling)

Q1.Write a python program which searches all the product under a particular product vertical
from www.amazon.in. The product verticals to be searched will be taken as input from user.
For e.g. If user input is ‘guitar’. Then search for guitars.

In [27]:
import selenium
import pandas as pd
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException

In [404]:
driver=webdriver.Chrome("chromedriver.exe")

In [405]:
url='https://www.amazon.in'
driver.get(url)

In [406]:
user_input=input("Enter the text to be searched")
user_input

Enter the text to be searchedLaptop

'Laptop'

In [407]:
search_job=driver.find_element_by_xpath("//input[@id='twotabsearchtextbox']")
search_job.send_keys(user_input)

In [408]:
click_search=driver.find_element_by_xpath("//input[@id='nav-search-submit-button']")
click_search.click()

Q2. From the above results. Details to be scraped are: "Brand Name", "Name of the Product", "Rating", "No. of 
Ratings", "Price", "Return/Exchange", "Expected Delivery", "Availability", "Other Details" 
and “Product URL”. In case, if any of the details are missing for any of the product then 
replace it by “-“

In [409]:
produrl =[]
produrl_ = driver.find_elements_by_xpath("//a[@class='a-link-normal a-text-normal']")

In [413]:
for i in produrl_:
    try: 
        produrl.append(i.get_attribute("href"))
    except NoSuchElementException:
        produrl.append('-')

In [415]:
Brand = []
prod = []
rate = []
ratenum = []
price = []
ex = []
delv = []
avl = []
det = []

In [416]:
for i in produrl:
    driver.get(i)
    time.sleep(5)
    try:
        brandtag = driver.find_element_by_xpath("//td[@class='a-size-base prodDetAttrValue']")
        Brand.append(brandtag.text)
    except:
        Brand.append('-')
    try:
        prodtag = driver.find_element_by_xpath("//span[@class='a-size-large product-title-word-break']")
        prod.append(prodtag.text)
    except:
        prod.append('-')
    try:
        ratetag = driver.find_element_by_xpath("//div[@id='averageCustomerReviews']//span[@class='a-icon-alt']")
        rate.append(ratetag.get_attribute("innerHTML"))
    except NoSuchElementException:
        rate.append('-')
    try:
        ratenumtag = driver.find_element_by_xpath("//span[@id='acrCustomerReviewText']")
        ratenum.append(ratenumtag.get_attribute("innerHTML"))
    except:
        ratenum.append('-')
    try:
        pricetag = driver.find_element_by_xpath("//span[@id='priceblock_ourprice']")
        price.append(pricetag.text)
    except:
        price.append('-')
    
    try:
        extag = driver.find_element_by_xpath("//div[@class='a-accordion-row-a11y']//h5")
        ex.append(extag.text.replace('\n',' ').replace('   ',''))
    except:
        ex.append('-')
    
    try:
        delvtag = driver.find_element_by_xpath("//div[@id='ddmDeliveryMessage']//b")
        delv.append(delvtag.text)
    except:
        delv.append('-')
    try:
        avltag = driver.find_element_by_xpath("//div[@id='availability']//span")
        avl.append(avltag.text)
    except:
        avl.append('-')
    try:
        dettag = driver.find_element_by_xpath("//div[@id='feature-bullets']")
        det.append(dettag.text.replace('\nShow More','.').replace('\n',''))
    except:
        det.append('-')

In [418]:
Laptops = pd.DataFrame({})
Laptops['Brand Name'] = Brand[:10]
Laptops['Product Name']=prod[:10]
Laptops['Price']=price[:10]
Laptops['Rating']=rate[:10]
Laptops['Number of Ratings']=ratenum[:10] 
Laptops['Exchange']=ex[:10]
Laptops['Expected Delivery']=delv[:10]
Laptops['Availablitiy']=avl[:10]
Laptops['Details']=det[:10]


Laptops

,Brand Name,Product Name,Price,Rating,Number of Ratings,Exchange,Expected Delivery,Availablitiy,Details
0,ASUS,"ASUS VivoBook Flip 14 (2020), Intel Core i3-10...","₹46,990.00",4.3 out of 5 stars,60 ratings,"With Exchange Up to 18,400.00 off","Saturday, Oct 2",In stock.,About this itemFree upgrade to Windows 11 when...
1,ASUS,"ASUS VivoBook Ultra 15 (2020), AMD Ryzen 5 450...","₹54,990.00",4.5 out of 5 stars,11 ratings,"With Exchange Up to 18,400.00 off","Saturday, Oct 2",In stock.,About this itemFree upgrade to Windows 11 when...
2,Acer,Acer Aspire 3 AMD Athlon Silver 3050U Dual-cor...,"₹32,500.00",3.5 out of 5 stars,7 ratings,"With Exchange Up to 18,400.00 off","Saturday, Oct 2",In stock.,About this itemLaptopsProcessor : AMD Athlon S...
3,HP,HP Chromebook 14-inch (35.56 cms) Thin & Light...,"₹27,990.00",3.8 out of 5 stars,791 ratings,"With Exchange Up to 18,400.00 off","Saturday, Oct 2",In stock.,About this itemGOOGLE ASSISTANT: Voice-Enabled...
4,ASUS,ASUS VivoBook 14 2020 AMD Ryzen 3 3250U 14 inc...,"₹31,990.00",3.8 out of 5 stars,163 ratings,"With Exchange Up to 18,400.00 off","Saturday, Oct 2",In stock.,About this itemFree upgrade to Windows 11 when...
5,ASUS,"ASUS ROG Zephyrus G14 (2021), 14-inch (35.56 c...","₹96,990.00",2.5 out of 5 stars,2 ratings,"With Exchange Up to 18,400.00 off","Saturday, Oct 2",In stock.,About this itemFree upgrade to Windows 11 when...
6,Dell,"Dell Inspiron 3502 15.6"" (39.62 cms) HD Displa...","₹40,126.00",4.2 out of 5 stars,230 ratings,"With Exchange Up to 18,400.00 off","Saturday, Oct 2",In stock.,About this itemFree upgrade to Windows 11 when...
7,RDP,RDP ThinBook 1010 - Intel Celeron Quad Core Pr...,"₹19,990.00",3.3 out of 5 stars,280 ratings,"With Exchange Up to 14,550.00 off","Saturday, Oct 2",In stock.,About this itemIntel Celeron Quad Core Process...
8,Lenovo,Lenovo IdeaPad Slim 3 Intel Celeron N4020 15.6...,"₹36,699.00",4.1 out of 5 stars,422 ratings,"With Exchange Up to 18,400.00 off","Monday, Oct 4",In stock.,About this itemProcessor: Intel Celeron N4020 ...
9,HP,HP 15 Intel Pentium Gold 6405U Processor Entry...,-,3.4 out of 5 stars,856 ratings,-,-,,About this itemDesign & Battery: Thin and ligh...

In [420]:
Laptops.to_csv('Amazonscrape.csv')

In [419]:
driver.close()

Q3. Write a python program to access the search bar and search button on images.google.com and 
scrape 100 images each for keywords ‘fruits’, ‘cars’ and ‘Machine Learning’

In [425]:
driver=webdriver.Chrome("chromedriver.exe")

In [424]:
url='https://images.google.com/'
urls = []  
img = []

In [438]:
search_item = ["Fruits"]
for item in search_item:
    driver.get(url) 
    time.sleep(3)
    search_bar = driver.find_element_by_tag_name("input")        
    search_bar.send_keys(str(item))          
    search_button =driver.find_element_by_xpath("//button[@class='Tg7LZd']").click() 

for _ in range(500):
    driver.execute_script("window.scrollBy(0,100)")        
    imgs = driver.find_elements_by_xpath("//img[@class='rg_i Q4LuWd']")
img_url = []
for image in imgs:
    source = image.get_attribute('src')
    if source is not None:
        if(source[0:4] == 'http'):
            img_url.append(source)
for i in img_url[:100]: 
    img_url.append(source)
    urls.append(i) 
for i in range(len(urls)):
    if i >= 300:
        break
        print("Obtaining {0} of {1} images".format(i, 300))
        response=requests.get(urls[i])
        file = open(r"C:\Fliprobo"+str(i)+".jpg", "wb")
        file.write(response.content)

Q4. Write a python program to search for a smartphone(e.g.: Oneplus Nord, pixel 4A, etc.) on 
www.flipkart.com and scrape following details for all the search results displayed on 1st page. 
Details to be scraped: “Brand Name”, “Smartphone name”, “Colour”, “RAM”, 
“Storage(ROM)”, “Primary Camera”, “Secondary Camera”, “Display Size”, “Display 
Resolution”, “Processor”, “Processor Cores”, “Battery Capacity”, “Price”, “Product URL”. 
Incase if any of the details is missing then replace it by “- “. Save your results in a dataframe 
and CSV.

In [439]:
driver=webdriver.Chrome("chromedriver.exe")

In [440]:
url = "https://www.flipkart.com/"
driver.get(url)

In [441]:
click_btn = driver.find_element_by_xpath("//div[@class='_2QfC02']//button")
click_btn.click()

In [442]:
search_bar = driver.find_element_by_xpath("//div[@class='_3OO5Xc']//input")
search_bar.send_keys("Smartphones")

In [443]:
search_btn = driver.find_element_by_xpath("/html/body/div[1]/div/div[1]/div[1]/div[2]/div[2]/form/div/button")
search_btn.click()

In [444]:
urls = []
for i in driver.find_elements_by_xpath("//a[@class='_1fQZEK']"):
    urls.append(i.get_attribute("href"))

In [463]:
#BAsed on the question creating empty lists
brand_names = []
name = []
color = []
RAM = []
storage = []
p_cam = []
s_cam = []
Display_size = []
display_resolution = []
processor = []
processor_core = []
battery_cap = []
prices = []
product_url = []

In [464]:
# fetching battery capacity
for i in driver.find_elements_by_xpath("//div[@class='fMghEO']"):
    try:
        bat_cap = driver.find_element_by_xpath("//ul[@class='_1xgFaf']//li[4]")
        battery_cap.append(bat_cap.text)
    except NoSuchElementException:
        battery_cap.append('-')
for i in urls:
    driver.get(i)
    time.sleep(3)
    
    # fetching brand names
    try:
        br_name = driver.find_element_by_xpath("/html/body/div/div/div[3]/div[1]/div[2]/div[1]/div[1]/div/div[4]/a")
        brand_names.append(br_name.text.replace('Mobiles',''))
    except NoSuchElementException:
        brand_names.append('-')
    # fetching the smartphone names
    try:
        smt_name = driver.find_element_by_xpath("//h1[@class='yhB1nd']//span")
        name.append(smt_name.text)
    except NoSuchElementException:
        name.append('-')
    
    # fetching colors of smartphone
    try:
        clr = driver.find_element_by_xpath("//table[@class='_14cfVK']//tr[4]//td[2]")
        color.append(clr.text)
    except NoSuchElementException:
        color.append('-')
    time.sleep(2)
    
    # getting the read more button
    try:
        read_more_btn = driver.find_element_by_xpath("//button[@class='_2KpZ6l _1FH0tX']").click()
    except NoSuchElementException:
        pass
    time.sleep(3)
    
    # fetching the display size
    try:
        disp_size = driver.find_element_by_xpath("//div[@class='_1UhVsV']//div[2]//tr[1]//td[2]")
        Display_size.append(disp_size.text)
    except NoSuchElementException:
        Display_size.append
        
    # fetching the display resolution
    try:
        disp_res = driver.find_element_by_xpath("//div[@class='_1UhVsV']//div[2]//tr[2]//td[2]")
        display_resolution.append(disp_res.text)
    except NoSuchElementException:
        display_resolution.append('-')
        
    # fetching the processor information
    try:
        pro = driver.find_element_by_xpath("//div[@class='_1UhVsV']//div[3]//tr[2]//td[2]")
        processor.append(pro.text)
    except NoSuchElementException:
        processor.append('-')
        
    # fetching the processor and number of core details
    try:
        pro_core = driver.find_element_by_xpath("//div[@class='_1UhVsV']//div[3]//tr[3]//td[2]")
        processor_core.append(pro_core.text)
    except NoSuchElementException:
        processor_core.append('-')
        
    # fetching the storage/ROM details
    try:
        rom = driver.find_element_by_xpath("//div[@class='_1UhVsV']//div[4]//tr[1]//td[2]")
        storage.append(rom.text)
    except NoSuchElementException:
        storage.append('-')
        
    # fetching the RAM information
    try:
        ram = driver.find_element_by_xpath("//div[@class='_1UhVsV']//div[4]//tr[2]//td[2]")
        RAM.append(ram.text)
    except NoSuchElementException:
        RAM.append('-')
    time.sleep(2)
    
   
        
    # fetching the secondary camera information
    try:
        sec_cam = driver.find_element_by_xpath("//div[@class='_1UhVsV']//div[5]//tr[5]//td[2]")
        s_cam.append(sec_cam.text)
    except NoSuchElementException:
        s_cam.append('-')        
   
    # fetching the price of the smartphone
    try:
        price = driver.find_element_by_xpath("//div[@class='_30jeq3 _16Jk6d']")
        prices.append(price.text.replace('₹','Rs. '))
    except NoSuchElementException:
        prices.append('-')

In [468]:
Req_info=pd.DataFrame({})
Req_info["Brand Name"]=brand_names[:10]
Req_info["Smartphone Name"]=name[:10]
Req_info["Color"]=color[:10]
Req_info["RAM"]=RAM[:10]
Req_info["Storage/ROM"]=storage[:10]
Req_info["Display Size"]=Display_size[:10]
Req_info["Display Resolution"]=display_resolution[:10]
Req_info["Processor"]=processor[:10]
Req_info["Processor-Core"]=processor_core[:10]
Req_info["Price"]=prices[:10]
Req_info["Product Url"]=urls[:10]

Req_info

,Brand Name,Smartphone Name,Color,RAM,Storage/ROM,Display Size,Display Resolution,Processor,Processor-Core,Price,Product Url
0,realme,"realme 8i (Space Black, 64 GB) (4 GB RAM)",Space Black,4 GB,64 GB,16.76 cm (6.6 inch),2412 x 1080 Pixels,MediaTek Helio G96,Octa Core,"Rs. 12,999",https://www.flipkart.com/realme-8i-space-black...
1,realme,"realme 8i (Space Purple, 64 GB) (4 GB RAM)",Space Purple,4 GB,64 GB,16.76 cm (6.6 inch),2412 x 1080 Pixels,MediaTek Helio G96,Octa Core,"Rs. 12,999",https://www.flipkart.com/realme-8i-space-purpl...
2,realme,"realme 8i (Space Purple, 128 GB) (6 GB RAM)",Space Purple,6 GB,128 GB,16.76 cm (6.6 inch),2412 x 1080 Pixels,MediaTek Helio G96,Octa Core,"Rs. 14,999",https://www.flipkart.com/realme-8i-space-purpl...
3,Infinix,"Infinix Hot 10 Play (7° Purple, 32 GB) (3 GB ...",7° Purple,3 GB,32 GB,17.32 cm (6.82 inch),1640 x 720 Pixels,MediaTek Helio G35,Octa Core,"Rs. 8,299",https://www.flipkart.com/infinix-hot-10-play-7...
4,Infinix,"Infinix Hot 10 Play (Aegean Blue, 32 GB) (3 G...",Aegean Blue,3 GB,32 GB,17.32 cm (6.82 inch),1640 x 720 Pixels,MediaTek Helio G35,Octa Core,"Rs. 8,299",https://www.flipkart.com/infinix-hot-10-play-a...
5,realme,"realme 8i (Space Black, 128 GB) (6 GB RAM)",Space Black,6 GB,128 GB,16.76 cm (6.6 inch),2412 x 1080 Pixels,MediaTek Helio G96,Octa Core,"Rs. 14,999",https://www.flipkart.com/realme-8i-space-black...
6,POCO,"POCO C3 (Arctic Blue, 64 GB) (4 GB RAM)",Arctic Blue,4 GB,64 GB,16.59 cm (6.53 inch),1600 x 720 Pixels,Mediatek Helio G35,Octa Core,"Rs. 8,299",https://www.flipkart.com/poco-c3-arctic-blue-6...
7,Infinix,"Infinix Hot 10 Play (7° Purple, 64 GB) (4 GB ...",7° Purple,4 GB,64 GB,17.32 cm (6.82 inch),1640 x 720 Pixels,MediaTek Helio G35,Octa Core,"Rs. 7,999",https://www.flipkart.com/infinix-hot-10-play-7...
8,Infinix,"Infinix Hot 10 Play (Aegean Blue, 64 GB) (4 G...",Aegean Blue,4 GB,64 GB,17.32 cm (6.82 inch),1640 x 720 Pixels,MediaTek Helio G35,Octa Core,"Rs. 7,999",https://www.flipkart.com/infinix-hot-10-play-a...
9,Infinix,"Infinix Hot 10 Play (Morandi Green, 64 GB) (4...",Morandi Green,4 GB,64 GB,17.32 cm (6.82 inch),1640 x 720 Pixels,MediaTek Helio G35,Octa Core,"Rs. 7,999",https://www.flipkart.com/infinix-hot-10-play-m...

In [469]:
Req_info.to_csv('FlipkartSmartphonescrape.csv') # Saving as .csv file

Q5.Write a program to scrap geospatial coordinates (latitude, longitude) of a city searched on 
google maps.

In [55]:
driver = webdriver.Chrome("chromedriver.exe")
url =  'https://www.google.co.in/maps?hl=en&authuser=0'
driver.get(url)

In [56]:
user_input = input("city name:")

city name:Hyderabad

In [57]:
search_bar = driver.find_element_by_xpath("//input[@id='searchboxinput']")
search_bar.send_keys(user_input)
search_btn = driver.find_element_by_xpath("//button[@class='searchbox-searchbutton']")
search_btn.click()

In [58]:
url = driver.current_url

In [59]:
url

'https://www.google.co.in/maps/place/Hyderabad,+Telangana/@17.4128084,78.1278297,10z/data=!3m1!4b1!4m5!3m4!1s0x3bcb99daeaebd2c7:0xae93b78392bafbc2!8m2!3d17.385044!4d78.486671?hl=en&authuser=0'

In [60]:
import re

In [62]:
co_ord = re.findall(r'@(.*),',url)[0].split(",")

In [63]:
co_ord

['17.4128084', '78.1278297']

In [64]:
Lattitude = co_ord[0]

In [65]:
Lattitude

'17.4128084'

In [66]:
Longitude = co_ord[1]

In [67]:
Longitude

'78.1278297'

In [72]:
print("Co-ordinates of Hyderabad are:")
print("Lattitude:", co_ord[0])
print("Longitude:", co_ord[1])

Co-ordinates of Hyderabad are:
Lattitude: 17.4128084
Longitude: 78.1278297

In [ ]:
driver.close()

Q6.Write a program to scrap details of all the funding deals for second quarter (i.e. July 20 –
September 20) from trak.in.

In [76]:
driver = webdriver.Chrome("chromedriver.exe")
url =  'https://trak.in/'
driver.get(url)

In [80]:
sel_fd=driver.find_element_by_xpath('/html/body/div[1]/header/div[2]/div/div/div/div/nav/ul/li[9]/a')
sel_fd.click()

In [81]:
driver.current_url

'https://trak.in/india-startup-funding-investment-2015/'

In [96]:
# creating empty data sets for the 

date = []
comp_name = []
sub_vert = []
industry = []
city = []
inv_name = []
inv_typ = []
amt = []

In [121]:
for i in range(48,51):  # since data is present in tables 48-50
    
    try:
        date_tag = driver.find_elements_by_xpath(f"//*[@id='tablepress-{i}']/tbody/tr/td[2]")
        for i in date_tag:
            date.append(i.text)
    except NoSuchElementException:
        date.append('-')

In [ ]:
for i in range(48,51):
 
    try:
        name_tag = driver.find_elements_by_xpath(f"//*[@id='tablepress-{i}']/tbody/tr/td[3]/a")
        for j in name_tag:
            comp_name.append(j.text)
    except NoSuchElementException:
        comp_name.append('-')
        
comp_name

In [ ]:
for i in range(48,51):
    
    try:
        industry_ = driver.find_elements_by_xpath(f"//*[@id='tablepress-{i}']/tbody/tr/td[4]")
        for p in industry_:
            industry.append(p.text)
    except NoSuchElementException:
        industry.append('-')    
        
industry

In [99]:
for i in range(48,51):
    
    
    try:
        sub_vrt = driver.find_elements_by_xpath(f"//*[@id='tablepress-{i}']/tbody/tr/td[5]")
        for k in sub_vrt:
            sub_vert.append(k.text)
    except NoSuchElementException:
         sub_vert.append('-')

In [102]:
for i in range(48,51):        
    
    try:
        city_ = driver.find_elements_by_xpath(f"//*[@id='tablepress-{i}']/tbody/tr/td[6]")
        for l in city_:
            city.append(l.text)
    except NoSuchElementException:
        city.append('-')

In [104]:
for i in range(48,51):
    
    try:
        invname_ = driver.find_elements_by_xpath(f"//*[@id='tablepress-{i}']/tbody/tr/td[7]")
        for m in invname_:
            inv_name.append(m.text)
    except NoSuchElementException:
        inv_name.append('-')

In [131]:
for i in range(48,51):        
    
    try:
        invtyp_  = driver.find_elements_by_xpath(f"//*[@id='tablepress-{i}']/tbody/tr/td[8]")
        for n in invtyp_:
            inv_typ.append(n.text)
    except NoSuchElementException:
        inv_typ.append('-')
        
for i in range(0,len(inv_typ)): #replacing misssing values with '-'
    if inv_typ[i]=="":
        inv_typ[i] = "-"

In [124]:
        
for i in range(48,51): 
    
    try:
        amt_tag = driver.find_elements_by_xpath(f"//*[@id='tablepress-{i}']/tbody/tr/td[9]")
        for o in amt_tag:
            amt.append(o.text)
    except NoSuchElementException:
        amt.append('-')

In [133]:
trek_data = pd.DataFrame({})
trek_data['Comp_name']=comp_name[:30]
trek_data['Date']=date[:30]
trek_data['Industry']=industry[:30]
trek_data['Sub_vertical']=sub_vert[:30]
trek_data['City']=city[:30]
trek_data['Inv_Name']=inv_name[:30]
trek_data['Inv_type']=inv_typ[:30]
trek_data['Amt']=amt[:30]

trek_data

,Comp_name,Date,Industry,Sub_vertical,City,Inv_Name,Inv_type,Amt
0,Flipkart,15/07/2020,E-commerce,E-commerce,Bangalore,Walmart Inc,M&A,"1,200,000,000"
1,Vedantu,16/07/2020,EduTech,Online Tutoring,Bangalore,Coatue Management,Series D,"100,000,000"
2,Crio,16/07/2020,EduTech,Learning Platform for Developers,Bangalore,021 Capital,pre-Series A,"934,160"
3,goDutch,14/07/2020,FinTech,Group Payments,Mumbai,"Matrix India,Y Combinator, Global Founders Cap...",Seed,"1,700,000"
4,Mystifly,13/07/2020,Airfare Marketplace,"Ticketing, Airline Retailing, and Post-Ticketi...",Singapore and Bangalore,Recruit Co. Ltd.,pre-Series B,"3,300,000"
5,JetSynthesys,09/07/2020,Gaming and Entertainment,Gaming and Entertainment,Pune,Adar Poonawalla and Kris Gopalakrishnan.,Venture-Series Unknown,"400,000"
6,gigIndia,10/07/2020,Marketplace,"Crowd Sourcing, Freelance",Pune,Incubate Fund India and Beyond Next Ventures,pre-Series A,"974,200"
7,PumPumPum,15/07/2020,Automotive Rental,Used Car-leasing platform,Gurgaon,Early Adapters Syndicate,Seed,"292,800"
8,FLYX,14/07/2020,OTT Player,Streaming Social Network,New York and Delhi,"Raj Mishra, founder of AIT Global Inc",pre-Seed,"200,000"
9,Open Appliances Pvt. Ltd.,13/07/2020,Information Technology,Internet-of-Things Security Solutions,Bangalore,Unicorn India Ventures,Venture-Series Unknown,"500,000"
10,Practo,15/08/2020,HealthTech,Health care and Wellness,Bangalore,A1A Company,Series F,"32,000,000"
11,Medlife,13/08/2020,E-commerce,Online Pharmacy,Bangalore,Prasid Uno Family Trust and SC Credit Fund,-,"23,000,000"
12,HungerBox,13/08/2020,FoodTech,Online Food Delivery Service,Bangalore,"One97, Sabre Partners Trust, Pratithi Investme...",Series D1,"1,560,000"
13,Dunzo,04/08/2020,Hyper-local Logistics,Online Delivery Services,Bangalore,Existing Backers,In Progress,"30,000,000"
14,Terra.do,11/08/2020,EduTech,"Online Climate School, E-learning","Stanford, California,","Stanford Angels and Entrepreneurs (India), BEE...",Seed,"1,400,000"
15,Classplus,12/08/2020,EduTech,"E-learning, Online Tutoring",Noida,Falcon Edge,In Progress,"upto 15,000,000"
16,Niyo,14/08/2020,FinTech,Financial Services,Bangalore,Niyo Solutions Inc.,-,"6,000,000"
17,ZestMoney,10/08/2020,FinTech,Financial Services,Bangalore,Primrose Hills Ventures,-,"10,670,000"
18,FreshToHome,07/08/2020,E-commerce,Food Delivery,Bangalore,Ascent Capital,Venture,"16,200,000"
19,Eduvanz,13/08/2020,FinTech,Financial Services,Mumbai,"Sequoia India, Unitus",Series A,"5,000,000"
20,Byju’s,08/09/2020,EduTech,Online Tutoring,Bangalore,"Silver Lake, Tiger Global, General Atlantic an...",Private Equity,"500,000,000"
21,mCaffeine,12/09/2020,Personal Care,Skincare & Haircare,Mumbai,"Amicus Capital Private Equity I LLP, Amicus Ca...",Series B,"3,000,000"
22,Qshala,09/09/2020,EduTech,Online Curiosity Platform for Kids,Bangalore,Rainmatter Capital,Angel,"370,000"
23,Winzo,02/09/2020,Online Gaming,Online Gaming,New Delhi,"Kalaari Capital Partners, IndigoEdge Managemen...",Series B,"15,500,000"
24,Hippo Video,09/09/2020,Video Customer Experience(CX) Platform,Video Customer Experience(CX) Platform,"Newark, Delaware, United States of Amercia","Alpha Wave Incubation, Exfinity Venture Partne...",Series A,"4,500,000"
25,Melorra,07/09/2020,E-commerce,Online Jewelry Store,Bangalore,"Shadow Holdings, Lightbox.",Debt Financing,"upto 8,900,000"
26,1mg,07/09/2020,E-commerce,Online Pharmacy,Gurgaon,"Gaja Capital, Tata Capital, Partners Group",In Progress,"100,000,000"
27,mfine,31/08/2020,HealthTech,On-Demand Healthcare Services,Bangalore,Caretech Pte Inc,Series B,"5,400,000"
28,Apna,31/08/2020,Human Resources,Recruitment Platform,Bangalore,Lightspeed India and Sequoia Capital India,Series A,"8,000,000"
29,Railofy,03/09/2020,Transportation,WL & RAC protection platform,Mumbai,Chiratae Ventures,Seed,"950,000"

In [134]:
driver.close()

Q7.Write a program to scrap all the available details of best gaming laptops from digit.in

In [216]:
driver = webdriver.Chrome("chromedriver.exe")
url =  'https://www.digit.in/'
driver.get(url)

In [217]:
top10btn = driver.find_element_by_xpath('/html/body/div[1]/div/div[4]/ul/li[4]/a')
top10btn.click() #clicking on top 10 button

In [218]:
sel_gaming=driver.find_element_by_xpath('/html/body/div[3]/div/div/div[3]/div[2]/ul/li[26]/a')
sel_gaming.click()

In [219]:
name = []
os = []
disp = []
mem = []
price = []
Processor = []
GraphProc= []
dim = []
wt = []
desc = []

In [220]:
name_  = driver.find_elements_by_xpath("//*[@id='summtable']/tbody/tr/td[1]")
for n in name_:
    name.append(n.text)

In [221]:
name

['Alienware Area 51M R2',
 'Alienware m15 R3',
 'ASUS ROG Strix Scar 15',
 'Asus ROG Zephyrus G14',
 'Lenovo Legion 5i',
 'ASUS ROG ZEPHYRUS DUO 15',
 'Acer Aspire 7 gaming']

In [222]:
price_  = driver.find_elements_by_xpath("//td[@class='smprice']")
for p in price_:
    price.append(p.text)
price

['N/A', '₹ 341,990', 'N/A', '₹ 164,990', '₹ 76,988', '₹ 185,000', '₹ 64,370']

In [223]:
try:
    os_ = driver.find_elements_by_xpath("//div[@class='Spcs-details']//tr[3]//td[3]")
    for i in os_:
        os.append(i.text)
except NoSuchElementException:
    os.append('-')

os

['Windows 10 Home',
 'Windows 10 Home',
 'Windows 10 Home',
 'Windows 10 Home',
 'Windows 10 Pro',
 'Windows 10',
 'Windows 10 Home']

In [224]:
disp_ = driver.find_elements_by_xpath("//div[@class='Spcs-details']//tr[4]//td[3]")
for d in disp_:
    disp.append(d.text)

In [225]:
disp

['17.3" (1920 x 1080)',
 '15.6" (3840 x 2160)',
 '15.6" (1920 x 1080)',
 '14" (1920 x 1080)',
 '15.6" (1920 x 1080)',
 '15.6" (3840 x 1100)',
 '15.6" (1920 x 1080)']

In [226]:
Processor_ = driver.find_elements_by_xpath("//div[@class='Spcs-details']//tr[5]//td[3]")
for k in Processor_:
    Processor.append(k.text)

In [227]:
Processor

['10th Generation Intel® Core™ i7-10700 | 2.90 GHz',
 '10th Generation Intel® Core™ i9-10980HK | NA',
 'AMD Ryzen™ 9 5900HX | 3.3 GHz',
 'AMD 3rd Generation Ryzen 9 | 3.3 GHz',
 '10th Generation Intel® Core™ i5-10300H | 2.50 GHz',
 'Intel Core i7 10th Gen 10875H | NA',
 'AMD Ryzen™ 5-5500U hexa-core | NA']

In [228]:
GraphProc_ = driver.find_elements_by_xpath("//div[@class='Spcs-details']//tr[9]//td[3]")
for g in GraphProc_:
    GraphProc.append(g.text)

GraphProc

['Intel® UHD Graphics 630',
 'NA',
 'NVIDIA® GeForce RTX™ 3070',
 'NVIDIA GeForce RTX 2060',
 'NVIDIA® GeForce® GTX 1650 4GB',
 'NVIDIA GeForce RTX 2070 Max-Q',
 'NVIDIA® GeForce® GTX 1650']

In [229]:
mem_ = driver.find_elements_by_xpath("//div[@class='Spcs-details']//tr[6]//td[3]")
for i in mem_:
    mem.append(i.text)
        
mem

['1 TB SSD/16 GBGB DDR4',
 '1 TB SSD/16 GBGB DDR4',
 '1 TB SSD/16 GBGB DDR4',
 '1 TB SSD/16 GBGB DDR4',
 '1 TB SSD/16 GBGB DDR4',
 '512 GB SSD/4 GBGB DDR4',
 '512 GB SSD/8 GBGB DDR4']

In [230]:
dim_ = driver.find_elements_by_xpath("//div[@class='Spcs-details']//tr[8]//td[3]")
for m in dim_:
    dim.append(m.text)
dim

['27.65 x 402.6 x 319.14',
 'NA',
 '35.4 x 25.9 x 2.26',
 '32.5 x 22.1 x 1.8',
 '363.06 x 259.61 x 23.57',
 '268.30 x 360.00 x 20.90',
 '2.29 x 36.3 x 25.4']

In [231]:
weight = driver.find_elements_by_xpath("//div[@class='Spcs-details']//tr[7]//td[3]")
for j in weight:
    wt.append(j.text)
wt

['4.1', 'NA', '2.30', '1.65', '2.3', '2.4', '2.15']

In [232]:
desc_ = driver.find_elements_by_xpath("//div[@class='Section-center']/p")
for k in desc_:
    desc.append(k.text)
desc

["If you want the absolute best when it comes to performance, then the Alienware Area 51M should be on top of your list. It is essentially a desktop replacement that leaves no stones unturned when it comes to delivering pure performance for gaming. It's basically a desktop in disguise, featuring up to 10th gen Intel Core i9K processors and Nvidia RTX 20-series GPU. It's worth pointing out that Area 51M is not exactly suitable for carrying around often. It's a desktop replacement that can be moved around but it's best to set it on a desk. All the variants feature a 71.1-inch display and you can configure it with panels that offer up to 4K resolution.",
 "If the Area 51M is a bit too much for you then you might want to check out the Alienware m15 R3. It's a more portable offering from the folks over at Alienware but it still packs the punch to deliver solid performance. The company hasn't updated these laptops in India with the latest 11th gen Intel Core processors, but a refresh is due anytime now. In fact, Alienware has also launched a Ryzen edition in the global market, so you might want to check it out before dropping big money on this laptop.",
 "When the ASUS ROG Strix Scar 15 ended up on our test bench, we immediately knew it was overkill. But you know what? It's a good kind of overkill. ASUS' annual upgrade to the Scar lineup saw some significant changes this year and we like most of them. The Asus ROG Strix Scar 15 comes with up to AMD Ryzen 9 5900HX and Nvidia GeForce RTX 3080. The laptop also features per-key RGB on its opto-mechanical keyboard. The new Scar laptops also have a slightly new design, making them look a little different from the older ones. It's also worth pointing out that the laptop comes with a 15.6-inch 1440p display with a refresh rate of 165Hz.",
 'The Asus Zephyrus G14 is a first-of-its-kind gaming laptop, featuring a high-power 8-core CPU in a 14-inch chassis. Powered by the AMD Ryzen 4000 series processors going all the way up to Ryzen 9 4900HS and an Nvidia GeForce RTX 2060, the AMD Zephyrus G14 is a perfect laptop for those kinds of people who like to game and create, but put a priority on doing so using a light-weight machine.',
 "Lenovo's Legion 5i is also a suitable laptop for most people as it packs a 10th gen Intel Core i5 or an i7 processor with up to an Nvidia GeForce RTX 2060 GPU. You get a 15.6-inch display with this laptop and there's support for up to 144Hz as well. If you want a bigger screen size, then you might want to check out the Lenovo Legion 7i which also comes with slightly better internals for improved performance.",
 'The machine is powered by an Intel Core i7-10875H processor, offering 8 cores and 16 threads. So, you can leave behind all your concerns around the CPU bottlenecking the overall performance during gaming. With an Nvidia GeForce RTX 2070 Max-Q, this laptop can manage pretty much anything game you throw at it and then some more. The star of the show however is the awesome 300Hz refresh rate capable, 1080p IPS panel on this gaming laptop. Yes, you read that correctly, 300Hz, which means you can get silky smooth, brag-worthy 300FPS on e-sports centric games on this machine.',
 'The Acer Aspire 7 gaming laptop is a very capable laptop that has made it to a lot of our recommendation lists. It costs less than Rs 60,000 but it packs a decent set of internals that should be enough to handle your gaming needs. The laptop even managed to run a lot of modern AAA titles without any issues even though it only has a GTX 1650 GPU. The Ryzen 5 5500U processor inside this laptop runs the show flawlessly. It also has a really good battery life, something that often goes missing when it comes to gaming laptops. You can check out our review of the laptop right here.']

In [233]:
GamingLap_info=pd.DataFrame({})
GamingLap_info['Name']=name
GamingLap_info['Operating System']=os
GamingLap_info['Display']=disp
GamingLap_info['Memory']=mem
GamingLap_info['Processor']=Processor
GamingLap_info['Graphic Processor']=GraphProc
GamingLap_info['Dimensions']=dim
GamingLap_info['Weight']=wt
GamingLap_info['Description']=desc
GamingLap_info['Price']=price

GamingLap_info

,Name,Operating System,Display,Memory,Processor,Graphic Processor,Dimensions,Weight,Description,Price
0,Alienware Area 51M R2,Windows 10 Home,"17.3"" (1920 x 1080)",1 TB SSD/16 GBGB DDR4,10th Generation Intel® Core™ i7-10700 | 2.90 GHz,Intel® UHD Graphics 630,27.65 x 402.6 x 319.14,4.1,If you want the absolute best when it comes to...,N/A
1,Alienware m15 R3,Windows 10 Home,"15.6"" (3840 x 2160)",1 TB SSD/16 GBGB DDR4,10th Generation Intel® Core™ i9-10980HK | NA,NA,NA,NA,If the Area 51M is a bit too much for you then...,"₹ 341,990"
2,ASUS ROG Strix Scar 15,Windows 10 Home,"15.6"" (1920 x 1080)",1 TB SSD/16 GBGB DDR4,AMD Ryzen™ 9 5900HX | 3.3 GHz,NVIDIA® GeForce RTX™ 3070,35.4 x 25.9 x 2.26,2.30,When the ASUS ROG Strix Scar 15 ended up on ou...,N/A
3,Asus ROG Zephyrus G14,Windows 10 Home,"14"" (1920 x 1080)",1 TB SSD/16 GBGB DDR4,AMD 3rd Generation Ryzen 9 | 3.3 GHz,NVIDIA GeForce RTX 2060,32.5 x 22.1 x 1.8,1.65,The Asus Zephyrus G14 is a first-of-its-kind g...,"₹ 164,990"
4,Lenovo Legion 5i,Windows 10 Pro,"15.6"" (1920 x 1080)",1 TB SSD/16 GBGB DDR4,10th Generation Intel® Core™ i5-10300H | 2.50 GHz,NVIDIA® GeForce® GTX 1650 4GB,363.06 x 259.61 x 23.57,2.3,Lenovo's Legion 5i is also a suitable laptop f...,"₹ 76,988"
5,ASUS ROG ZEPHYRUS DUO 15,Windows 10,"15.6"" (3840 x 1100)",512 GB SSD/4 GBGB DDR4,Intel Core i7 10th Gen 10875H | NA,NVIDIA GeForce RTX 2070 Max-Q,268.30 x 360.00 x 20.90,2.4,The machine is powered by an Intel Core i7-108...,"₹ 185,000"
6,Acer Aspire 7 gaming,Windows 10 Home,"15.6"" (1920 x 1080)",512 GB SSD/8 GBGB DDR4,AMD Ryzen™ 5-5500U hexa-core | NA,NVIDIA® GeForce® GTX 1650,2.29 x 36.3 x 25.4,2.15,The Acer Aspire 7 gaming laptop is a very capa...,"₹ 64,370"

In [234]:
driver.close()

Q8.Write a python program to scrape the details for all billionaires from www.forbes.com. 
Details to be scrapped: “Rank”, “Name”, “Net worth”, “Age”, “Citizenship”, “Source”, 
“Industry”.

In [245]:
driver = webdriver.Chrome("chromedriver.exe")
url =  'https://www.forbes.com/'
driver.get(url)

In [246]:
click_icon=driver.find_element_by_xpath("//button[@class='icon--hamburger']")
click_icon.click()

In [247]:
hover = driver.find_element_by_xpath("/html/body/div[1]/header/nav/div[3]/ul/li[1]")
hover.click()
time.sleep(3)

In [248]:
world_bill = driver.find_element_by_xpath("/html/body/div[1]/header/nav/div[3]/ul/li[1]/div[2]/ul/li[2]/a")
world_bill.click()

In [249]:
Rank=[]
Name=[]
NetWorth=[]
Age=[]
Citizenship=[]
Source=[]
Industry=[]

In [250]:
name_=driver.find_elements_by_xpath("//div[@class='personName']")
for i in name_:
    Name.append(i.text)
Name

['Jeff Bezos',
 'Elon Musk',
 'Bernard Arnault & family',
 'Bill Gates',
 'Mark Zuckerberg',
 'Warren Buffett',
 'Larry Ellison',
 'Larry Page',
 'Sergey Brin',
 'Mukesh Ambani',
 'Amancio Ortega',
 'Francoise Bettencourt Meyers & family',
 'Zhong Shanshan',
 'Steve Ballmer',
 'Ma Huateng',
 'Carlos Slim Helu & family',
 'Alice Walton',
 'Jim Walton',
 'Rob Walton',
 'Michael Bloomberg',
 'Colin Zheng Huang',
 'MacKenzie Scott',
 'Daniel Gilbert',
 'Gautam Adani & family',
 'Phil Knight & family',
 'Jack Ma',
 'Charles Koch',
 'Julia Koch & family',
 'Masayoshi Son',
 'Michael Dell',
 'Tadashi Yanai & family',
 'François Pinault & family',
 'David Thomson & family',
 'Beate Heister & Karl Albrecht Jr.',
 'Wang Wei',
 'Miriam Adelson',
 'He Xiangjian',
 'Dieter Schwarz',
 'Zhang Yiming',
 'Giovanni Ferrero',
 'Alain Wertheimer',
 'Gerard Wertheimer',
 'Li Ka-shing',
 'Qin Yinglin & family',
 'William Lei Ding',
 'Len Blavatnik',
 'Lee Shau Kee',
 'Jacqueline Mars',
 'John Mars',
 'Yang Huiyan & family',
 'Alexey Mordashov & family',
 'Robin Zeng',
 'Hui Ka Yan',
 'Susanne Klatten',
 'Vladimir Potanin',
 'Dietrich Mateschitz',
 'Pang Kang',
 'Klaus-Michael Kuehne',
 'Vladimir Lisin',
 'Wang Xing',
 'German Larrea Mota Velasco & family',
 'Leonardo Del Vecchio & family',
 'Takemitsu Takizaki',
 'Leonard Lauder',
 'Thomas Peterffy',
 'Vagit Alekperov',
 'Leonid Mikhelson',
 'Jim Simons',
 'Jiang Rensheng & family',
 'Gina Rinehart',
 'Rupert Murdoch & family',
 'Shiv Nadar',
 'Zhang Zhidong',
 'Iris Fontbona & family',
 'Lei Jun',
 'Zhang Yong',
 'Richard Qiangdong Liu',
 'Gennady Timchenko',
 'Stephen Schwarzman',
 'Goh Cheng Liang',
 'Stefan Quandt',
 'Li Xiting',
 'Pierre Omidyar',
 'Stefan Persson',
 'Abigail Johnson',
 'R. Budi Hartono',
 'Andrew Forrest',
 'Ray Dalio',
 'Michael Hartono',
 'Li Shufu',
 'Zhong Huijuan',
 'Xu Hang',
 'Lui Che Woo & family',
 'Emmanuel Besnier',
 'Laurene Powell Jobs & family',
 'Eric Schmidt',
 'Sun Piaoyang',
 'Theo Albrecht, Jr. & family',
 'Alisher Usmanov',
 'Robert Pera',
 'Wu Yajun',
 'Fan Hongwei & family',
 'Dhanin Chearavanont',
 'Peter Woo',
 'Chen Bang',
 'Andrey Melnichenko',
 'Dustin Moskovitz',
 'Su Hua',
 'Donald Newhouse',
 'Petr Kellner',
 'Lee Man Tat',
 'Pavel Durov',
 'James Ratcliffe',
 'Jorge Paulo Lemann & family',
 'Reinhold Wuerth & family',
 'Charlene de Carvalho-Heineken & family',
 'Radhakishan Damani',
 'Wang Chuanfu',
 'Steve Cohen',
 'Ken Griffin',
 'Chen Zhiping',
 'Ernest Garcia, II.',
 'Uday Kotak',
 'Carl Icahn',
 'Suleiman Kerimov & family',
 'Thomas Frist, Jr. & family',
 'Lukas Walton',
 'Mikhail Fridman',
 'Wei Jianjun & family',
 'Zuo Hui',
 'Zhou Qunfei & family',
 'Donald Bren',
 'Hinduja brothers',
 'Lakshmi Mittal',
 'Georg Schaeffler',
 'Eric Yuan & family',
 'Wang Jianlin',
 'Kwong Siu-hing',
 'Robin Li',
 'Pallonji Mistry',
 'Eduardo Saverin',
 'Roman Abramovich',
 'David Tepper',
 'Gong Hongjia & family',
 'Mike Cannon-Brookes',
 'John Menard, Jr.',
 'Seo Jung-jin',
 'Cheng Yixiao',
 'Liang Wengen',
 'Scott Farquhar',
 'Finn Rausing',
 'Jorn Rausing',
 'Kirsten Rausing',
 'Brian Chesky',
 'Joseph Lau',
 'David Duffield',
 'Charoen Sirivadhanabhakdi',
 'Kim Jung-ju',
 'Robert & Philip Ng',
 'Zhang Bangxin',
 'Anders Holch Povlsen',
 'Wang Wenyin',
 'Wang Liping & family',
 'Tatyana Bakalchuk',
 'Michael Platt',
 'Huang Shilin',
 'Ricardo Salinas Pliego & family',
 'Kumar Birla',
 'Dang Yanbao',
 'Cyrus Poonawalla',
 'Robert Kuok',
 'Hank & Doug Meijer',
 'Jack Dorsey',
 'Lu Zhongfang',
 'Ma Jianrong & family',
 'Zhang Tao',
 'Nathan Blecharczyk',
 'John Doerr',
 'Joe Gebbia',
 'Forrest Li',
 'Yu Renrong',
 'Liu Yonghao & family',
 'Gordon Moore',
 'Jeff Yass',
 'Bobby Murphy',
 'Patrick Drahi',
 'Jensen Huang',
 'Alexander Otto',
 'Cen Junda',
 'Joseph Tsai',
 'Aliko Dangote',
 'Marcel Herrmann Telles',
 'Mikhail Prokhorov',
 'Jorge Moll Filho & family',
 'Viktor Rashnikov',
 'Harry Triguboff',
 'Leonid Fedun & family',
 'Eyal Ofer',
 'Evan Spiegel',
 'Luis Carlos Sarmiento']

In [252]:
rank_=driver.find_elements_by_xpath("//div[@class='rank']")
for i in rank_:
    Rank.append(i.text)
Rank

['1.',
 '2.',
 '3.',
 '4.',
 '5.',
 '6.',
 '7.',
 '8.',
 '9.',
 '10.',
 '11.',
 '12.',
 '13.',
 '14.',
 '15.',
 '16.',
 '17.',
 '18.',
 '19.',
 '20.',
 '21.',
 '22.',
 '23.',
 '24.',
 '25.',
 '26.',
 '27.',
 '27.',
 '29.',
 '30.',
 '31.',
 '32.',
 '33.',
 '34.',
 '35.',
 '36.',
 '37.',
 '38.',
 '39.',
 '40.',
 '41.',
 '41.',
 '43.',
 '44.',
 '45.',
 '46.',
 '47.',
 '48.',
 '48.',
 '50.',
 '51.',
 '52.',
 '53.',
 '53.',
 '55.',
 '56.',
 '57.',
 '58.',
 '59.',
 '60.',
 '61.',
 '62.',
 '62.',
 '64.',
 '65.',
 '66.',
 '66.',
 '68.',
 '69.',
 '70.',
 '71.',
 '71.',
 '73.',
 '74.',
 '75.',
 '75.',
 '77.',
 '78.',
 '79.',
 '80.',
 '81.',
 '82.',
 '83.',
 '84.',
 '85.',
 '86.',
 '87.',
 '88.',
 '89.',
 '89.',
 '89.',
 '92.',
 '93.',
 '94.',
 '95.',
 '96.',
 '96.',
 '98.',
 '99.',
 '100.',
 '100.',
 '102.',
 '103.',
 '104.',
 '105.',
 '105.',
 '107.',
 '107.',
 '109.',
 '110.',
 '111.',
 '112.',
 '113.',
 '114.',
 '115.',
 '116.',
 '117.',
 '118.',
 '119.',
 '119.',
 '121.',
 '121.',
 '121.',
 '124.',
 '124.',
 '126.',
 '127.',
 '128.',
 '128.',
 '128.',
 '131.',
 '132.',
 '133.',
 '133.',
 '133.',
 '133.',
 '137.',
 '138.',
 '138.',
 '140.',
 '140.',
 '142.',
 '142.',
 '144.',
 '145.',
 '145.',
 '145.',
 '148.',
 '148.',
 '150.',
 '151.',
 '151.',
 '151.',
 '154.',
 '155.',
 '156.',
 '156.',
 '158.',
 '158.',
 '158.',
 '161.',
 '161.',
 '163.',
 '164.',
 '164.',
 '166.',
 '166.',
 '168.',
 '169.',
 '169.',
 '171.',
 '171.',
 '173.',
 '173.',
 '173.',
 '173.',
 '177.',
 '177.',
 '177.',
 '177.',
 '181.',
 '182.',
 '182.',
 '184.',
 '185.',
 '186.',
 '186.',
 '186.',
 '189.',
 '189.',
 '191.',
 '191.',
 '193.',
 '194.',
 '195.',
 '195.',
 '197.',
 '197.',
 '197.',
 '200.']

In [264]:
net_worth = driver.find_elements_by_xpath("//div[@class='netWorth']")
for i in net_worth:
    NetWorth.append(i.text)

In [259]:
try:
    age_= driver.find_elements_by_xpath("//div[@class='age']")
    for i in age_:
        Age.append(i.text)
except NoSuchElementException:
    Age.append('-')

Age

['57',
 '49',
 '72',
 '65',
 '36',
 '90',
 '76',
 '48',
 '47',
 '63',
 '85',
 '67',
 '66',
 '65',
 '49',
 '81',
 '71',
 '72',
 '76',
 '79',
 '41',
 '50',
 '59',
 '58',
 '83',
 '56',
 '85',
 '58',
 '63',
 '56',
 '72',
 '84',
 '63',
 'N/A',
 '50',
 '75',
 '78',
 '81',
 '37',
 '56',
 '72',
 '70',
 '92',
 '55',
 '49',
 '63',
 '93',
 '81',
 '85',
 '39',
 '55',
 '52',
 '62',
 '58',
 '60',
 '76',
 '65',
 '83',
 '64',
 '42',
 '67',
 '85',
 '75',
 '88',
 '76',
 '70',
 '65',
 '82',
 '67',
 '67',
 '90',
 '75',
 '49',
 '78',
 '51',
 '50',
 '47',
 '68',
 '74',
 '93',
 '54',
 '70',
 '53',
 '73',
 '59',
 '80',
 '59',
 '71',
 '81',
 '57',
 '60',
 '54',
 '92',
 '50',
 '57',
 '65',
 '62',
 '70',
 '67',
 '43',
 '57',
 '54',
 '81',
 '74',
 '55',
 '49',
 '36',
 '39',
 '91',
 '56',
 '91',
 '36',
 '68',
 '81',
 '85',
 '66',
 '66',
 '55',
 '64',
 '52',
 '45',
 '63',
 '62',
 '85',
 '55',
 '82',
 '34',
 '56',
 '57',
 '50',
 '51',
 '88',
 'N/A',
 '70',
 '56',
 '51',
 '66',
 '91',
 '52',
 '91',
 '39',
 '54',
 '63',
 '56',
 '41',
 '81',
 '63',
 '37',
 '64',
 '41',
 '66',
 '61',
 '68',
 '39',
 '69',
 '80',
 '76',
 '53',
 'N/A',
 '41',
 '48',
 '53',
 '55',
 '45',
 '53',
 '54',
 '65',
 '53',
 '48',
 '79',
 '97',
 'N/A',
 '44',
 '78',
 '57',
 '48',
 '37',
 '69',
 '39',
 '43',
 '55',
 '69',
 '92',
 '62',
 '32',
 '57',
 '58',
 '53',
 '56',
 '57',
 '63',
 '71',
 '55',
 '76',
 '72',
 '88',
 '65',
 '70',
 '30',
 '88']

In [261]:
try:
    citizenship_=driver.find_elements_by_xpath("//div[@class='countryOfCitizenship']")
    for i in citizenship_:
        Citizenship.append(i.text)
except NoSuchElementException:
    Citizenship.append('-')

Citizenship

['United States',
 'United States',
 'France',
 'United States',
 'United States',
 'United States',
 'United States',
 'United States',
 'United States',
 'India',
 'Spain',
 'France',
 'China',
 'United States',
 'China',
 'Mexico',
 'United States',
 'United States',
 'United States',
 'United States',
 'China',
 'United States',
 'United States',
 'India',
 'United States',
 'China',
 'United States',
 'United States',
 'Japan',
 'United States',
 'Japan',
 'France',
 'Canada',
 'Germany',
 'China',
 'United States',
 'China',
 'Germany',
 'China',
 'Italy',
 'France',
 'France',
 'Hong Kong',
 'China',
 'China',
 'United States',
 'Hong Kong',
 'United States',
 'United States',
 'China',
 'Russia',
 'Hong Kong',
 'China',
 'Germany',
 'Russia',
 'Austria',
 'China',
 'Germany',
 'Russia',
 'China',
 'Mexico',
 'Italy',
 'Japan',
 'United States',
 'United States',
 'Russia',
 'Russia',
 'United States',
 'China',
 'Australia',
 'United States',
 'India',
 'China',
 'Chile',
 'China',
 'Singapore',
 'China',
 'Russia',
 'United States',
 'Singapore',
 'Germany',
 'Singapore',
 'United States',
 'Sweden',
 'United States',
 'Indonesia',
 'Australia',
 'United States',
 'Indonesia',
 'China',
 'China',
 'Hong Kong',
 'Hong Kong',
 'France',
 'United States',
 'United States',
 'China',
 'Germany',
 'Russia',
 'United States',
 'China',
 'China',
 'Thailand',
 'Hong Kong',
 'China',
 'Russia',
 'United States',
 'China',
 'United States',
 'Czechia',
 'Hong Kong',
 'Russia',
 'United Kingdom',
 'Brazil',
 'Germany',
 'Netherlands',
 'India',
 'China',
 'United States',
 'United States',
 'China',
 'United States',
 'India',
 'United States',
 'Russia',
 'United States',
 'United States',
 'Russia',
 'China',
 'China',
 'Hong Kong',
 'United States',
 'United Kingdom',
 'India',
 'Germany',
 'United States',
 'China',
 'Hong Kong',
 'China',
 'Ireland',
 'Brazil',
 'Russia',
 'United States',
 'Hong Kong',
 'Australia',
 'United States',
 'South Korea',
 'China',
 'China',
 'Australia',
 'Sweden',
 'Sweden',
 'Sweden',
 'United States',
 'Hong Kong',
 'United States',
 'Thailand',
 'South Korea',
 'Singapore',
 'China',
 'Denmark',
 'China',
 'China',
 'Russia',
 'United Kingdom',
 'China',
 'Mexico',
 'India',
 'China',
 'India',
 'Malaysia',
 'United States',
 'United States',
 'China',
 'China',
 'China',
 'United States',
 'United States',
 'United States',
 'Singapore',
 'China',
 'China',
 'United States',
 'United States',
 'United States',
 'France',
 'United States',
 'Germany',
 'China',
 'Canada',
 'Nigeria',
 'Brazil',
 'Russia',
 'Brazil',
 'Russia',
 'Australia',
 'Russia',
 'Israel',
 'United States',
 'Colombia']

In [262]:
try:
    source_=driver.find_elements_by_xpath("//div[@class='source']")
    for i in source_:
        Source.append(i.text)
except NoSuchElementException:
    Source.append('-')

len(Source)

200

In [263]:
try:
    industry_=driver.find_elements_by_xpath("//div[@class='category']")
    for i in industry_:
        Industry.append(i.text)
except NoSuchElementException:
    Industry.append('-')

Industry

['Technology',
 'Automotive',
 'Fashion & Retail',
 'Technology',
 'Technology',
 'Finance & Investments',
 'Technology',
 'Technology',
 'Technology',
 'Diversified',
 'Fashion & Retail',
 'Fashion & Retail',
 'Food & Beverage',
 'Technology',
 'Technology',
 'Telecom',
 'Fashion & Retail',
 'Fashion & Retail',
 'Fashion & Retail',
 'Media & Entertainment',
 'Technology',
 'Technology',
 'Finance & Investments',
 'Diversified',
 'Fashion & Retail',
 'Technology',
 'Diversified',
 'Diversified',
 'Telecom',
 'Technology',
 'Fashion & Retail',
 'Fashion & Retail',
 'Media & Entertainment',
 'Fashion & Retail',
 'Service',
 'Gambling & Casinos',
 'Manufacturing',
 'Fashion & Retail',
 'Technology',
 'Food & Beverage',
 'Fashion & Retail',
 'Fashion & Retail',
 'Diversified',
 'Food & Beverage',
 'Technology',
 'Diversified',
 'Real Estate',
 'Food & Beverage',
 'Food & Beverage',
 'Real Estate',
 'Metals & Mining',
 'Energy',
 'Real Estate',
 'Automotive',
 'Metals & Mining',
 'Food & Beverage',
 'Food & Beverage',
 'Logistics',
 'Metals & Mining',
 'Technology',
 'Metals & Mining',
 'Fashion & Retail',
 'Manufacturing',
 'Fashion & Retail',
 'Finance & Investments',
 'Energy',
 'Energy',
 'Finance & Investments',
 'Healthcare',
 'Metals & Mining',
 'Media & Entertainment',
 'Technology',
 'Technology',
 'Metals & Mining',
 'Technology',
 'Food & Beverage',
 'Technology',
 'Energy',
 'Finance & Investments',
 'Manufacturing',
 'Automotive',
 'Healthcare',
 'Technology',
 'Fashion & Retail',
 'Finance & Investments',
 'Finance & Investments',
 'Metals & Mining',
 'Finance & Investments',
 'Manufacturing',
 'Automotive',
 'Healthcare',
 'Healthcare',
 'Gambling & Casinos',
 'Food & Beverage',
 'Technology',
 'Technology',
 'Healthcare',
 'Fashion & Retail',
 'Metals & Mining',
 'Technology',
 'Real Estate',
 'Energy',
 'Diversified',
 'Real Estate',
 'Healthcare',
 'Energy',
 'Technology',
 'Media & Entertainment',
 'Media & Entertainment',
 'Finance & Investments',
 'Food & Beverage',
 'Technology',
 'Manufacturing',
 'Food & Beverage',
 'Manufacturing',
 'Food & Beverage',
 'Fashion & Retail',
 'Automotive',
 'Finance & Investments',
 'Finance & Investments',
 'Manufacturing',
 'Automotive',
 'Finance & Investments',
 'Finance & Investments',
 'Finance & Investments',
 'Healthcare',
 'Fashion & Retail',
 'Energy',
 'Automotive',
 'Real Estate',
 'Technology',
 'Real Estate',
 'Diversified',
 'Metals & Mining',
 'Automotive',
 'Technology',
 'Real Estate',
 'Real Estate',
 'Technology',
 'Construction & Engineering',
 'Technology',
 'Diversified',
 'Finance & Investments',
 'Finance & Investments',
 'Technology',
 'Fashion & Retail',
 'Healthcare',
 'Media & Entertainment',
 'Manufacturing',
 'Technology',
 'Food & Beverage',
 'Food & Beverage',
 'Food & Beverage',
 'Technology',
 'Real Estate',
 'Technology',
 'Food & Beverage',
 'Technology',
 'Real Estate',
 'Service',
 'Fashion & Retail',
 'Metals & Mining',
 'Manufacturing',
 'Fashion & Retail',
 'Finance & Investments',
 'Energy',
 'Fashion & Retail',
 'Diversified',
 'Metals & Mining',
 'Healthcare',
 'Diversified',
 'Fashion & Retail',
 'Technology',
 'Automotive',
 'Fashion & Retail',
 'Fashion & Retail',
 'Technology',
 'Technology',
 'Technology',
 'Media & Entertainment',
 'Manufacturing',
 'Service',
 'Technology',
 'Finance & Investments',
 'Technology',
 'Telecom',
 'Technology',
 'Real Estate',
 'Healthcare',
 'Technology',
 'Manufacturing',
 'Food & Beverage',
 'Finance & Investments',
 'Healthcare',
 'Manufacturing',
 'Real Estate',
 'Energy',
 'Diversified',
 'Technology',
 'Finance & Investments']

In [265]:
TopBillionaire=pd.DataFrame({})
TopBillionaire['Rank']=Rank
TopBillionaire['Name']=Name
TopBillionaire['NetWorth']=NetWorth[:200]
TopBillionaire['Age']=Age
TopBillionaire['Citizenship']=Citizenship
TopBillionaire['Source']=Source
TopBillionaire['Industry']=Industry

TopBillionaire

,Rank,Name,NetWorth,Age,Citizenship,Source,Industry
0,1.,Jeff Bezos,$177 B,57,United States,Amazon,Technology
1,2.,Elon Musk,$151 B,49,United States,"Tesla, SpaceX",Automotive
2,3.,Bernard Arnault & family,$150 B,72,France,LVMH,Fashion & Retail
3,4.,Bill Gates,$124 B,65,United States,Microsoft,Technology
4,5.,Mark Zuckerberg,$97 B,36,United States,Facebook,Technology
...,...,...,...,...,...,...,...
195,195.,Harry Triguboff,$11.2 B,88,Australia,real estate,Real Estate
196,197.,Leonid Fedun & family,$11.1 B,65,Russia,oil,Energy
197,197.,Eyal Ofer,$11.1 B,70,Israel,"real estate, shipping",Diversified
198,197.,Evan Spiegel,$11.1 B,30,United States,Snapchat,Technology
199,200.,Luis Carlos Sarmiento,$11 B,88,Colombia,banking,Finance & Investments

In [266]:
driver.close()

Q9.Write a program to extract at least 500 Comments, Comment upvote and time when comment 
was posted from any YouTube Video.

In [286]:
driver = webdriver.Chrome("chromedriver.exe")
url =  'https://www.youtube.com/'
driver.get(url)

In [287]:
driver.maximize_window()

In [289]:
#selecting the search bar
search_bar = driver.find_element_by_xpath("//input[@id='search']")  
search_bar.send_keys('One Direction')

In [290]:
#clicking on the search button
search_btn=driver.find_element_by_xpath("/html/body/ytd-app/div/div/ytd-masthead/div[3]/div[2]/ytd-searchbox/button/yt-icon")
search_btn.click()

In [291]:
# clicking on the first video

video= driver.find_element_by_xpath("/html/body/ytd-app/div/ytd-page-manager/ytd-search/div[1]/ytd-two-column-search-results-renderer/div/ytd-section-list-renderer/div[2]/ytd-item-section-renderer/div[3]/ytd-video-renderer[1]/div[1]/div/div[1]/div/h3/a/yt-formatted-string")
video.click()

In [306]:
# Creating emty lists
Comment=[]
Upvote=[]
Time=[]

In [301]:
import time
for i in range(1000):
    driver.execute_script("window.scrollBy(0, 1000)"," ")

In [308]:
# scraping comments
try:
    comment_=driver.find_elements_by_xpath("//yt-formatted-string[@id='content-text']")
    for i in comment_:
        Comment.append(i.text)
except NoSuchElementException:
    Comment.append('-')

In [309]:
# scraping upvotes

try:
    upvote_=driver.find_elements_by_xpath("//span[@id='vote-count-middle']")
    for i in upvote_:
        Upvote.append(i.text)
except NoSuchElementException:
    Upvote.append('-')

In [316]:
# Scraping time of the comment uploaded
try:
    time_ = driver.find_elements_by_xpath("//yt-formatted-string[@class='published-time-text above-comment style-scope ytd-comment-renderer']")[:500]
    for i in time_:
        Time.append(i.text)
except NoSuchElementException:
    times.append('-')

In [317]:
YTComments=pd.DataFrame({})
YTComments['Comment']=Comment[:500]
YTComments['UpVote']=Upvote[:500]
YTComments['Time Of Comment']=Time[:500]

YTComments

                                               Comment UpVote Time Of Comment
0    Tommo was probably jealous when Hazza was up n...
1                                                 2:24      1
2                                      Ainda amo❤️😭😥❤️      1
3    I'm leaving this comment here so after a month...      1
4                                     One word: IcOnIC      2
..                                                 ...    ...             ...
495                                        Still love!      1      2 days ago
496                      I have no clue how I got here      1
497  my best friend tortured me into playing this s...      1      2 days ago
498                                   LLEGÓ AL BILLÓN😭
499                                        First time🗿             3 days ago

[500 rows x 3 columns]

Q10.Write a python program to scrape a data for all available Hostels from 
https://www.hostelworld.com/ in “London” location. You have to scrape hostel name, 
distance from city centre, ratings, total reviews, overall reviews, privates from price, dorms 
from price, facilities and property description.

In [382]:
driver = webdriver.Chrome("chromedriver.exe")
url = "https://www.hostelworld.com/"
driver.get(url)

In [324]:
search_bar = driver.find_element_by_id('search-input-field')
search_bar.send_keys("London")
time.sleep(2)

In [327]:
listopt= driver.find_element_by_xpath("//*[@id='predicted-search-results']/li[2]")
listopt.click()

In [328]:
click_search = driver.find_element_by_id("search-button")
click_search.click()

In [341]:
Hostel_name=[]
try:
    name=driver.find_elements_by_xpath("//h2[@class='title body-1']")
    for i in name:
        Hostel_name.append(i.text)
    name_=driver.find_elements_by_xpath("//h2[@class='title title-6']")
    for j in name_:
         Hostel_name.append(j.text)
        
except NoSuchElementException:
    Hostel_name.append('-')
    
len(Hostel_name)

33

In [343]:
Distance=[]

try:
    distance=driver.find_elements_by_xpath("//div[@class='subtitle body-3']")
    for i in distance:
        Distance.append(i.text.replace('Hostel - '," "))
except NoSuchElementException:
    Distance.append('-')
    
len(Distance)

33

In [347]:
Rating=[]
try:
    rating_=driver.find_elements_by_xpath("//div[@class='score orange small']")
    for j in rating_:
        Rating.append(j.text)
    rating = driver.find_elements_by_xpath("//div[@class='score orange big']")
    for i in rating:
        Rating.append(i.text)
except NoSuchElementException:
    Rating.append('-')
Rating

['8.7',
 '9.2',
 '8.5',
 '7.2',
 '9.7',
 '8.7',
 '10',
 '8.1',
 '8.5',
 '8.5',
 '8.2',
 '6.8',
 '8.0',
 '7.4',
 '9.8',
 '6.2',
 '8.1',
 '6.9',
 '8.1',
 '7.9',
 '6.3',
 '8.3',
 '7.8',
 '6.6',
 '9.3',
 '7.0',
 '7.5',
 '8.9',
 '6.8',
 '8.1',
 '7.4',
 '10',
 '8.2']

In [349]:
Tot_Review=[]
try:
    review=driver.find_elements_by_xpath("//div[@class='keyword']")
    for i in review:
        Tot_Review.append(i.text.replace(" Total reviews", " Reviews"))
except NoSuchElementException:
    Tot_Review.append('-')
    
len(Tot_Review)

33

In [350]:
ov_rev=[]
try:
    ov = driver.find_elements_by_xpath("//div[@class='keyword']//span")
    for i in ov:
        ov_rev.append(i.text)
    
except NoSuchElementException:
        over_all.append('-')
        
len(ov_rev)

33

In [372]:
urls = []
try:
    url = driver.find_elements_by_xpath("//a[@class='title-link']")
    for i in url:
        urls.append(i.get_attribute('href'))    
    url_= driver.find_elements_by_xpath("//h2[@class='title title-6']//a")
    for j in url_:
        urls.append(j.get_attribute('href'))
except NoSuchElementException:
    urls.append('-')

In [374]:
len(urls)

33

In [398]:
fac=[]
for i in urls:
    driver.get(i)
    time.sleep(2)
try:
    f=driver.find_element_by_xpath("//ul[@class='facility-sections']")
    fac.append(f.text.replace("/n"," "))
except NoSuchElementException:
    fac.append('--')
fac

['Free\nFree Breakfast Linen Included Free City Maps Free WiFi Free Internet Access Free City Tour\nGeneral\nSecurity Lockers Common Room Bicycle Parking Adaptors Book Exchange Hot Showers Self-Catering Facilities Fridge/Freezer Hair Dryers Iron / Ironing Board Microwave Flexible NRR Follows Covid-19 sanitation guidance\nServices\nInternet access Towels for hire Luggage Storage Tours/Travel Desk 24 Hour Security Housekeeping Late check-out\nFood & Drink\nBar Tea & Coffee Making Facilities\nEntertainment\nBoard Games Games Room Foosball Wi-Fi']

In [474]:
Hostels=pd.DataFrame({})
Hostels['Hostel name']=Hostel_name
Hostels['Distance']=Distance
Hostels["Rating"]=Rating
Hostels['Total_review']=Tot_Review
Hostels["Overall_review"]=ov_rev

Hostels

,Hostel name,Distance,Rating,Total_review,Overall_review
0,Wombat's The City Hostel London,3.6km from city centre,8.7,Fabulous,Fabulous
1,Selina Camden,5.5km from city centre,9.2,Superb,Superb
2,London Backpackers,11.9km from city centre,8.5,Fabulous,Fabulous
3,London Waterloo Hostel,0.7km from city centre Show on Map,7.2,Very Good,Very Good
4,Barmy Badger Backpackers,5.5km from city centre Show on Map,9.7,Superb,Superb
5,Wombat's The City Hostel London,3.6km from city centre Show on Map,8.7,Fabulous,Fabulous
6,Prime Backpackers Angel,3.6km from city centre Show on Map,10,Superb,Superb
7,The Walrus Hostel,0.2km from city centre Show on Map,8.1,Fabulous,Fabulous
8,St Christopher's Village,1.8km from city centre Show on Map,8.5,Fabulous,Fabulous
9,"PubLove @ The Steam Engine, Waterloo",0.5km from city centre Show on Map,8.5,Fabulous,Fabulous
10,Smart Camden Inn Hostel,4.4km from city centre Show on Map,8.2,Fabulous,Fabulous
11,"PubLove @ The Crown, Battersea",4.7km from city centre Show on Map,6.8,Good,Good
12,Safestay London Elephant & Castle,1.7km from city centre Show on Map,8.0,Fabulous,Fabulous
13,St Christopher's Hammersmith,7.5km from city centre Show on Map,7.4,Very Good,Very Good
14,Urbany Hostel London,5.4km from city centre Show on Map,9.8,Superb,Superb
15,"PubLove @ The Green Man, Paddington",4.3km from city centre Show on Map,6.2,Good,Good
16,St Christopher's Greenwich,7.6km from city centre Show on Map,8.1,Fabulous,Fabulous
17,New Cross Inn Hostel,6.1km from city centre Show on Map,6.9,Good,Good
18,St Christopher's Camden,4.3km from city centre Show on Map,8.1,Fabulous,Fabulous
19,St Christopher's Shepherds Bush,7km from city centre Show on Map,7.9,Very Good,Very Good
20,Mapesbury Hostel,8.2km from city centre Show on Map,6.3,Good,Good
21,Hootananny Hostel,5km from city centre Show on Map,8.3,Fabulous,Fabulous
22,Phoenix Hostel,4.2km from city centre Show on Map,7.8,Very Good,Very Good
23,247london Hostel and Private Rooms,8.2km from city centre Show on Map,6.6,Good,Good
24,Burlington Residence,7.1km from city centre Show on Map,9.3,Superb,Superb
25,Clink261,3.2km from city centre Show on Map,7.0,Very Good,Very Good
26,Generator London,3km from city centre Show on Map,7.5,Very Good,Very Good
27,"PubLove @ The White Ferry, Victoria",2.4km from city centre Show on Map,8.9,Fabulous,Fabulous
28,Smart Russell Square Hostel,2.6km from city centre Show on Map,6.8,Good,Good
29,Smart Hyde Park View Hostel,5km from city centre Show on Map,8.1,Fabulous,Fabulous
30,Saint James Backpackers,5.5km from city centre Show on Map,7.4,Very Good,Very Good
31,The Finnish Church in London,4.5km from city centre Show on Map,10,Superb,Superb
32,Queen Elizabeth Chelsea,5.7km from city centre Show on Map,8.2,Fabulous,Fabulous