WEB-SCRAPING ASSIGNMENT(4)

Q1.Scrape the details of most viewed videos on YouTube from Wikipedia:
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/
You need to find following details:
A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [1]:
import selenium
import pandas as pd 
from selenium import webdriver
import time 
from selenium.common.exceptions import NoSuchElementException

import warnings
warnings.filterwarnings('ignore')

Q1.Scrape the details of most viewed videos on YouTube from Wikipedia:
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/
You need to find following details:
A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [3]:
driver=webdriver.Chrome("chromedriver.exe")
url = " https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/ "
driver.get(url)

In [4]:
url = []
for i in driver.find_elements_by_xpath("//a[@class='external text']"):
    url.append(i.get_attribute("href"))

In [5]:
url1=url[3]
url1

'https://en.wikipedia.org/w/index.php?search=List+of+most-viewed+YouTube+videos%2F&title=Special%3ASearch&fulltext=1'

In [6]:

driver.get(url1)

In [7]:
url2 = []
for i in driver.find_elements_by_xpath('//ul[@class="mw-search-results"][1]/li/div/a'):
    url2.append(i.get_attribute("href"))

In [9]:
driver.get(url2[0])

In [14]:
rank = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[1]')
rank

[]

In [17]:
Rank=[]
for i in rank:
    Rank.append(i.text)
Rank

[]

In [16]:
name = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[2]')
Name=[]
for i in name:
    Name.append(i.text)
Name

['"Baby Shark Dance"[23]',
 '"Despacito"[25]',
 '"Johny Johny Yes Papa"[26]',
 '"Shape of You"[27]',
 '"See You Again"[28]',
 '"Bath Song"[31]',
 '"Learning Colors – Colorful Eggs on a Farm"[32]',
 '"Masha and the Bear – Recipe for Disaster"[33]',
 '"Uptown Funk"[34]',
 '"Phonics Song with Two Words"[35]',
 '"Gangnam Style"[36]',
 '"Dame Tu Cosita"[38]',
 '"Sugar"[39]',
 '"Sorry"[40]',
 '"Roar"[41]',
 '"Counting Stars"[42]',
 '"Thinking Out Loud"[43]',
 '"Wheels on the Bus"[44]',
 '"Dark Horse"[45]',
 '"Faded"[46]',
 '"Girls Like You"[47]',
 '"Lean On"[48]',
 '"Bailando"[49]',
 '"Shake It Off"[50]',
 '"Let Her Go"[51]',
 '"Axel F"[52]',
 '"Mi Gente"[53]',
 '"Perfect"[54]',
 '"Waka Waka (This Time for Africa)"[55]',
 '"Hello"[56]']

In [18]:
artist= driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[3]')
Artist=[]
for i in artist:
    Artist.append(i.text)
Artist

["Pinkfong Baby Shark - Kids' Songs & Stories",
 'Luis Fonsi',
 'LooLoo Kids',
 'Ed Sheeran',
 'Wiz Khalifa',
 'Cocomelon – Nursery Rhymes',
 'Miroshka TV',
 'Get Movies',
 'Mark Ronson',
 'ChuChu TV',
 'Psy',
 'El Chombo',
 'Maroon 5',
 'Justin Bieber',
 'Katy Perry',
 'OneRepublic',
 'Ed Sheeran',
 'Cocomelon – Nursery Rhymes',
 'Katy Perry',
 'Alan Walker',
 'Maroon 5',
 'Major Lazer',
 'Enrique Iglesias',
 'Taylor Swift',
 'Passenger',
 'Crazy Frog',
 'J Balvin',
 'Ed Sheeran',
 'Shakira',
 'Adele']

In [19]:
date= driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[5]')
Date=[]
for i in date:
    Date.append(i.text)
Date

['June 17, 2016',
 'January 12, 2017',
 'October 8, 2016',
 'January 30, 2017',
 'April 6, 2015',
 'May 2, 2018',
 'February 27, 2018',
 'January 31, 2012',
 'November 19, 2014',
 'March 6, 2014',
 'July 15, 2012',
 'April 5, 2018',
 'January 14, 2015',
 'October 22, 2015',
 'September 5, 2013',
 'May 31, 2013',
 'October 7, 2014',
 'May 24, 2018',
 'February 20, 2014',
 'December 3, 2015',
 'May 31, 2018',
 'March 22, 2015',
 'April 11, 2014',
 'August 18, 2014',
 'July 25, 2012',
 'June 16, 2009',
 'June 29, 2017',
 'November 9, 2017',
 'June 4, 2010',
 'October 22, 2015']

In [20]:
views= driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[4]')
Views=[]
for i in views:
    Views.append(i.text)
Views

['9.46',
 '7.57',
 '5.78',
 '5.48',
 '5.29',
 '4.55',
 '4.52',
 '4.46',
 '4.32',
 '4.22',
 '4.21',
 '3.63',
 '3.57',
 '3.47',
 '3.45',
 '3.41',
 '3.34',
 '3.29',
 '3.16',
 '3.16',
 '3.14',
 '3.11',
 '3.11',
 '3.10',
 '3.09',
 '3.04',
 '2.99',
 '2.98',
 '2.96',
 '2.89']

In [21]:
df = pd.DataFrame({})
#df["Rank"] = Rank
df["Name"] = Name
df["Artist"] = Artist
df[" Upload date"] = Date
df["Views in billions"] = Views
df

,Name,Artist,Upload date,Views in billions
0,"""Baby Shark Dance""[23]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",9.46
1,"""Despacito""[25]",Luis Fonsi,"January 12, 2017",7.57
2,"""Johny Johny Yes Papa""[26]",LooLoo Kids,"October 8, 2016",5.78
3,"""Shape of You""[27]",Ed Sheeran,"January 30, 2017",5.48
4,"""See You Again""[28]",Wiz Khalifa,"April 6, 2015",5.29
5,"""Bath Song""[31]",Cocomelon – Nursery Rhymes,"May 2, 2018",4.55
6,"""Learning Colors – Colorful Eggs on a Farm""[32]",Miroshka TV,"February 27, 2018",4.52
7,"""Masha and the Bear – Recipe for Disaster""[33]",Get Movies,"January 31, 2012",4.46
8,"""Uptown Funk""[34]",Mark Ronson,"November 19, 2014",4.32
9,"""Phonics Song with Two Words""[35]",ChuChu TV,"March 6, 2014",4.22
10,"""Gangnam Style""[36]",Psy,"July 15, 2012",4.21
11,"""Dame Tu Cosita""[38]",El Chombo,"April 5, 2018",3.63
12,"""Sugar""[39]",Maroon 5,"January 14, 2015",3.57
13,"""Sorry""[40]",Justin Bieber,"October 22, 2015",3.47
14,"""Roar""[41]",Katy Perry,"September 5, 2013",3.45
15,"""Counting Stars""[42]",OneRepublic,"May 31, 2013",3.41
16,"""Thinking Out Loud""[43]",Ed Sheeran,"October 7, 2014",3.34
17,"""Wheels on the Bus""[44]",Cocomelon – Nursery Rhymes,"May 24, 2018",3.29
18,"""Dark Horse""[45]",Katy Perry,"February 20, 2014",3.16
19,"""Faded""[46]",Alan Walker,"December 3, 2015",3.16
20,"""Girls Like You""[47]",Maroon 5,"May 31, 2018",3.14
21,"""Lean On""[48]",Major Lazer,"March 22, 2015",3.11
22,"""Bailando""[49]",Enrique Iglesias,"April 11, 2014",3.11
23,"""Shake It Off""[50]",Taylor Swift,"August 18, 2014",3.10
24,"""Let Her Go""[51]",Passenger,"July 25, 2012",3.09
25,"""Axel F""[52]",Crazy Frog,"June 16, 2009",3.04
26,"""Mi Gente""[53]",J Balvin,"June 29, 2017",2.99
27,"""Perfect""[54]",Ed Sheeran,"November 9, 2017",2.98
28,"""Waka Waka (This Time for Africa)""[55]",Shakira,"June 4, 2010",2.96
29,"""Hello""[56]",Adele,"October 22, 2015",2.89

Q2.Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1st ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [22]:
driver =webdriver.Chrome("chromedriver.exe")
url = " https://www.bcci.tv/ "
driver.get(url)

In [24]:
Url = []
for i in driver.find_elements_by_xpath('//a[@class="navigation__link navigation__link--in-drop-down"]'):
    Url.append(i.get_attribute("href"))

In [25]:
driver.get(Url[0])

In [26]:
title = driver.find_elements_by_xpath('//span[@class="u-unskewed-text fixture__tournament-label u-truncated"]')
Title=[]
for i in title:
    Title.append(i.text)
Title

["2021 ICC MEN'S T20 WORLD CUP",
 "2021 ICC MEN'S T20 WORLD CUP",
 "2021 ICC MEN'S T20 WORLD CUP",
 "2021 ICC MEN'S T20 WORLD CUP",
 "2021 ICC MEN'S T20 WORLD CUP",
 'INDIA V NEW ZEALAND 2021',
 'INDIA V NEW ZEALAND 2021',
 'INDIA V NEW ZEALAND 2021',
 'INDIA V NEW ZEALAND 2021',
 'INDIA V NEW ZEALAND 2021',
 'SOUTH AFRICA V INDIA 2021/2022',
 'SOUTH AFRICA V INDIA 2021/2022',
 'SOUTH AFRICA V INDIA 2021/2022',
 'SOUTH AFRICA V INDIA 2021/2022',
 'SOUTH AFRICA V INDIA 2021/2022',
 'SOUTH AFRICA V INDIA 2021/2022',
 'SOUTH AFRICA V INDIA 2021/2022',
 'SOUTH AFRICA V INDIA 2021/2022',
 'SOUTH AFRICA V INDIA 2021/2022',
 'SOUTH AFRICA V INDIA 2021/2022']

In [27]:
series = driver.find_elements_by_xpath('//span[@class="u-unskewed-text fixture__format"]')
Series=[]
for i in series:
    Series.append(i.text)
Series

['T20I',
 'T20I',
 'T20I',
 'T20I',
 'T20I',
 'T20I',
 'T20I',
 'T20I',
 'TEST',
 'TEST',
 'TEST',
 'TEST',
 'TEST',
 'ODI',
 'ODI',
 'ODI',
 'T20I',
 'T20I',
 'T20I',
 'T20I']

In [28]:
place = driver.find_elements_by_xpath('//p[@class="fixture__additional-info"]/span')
Place=[]
for i in place:
    Place.append(i.text)
Place

['Dubai International Stadium, Dubai',
 'Dubai International Stadium, Dubai',
 'Zayed Cricket Stadium, Abu Dhabi',
 'Dubai International Stadium, Dubai',
 'Dubai International Stadium, Dubai',
 'Sawai Mansingh Stadium, Jaipur',
 'JSCA International Stadium Complex, Ranchi',
 'Eden Gardens, Kolkata',
 'Green Park, Kanpur',
 'Wankhede Stadium, Mumbai',
 'New Wanderers Stadium, Johannesburg',
 'Supersport Park, Centurion',
 'New Wanderers Stadium, Johannesburg',
 'Boland Park, Paarl',
 'Newlands, Cape Town',
 'Newlands, Cape Town',
 'Newlands, Cape Town',
 'Newlands, Cape Town',
 'Boland Park, Paarl',
 'Boland Park, Paarl']

In [29]:
url_ = []
for i in driver.find_elements_by_xpath('//div[@class="js-list"]/a'):
    url_.append(i.get_attribute("href"))

In [31]:
date = driver.find_elements_by_xpath('//div[@class="fixture__full-date"]//span[@class="fixture__date"]')
Date=[]
for i in date:
    Date.append(i.text)
Date

['24',
 '31',
 '03',
 '05',
 '08',
 '17',
 '19',
 '21',
 '25',
 '03',
 '17',
 '26',
 '03',
 '11',
 '14',
 '16',
 '19',
 '21',
 '23',
 '26']

In [32]:
d_ = driver.find_elements_by_xpath('//div[@class="fixture__date-details"]//span[1]')
D_=[]
for i in d_:
    D_.append(i.text)
D_

['OCTOBER',
 'OCTOBER',
 'NOVEMBER',
 'NOVEMBER',
 'NOVEMBER',
 'NOVEMBER',
 'NOVEMBER',
 'NOVEMBER',
 'NOVEMBER',
 'DECEMBER',
 'DECEMBER',
 'DECEMBER',
 'JANUARY',
 'JANUARY',
 'JANUARY',
 'JANUARY',
 'JANUARY',
 'JANUARY',
 'JANUARY',
 'JANUARY']

In [33]:
day = driver.find_elements_by_xpath('//span[@class="fixture__day"]')
Day=[]
for i in day:
    Day.append(i.text)
Day

['Sunday',
 'Sunday',
 'Wednesday',
 'Friday',
 'Monday',
 'Wednesday',
 'Friday',
 'Sunday',
 'Thursday',
 'Friday',
 'Friday',
 'Sunday',
 'Monday',
 'Tuesday',
 'Friday',
 'Sunday',
 'Wednesday',
 'Friday',
 'Sunday',
 'Wednesday']

In [34]:
time = driver.find_elements_by_xpath('//div[@class="fixture__full-date"]//span[2]')
Time=[]
for i in time:
    Time.append(i.text)
Time

['19:30 IST',
 '19:30 IST',
 '19:30 IST',
 '19:30 IST',
 '19:30 IST',
 '19:00 IST',
 '19:00 IST',
 '19:00 IST',
 '09:30 IST',
 '09:30 IST',
 '13:30 IST',
 '13:30 IST',
 '13:30 IST',
 '14:00 IST',
 '14:00 IST',
 '14:00 IST',
 '19:30 IST',
 '19:30 IST',
 '19:30 IST',
 '19:30 IST']

In [35]:
df = pd.DataFrame({})
df["Title"] = Title
df["Series"] = Series
df["Place"] = Place
df["Date"] = Date
df["Month"] = D_
df["Day"] = Day
df["Time"] = Time
df

,Title,Series,Place,Date,Month,Day,Time
0,2021 ICC MEN'S T20 WORLD CUP,T20I,"Dubai International Stadium, Dubai",24,OCTOBER,Sunday,19:30 IST
1,2021 ICC MEN'S T20 WORLD CUP,T20I,"Dubai International Stadium, Dubai",31,OCTOBER,Sunday,19:30 IST
2,2021 ICC MEN'S T20 WORLD CUP,T20I,"Zayed Cricket Stadium, Abu Dhabi",03,NOVEMBER,Wednesday,19:30 IST
3,2021 ICC MEN'S T20 WORLD CUP,T20I,"Dubai International Stadium, Dubai",05,NOVEMBER,Friday,19:30 IST
4,2021 ICC MEN'S T20 WORLD CUP,T20I,"Dubai International Stadium, Dubai",08,NOVEMBER,Monday,19:30 IST
5,INDIA V NEW ZEALAND 2021,T20I,"Sawai Mansingh Stadium, Jaipur",17,NOVEMBER,Wednesday,19:00 IST
6,INDIA V NEW ZEALAND 2021,T20I,"JSCA International Stadium Complex, Ranchi",19,NOVEMBER,Friday,19:00 IST
7,INDIA V NEW ZEALAND 2021,T20I,"Eden Gardens, Kolkata",21,NOVEMBER,Sunday,19:00 IST
8,INDIA V NEW ZEALAND 2021,TEST,"Green Park, Kanpur",25,NOVEMBER,Thursday,09:30 IST
9,INDIA V NEW ZEALAND 2021,TEST,"Wankhede Stadium, Mumbai",03,DECEMBER,Friday,09:30 IST
10,SOUTH AFRICA V INDIA 2021/2022,TEST,"New Wanderers Stadium, Johannesburg",17,DECEMBER,Friday,13:30 IST
11,SOUTH AFRICA V INDIA 2021/2022,TEST,"Supersport Park, Centurion",26,DECEMBER,Sunday,13:30 IST
12,SOUTH AFRICA V INDIA 2021/2022,TEST,"New Wanderers Stadium, Johannesburg",03,JANUARY,Monday,13:30 IST
13,SOUTH AFRICA V INDIA 2021/2022,ODI,"Boland Park, Paarl",11,JANUARY,Tuesday,14:00 IST
14,SOUTH AFRICA V INDIA 2021/2022,ODI,"Newlands, Cape Town",14,JANUARY,Friday,14:00 IST
15,SOUTH AFRICA V INDIA 2021/2022,ODI,"Newlands, Cape Town",16,JANUARY,Sunday,14:00 IST
16,SOUTH AFRICA V INDIA 2021/2022,T20I,"Newlands, Cape Town",19,JANUARY,Wednesday,19:30 IST
17,SOUTH AFRICA V INDIA 2021/2022,T20I,"Newlands, Cape Town",21,JANUARY,Friday,19:30 IST
18,SOUTH AFRICA V INDIA 2021/2022,T20I,"Boland Park, Paarl",23,JANUARY,Sunday,19:30 IST
19,SOUTH AFRICA V INDIA 2021/2022,T20I,"Boland Park, Paarl",26,JANUARY,Wednesday,19:30 IST

In [36]:
driver.close()

Q3.Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/
You need to find following details:
A) Name
B) Description

In [37]:
driver=webdriver.Chrome("chromedriver.exe")
url = "https://www.guru99.com/"
driver.get(url)

In [40]:
driver.maximize_window()

In [42]:
search = driver.find_element_by_id('gsc-i-id1')

In [43]:
search.send_keys("selenium exception handling")

In [44]:
click_btn = driver.find_element_by_xpath('//button[@class="gsc-search-button gsc-search-button-v2"]')
click_btn.click()

In [45]:
URL = []
for i in driver.find_elements_by_xpath('//div[@class="gs-title"]/a'):
    URL.append(i.get_attribute("href"))

In [46]:
driver.get(URL[0])

In [47]:
name = driver.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[1]')
Name=[]
for i in name:
    Name.append(i.text)
Name

['ElementNotVisibleException',
 'ElementNotSelectableException',
 'NoSuchElementException',
 'NoSuchFrameException',
 'NoAlertPresentException',
 'NoSuchWindowException',
 'StaleElementReferenceException',
 'SessionNotFoundException',
 'TimeoutException',
 'WebDriverException',
 'ConnectionClosedException',
 'ElementClickInterceptedException',
 'ElementNotInteractableException',
 'ErrorInResponseException',
 'ErrorHandler.UnknownServerException',
 'ImeActivationFailedException',
 'ImeNotAvailableException',
 'InsecureCertificateException',
 'InvalidArgumentException',
 'InvalidCookieDomainException',
 'InvalidCoordinatesException',
 'InvalidElementStateExceptio',
 'InvalidSessionIdException',
 'InvalidSwitchToTargetException',
 'JavascriptException',
 'JsonException',
 'NoSuchAttributeException',
 'MoveTargetOutOfBoundsException',
 'NoSuchContextException',
 'NoSuchCookieException',
 'NotFoundException',
 'RemoteDriverServerException',
 'ScreenshotException',
 'SessionNotCreatedException',
 'UnableToSetCookieException',
 'UnexpectedTagNameException',
 'UnhandledAlertException',
 'UnexpectedAlertPresentException',
 'UnknownMethodException',
 'UnreachableBrowserException',
 'UnsupportedCommandException']

In [48]:
desc= driver.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[2]')
Desc=[]
for i in desc:
    Desc.append(i.text)
Desc

['This type of Selenium exception occurs when an existing element in DOM has a feature set as hidden.',
 'This Selenium exception occurs when an element is presented in the DOM, but you can be able to select. Therefore, it is not possible to interact.',
 'This Exception occurs if an element could not be found.',
 'This Exception occurs if the frame target to be switched to does not exist.',
 'This Exception occurs when you switch to no presented alert.',
 'This Exception occurs if the window target to be switch does not exist.',
 'This Selenium exception occurs happens when the web element is detached from the current DOM.',
 'The WebDriver is acting after you quit the browser.',
 'Thrown when there is not enough time for a command to be completed. For Example, the element searched wasn’t found in the specified time.',
 'This Exception takes place when the WebDriver is acting right after you close the browser.',
 'This type of Exception takes place when there is a disconnection in the driver.',
 'The command may not be completed as the element receiving the events is concealing the element which was requested clicked.',
 'This Selenium exception is thrown when any element is presented in the DOM. However, it is impossible to interact with such an element.',
 'This happens while interacting with the Firefox extension or the remote driver server.',
 'Exception is used as a placeholder in case if the server returns an error without a stack trace.',
 'This expectation will occur when IME engine activation has failed.',
 'It takes place when IME support is unavailable.',
 'Navigation made the user agent to hit a certificate warning. This can cause by an invalid or expired TLS certificate.',
 'It occurs when an argument does not belong to the expected type.',
 'This happens when you try to add a cookie under a different domain instead of current URL.',
 'This type of Exception matches an interacting operation that is not valid.',
 'It occurs when command can’t be finished when the element is invalid.',
 'This Exception took place when the given session ID is not included in the list of active sessions. It means the session does not exist or is inactive either.',
 'This occurs when the frame or window target to be switched does not exist.',
 'This issue occurs while executing JavaScript given by the user.',
 'It occurs when you afford to get the session when the session is not created.',
 'This kind of Exception occurs when the attribute of an element could not be found.',
 'It takes place if the target provided to the ActionChains move() methodology is not valid. For Example, out of the document.',
 'ContextAware does mobile device testing.',
 'This Exception occurs when no cookie matching with the given pathname found for all the associated cookies of the currently browsing document.',
 'This Exception is a subclass of WebDriverException. This will occur when an element on the DOM does not exist.',
 'This Selenium exception is thrown when the server is not responding because of the problem that the capabilities described are not proper.',
 'It is not possible to capture a screen.',
 'It happens when a new session could not be successfully created.',
 'This occurs if a driver is unable to set a cookie.',
 'Happens if a support class did not get a web element as expected.',
 'This expectation occurs when there is an alert, but WebDriver is not able to perform Alert operation.',
 'It occurs when there is the appearance of an unexpected alert.',
 'This Exception happens when the requested command matches with a known URL but and not matching with a methodology for a specific URL.',
 'This Exception occurs only when the browser is not able to be opened or crashed because of some reason.',
 'This occurs when remote WebDriver does n’t send valid commands as expected.']

In [49]:
df = pd.DataFrame({})
df["Name"] = Name[:10]
df["Description"] = Desc[:10]

df

,Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...

In [51]:
driver.close()

Q4.Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:
A) Rank
B) State
C) GSDP at current price (19-20)
D) GSDP at current price (18-19)
E) Share(18-19)
F) GDP($ billion)

In [52]:
driver =webdriver.Chrome("chromedriver.exe")
url = "http://statisticstimes.com/"
driver.get(url)

In [56]:
driver.maximize_window()

In [57]:
button = driver.find_element_by_xpath("(//button[@class='dropbtn'])[2]")
button.click()

In [58]:
button_nxt = driver.find_element_by_xpath("//div[@class='navbar']/div[2]/div/a[3]")
button_nxt.click()

In [62]:
main_click = driver.find_element_by_xpath("(//ul[@style='list-style-type:none;margin-left:20px;'])//li[1]")
main_click.click()

In [63]:
States = []
for i in driver.find_elements_by_xpath("//table[@id='table_id']/tbody/tr/td[2]"):
    States.append(i.text)
    
States

['Maharashtra',
 'Tamil Nadu',
 'Uttar Pradesh',
 'Gujarat',
 'Karnataka',
 'West Bengal',
 'Rajasthan',
 'Andhra Pradesh',
 'Telangana',
 'Madhya Pradesh',
 'Kerala',
 'Delhi',
 'Haryana',
 'Bihar',
 'Punjab',
 'Odisha',
 'Assam',
 'Chhattisgarh',
 'Jharkhand',
 'Uttarakhand',
 'Jammu & Kashmir',
 'Himachal Pradesh',
 'Goa',
 'Tripura',
 'Chandigarh',
 'Puducherry',
 'Meghalaya',
 'Sikkim',
 'Manipur',
 'Nagaland',
 'Arunachal Pradesh',
 'Mizoram',
 'Andaman & Nicobar Islands']

In [65]:
Ranks = []
for a in driver.find_elements_by_xpath("//table[@id='table_id']/tbody/tr/td[1]"):
    Ranks.append(a.text)

Ranks

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33']

In [68]:
GSDP_ = []
for i in driver.find_elements_by_xpath("//table[@id='table_id']/tbody/tr/td[3]"):
    try:
        GSDP_.append(i.text)
    except:
        GDSP_.append("--")
    
GSDP_

['-',
 '1,845,853',
 '1,687,818',
 '-',
 '1,631,977',
 '1,253,832',
 '1,020,989',
 '972,782',
 '969,604',
 '906,672',
 '-',
 '856,112',
 '831,610',
 '611,804',
 '574,760',
 '521,275',
 '-',
 '329,180',
 '328,598',
 '-',
 '-',
 '165,472',
 '80,449',
 '55,984',
 '-',
 '38,253',
 '36,572',
 '32,496',
 '31,790',
 '-',
 '-',
 '26,503',
 '-']

In [69]:
GSDP_1819 = []
for i in driver.find_elements_by_xpath("//table[@id='table_id']/tbody/tr/td[4]"):
    try:
        GSDP_1819.append(i.text)
    except NoSuchElementException:
        GSDP_1819.append("-")
        

GSDP_1819

['2,632,792',
 '1,630,208',
 '1,584,764',
 '1,502,899',
 '1,493,127',
 '1,089,898',
 '942,586',
 '862,957',
 '861,031',
 '809,592',
 '781,653',
 '774,870',
 '734,163',
 '530,363',
 '526,376',
 '487,805',
 '315,881',
 '304,063',
 '297,204',
 '245,895',
 '155,956',
 '153,845',
 '73,170',
 '49,845',
 '42,114',
 '34,433',
 '33,481',
 '28,723',
 '27,870',
 '27,283',
 '24,603',
 '22,287',
 '-']

In [70]:
Share = []

for i in driver.find_elements_by_xpath("//table[@id='table_id']/tbody/tr/td[5]"):
    try:
        Share.append(i.text)
    except:
        Share.append("-")

Share

['13.94%',
 '8.63%',
 '8.39%',
 '7.96%',
 '7.91%',
 '5.77%',
 '4.99%',
 '4.57%',
 '4.56%',
 '4.29%',
 '4.14%',
 '4.10%',
 '3.89%',
 '2.81%',
 '2.79%',
 '2.58%',
 '1.67%',
 '1.61%',
 '1.57%',
 '1.30%',
 '0.83%',
 '0.81%',
 '0.39%',
 '0.26%',
 '0.22%',
 '0.18%',
 '0.18%',
 '0.15%',
 '0.15%',
 '0.14%',
 '0.13%',
 '0.12%',
 '-']

In [72]:
GDP=[]

for j in driver.find_elements_by_xpath("//table[@id='table_id']/tbody/tr/td[6]"):
    try:
        GDP.append(j.text)
    except:
        GDP.append("-")
        
GDP

['399.921',
 '247.629',
 '240.726',
 '228.290',
 '226.806',
 '165.556',
 '143.179',
 '131.083',
 '130.791',
 '122.977',
 '118.733',
 '117.703',
 '111.519',
 '80.562',
 '79.957',
 '74.098',
 '47.982',
 '46.187',
 '45.145',
 '37.351',
 '23.690',
 '23.369',
 '11.115',
 '7.571',
 '6.397',
 '5.230',
 '5.086',
 '4.363',
 '4.233',
 '4.144',
 '3.737',
 '3.385',
 '-']

In [75]:
df = pd.DataFrame({})
df["Rank"] = Ranks
df["State"] = States
df["GSDP(19-20)"] = GSDP_
df["GSDP(18-19)"] = GSDP_1819
df["Share(18-19)"] = Share
df["GDPBillion[$]"] = GDP

df

,Rank,State,GSDP(19-20),GSDP(18-19),Share(18-19),GDPBillion[$]
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

In [76]:
driver.close()

Q5.Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used

In [182]:
driver=webdriver.Chrome("chromedriver.exe")
url = "https://github.com/"
driver.get(url)

In [183]:
driver.maximize_window()

In [79]:
button = driver.find_elements_by_xpath('//summary[@class="HeaderMenu-summary HeaderMenu-link px-0 py-3 border-0 no-wrap d-block d-lg-inline-block"]')
button

[<selenium.webdriver.remote.webelement.WebElement (session="8df33c5b8e7e3f86aae28422c08a0bf5", element="22025bb8-2669-43ed-b489-49b96c2458e5")>,
 <selenium.webdriver.remote.webelement.WebElement (session="8df33c5b8e7e3f86aae28422c08a0bf5", element="4053fc14-8c5f-46cd-957a-fdc6a3f1066e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="8df33c5b8e7e3f86aae28422c08a0bf5", element="005b8af8-03a2-4715-9c65-0c659ef59829")>]

In [ ]:
button2=button1[1]
button2

In [80]:
button[1].click()

In [82]:
btn = driver.find_element_by_xpath('//div[@class="dropdown-menu flex-auto rounded px-0 pt-2 pb-0 mt-0 pb-4 p-lg-4 position-relative position-lg-absolute left-0 left-lg-n4"]/ul[2]/li[3]/a')
btn.click()

In [84]:
Rep_Title = []
for i in driver.find_elements_by_xpath('//article[@class="Box-row"]/h1/a'):
    Rep_Title.append(i.text)
    
Rep_Title

['WorkerLivesMatter / WorkingTime',
 'nuxt / framework',
 'goplus / gop',
 'KieSun / all-of-frontend',
 'AveYo / MediaCreationTool.bat',
 'twbs / icons',
 'trekhleb / javascript-algorithms',
 'Chakazul / Lenia',
 'microsoft / Swin-Transformer',
 'NVlabs / stylegan3',
 'sentsin / layui',
 'electron-userland / electron-builder',
 '3b1b / videos',
 'zhanwen / MathModel',
 'qiurunze123 / miaosha',
 'smartcontractkit / full-blockchain-solidity-course-py',
 'practical-tutorials / project-based-learning',
 'LeCoupa / awesome-cheatsheets',
 'thingsboard / thingsboard',
 'ascoders / weekly',
 'microsoft / playwright',
 'ddosify / ddosify',
 'apache / apisix',
 'CyC2018 / CS-Notes',
 'PanJiaChen / vue-element-admin']

In [86]:
Rep_Desc = []
for j in driver.find_elements_by_xpath('//article[@class="Box-row"]/p'):
    Rep_Desc.append(j.text)

Rep_Desc

['The Hybrid Vue(3) Framework.',
 'GoPlus - The Go+ language for engineering, STEM education, and data science',
 '你想知道的前端内容都在这',
 'Universal MCT wrapper script for all Windows 10/11 versions from 1507 to 21H2!',
 'Official open source SVG icon library for Bootstrap.',
 '📝 Algorithms and data structures implemented in JavaScript with explanations and links to further readings',
 'Lenia - Mathematical Life Forms',
 'This is an official implementation for "Swin Transformer: Hierarchical Vision Transformer using Shifted Windows".',
 'Official PyTorch implementation of StyleGAN3',
 '采用自身模块规范编写的前端 UI 框架，遵循原生 HTML/CSS/JS 的书写形式，极低门槛，拿来即用。',
 'A complete solution to package and build a ready for distribution Electron app with “auto update” support out of the box',
 'Code for the manim-generated scenes used in 3blue1brown videos',
 '研究生数学建模，本科生数学建模、数学建模竞赛优秀论文，数学建模算法，LaTeX论文模板，算法思维导图，参考书籍，Matlab软件教程，PPT',
 '⭐⭐⭐⭐秒杀系统设计与实现.互联网工程师进阶与分析🙋🐓',
 'Ultimate Solidity, Blockchain, and Smart Contract - Beginner to Expert Full Course | Python Edition',
 'Curated list of project-based tutorials',
 '👩\u200d💻👨\u200d💻 Awesome cheatsheets for popular programming languages, frameworks and development tools. They include everything you should know in one single file.',
 'Open-source IoT Platform - Device management, data collection, processing and visualization.',
 '前端精读周刊。帮你理解最前沿、实用的技术。',
 'Node.js library to automate Chromium, Firefox and WebKit with a single API',
 'High-performance load testing tool, written in Golang.',
 'The Cloud-Native API Gateway',
 '📚 技术面试必备基础知识、Leetcode、计算机操作系统、计算机网络、系统设计',
 '🎉 A magical vue admin https://panjiachen.github.io/vue-element-admin']

In [88]:
Counts = []
for k in driver.find_elements_by_xpath('//article[@class="Box-row"]/div[2]/a[1]'):
    Counts.append(k.text)

Counts

['8,035',
 '1,687',
 '6,101',
 '2,476',
 '501',
 '4,547',
 '122,359',
 '2,096',
 '4,891',
 '2,001',
 '24,842',
 '11,048',
 '968',
 '3,252',
 '22,067',
 '1,781',
 '57,324',
 '24,271',
 '9,452',
 '15,818',
 '28,614',
 '303',
 '6,690',
 '139,876',
 '71,324']

In [89]:
Url = []
for i in driver.find_elements_by_xpath('//article[@class="Box-row"]/h1/a'):
    Url.append(i.get_attribute("href"))

In [94]:
Language=[]
import time

for i in Url:
    driver.get(i)
    time.sleep(3)
    
try:
    language = driver.find_element_by_xpath('//span[@class="color-text-primary text-bold mr-1"]')
    Language.append(language.text)
        
except NoSuchElementException:
    Language.append("-")

['Vue']

In [98]:
df = pd.DataFrame({})
df[" Repository_title"] = Rep_Title[:10]
df[" Repository_description"] = Rep_Desc[:10]
df[" Contributors_count"] = Counts[:10]
#df["Language"] = Language[:10]

df

,Repository_title,Repository_description,Contributors_count
0,WorkerLivesMatter / WorkingTime,The Hybrid Vue(3) Framework.,"8,035"
1,nuxt / framework,"GoPlus - The Go+ language for engineering, STE...","1,687"
2,goplus / gop,你想知道的前端内容都在这,"6,101"
3,KieSun / all-of-frontend,Universal MCT wrapper script for all Windows 1...,"2,476"
4,AveYo / MediaCreationTool.bat,Official open source SVG icon library for Boot...,501
5,twbs / icons,📝 Algorithms and data structures implemented i...,"4,547"
6,trekhleb / javascript-algorithms,Lenia - Mathematical Life Forms,"122,359"
7,Chakazul / Lenia,"This is an official implementation for ""Swin T...","2,096"
8,microsoft / Swin-Transformer,Official PyTorch implementation of StyleGAN3,"4,891"
9,NVlabs / stylegan3,采用自身模块规范编写的前端 UI 框架，遵循原生 HTML/CSS/JS 的书写形式，极低门...,"2,001"

Q6.Scrape the details of top 100 songs on billboard.com.
Url = https://www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board

In [119]:
driver=webdriver.Chrome("chromedriver.exe")
url = "https://www.billboard.com/ "
driver.get(url)

In [120]:
driver.maximize_window()

In [121]:
button = driver.find_element_by_xpath('//div[@id="root"]/div[2]/div[2]/header/div/ul/li[1]/a')
button.click()

In [122]:
btn = driver.find_element_by_xpath('//main[@id="main"]/div[2]/div/div[1]/a')
btn.click()

In [123]:
Song_name = []
for a in driver.find_elements_by_xpath('//div[@class="chart-list__wrapper"]/div/ol/li/button/span[2]/span[1]'):
    Song_name.append(a.text)

Song_name

['Stay',
 'Industry Baby',
 'Fancy Like',
 'Way 2 Sexy',
 'Bad Habits',
 'Good 4 U',
 'Kiss Me More',
 'Levitating',
 'Knife Talk',
 'Essence',
 'Shivers',
 'My Universe',
 'Need To Know',
 'Save Your Tears',
 'Heat Waves',
 "Beggin'",
 'Montero (Call Me By Your Name)',
 'You Right',
 "If I Didn't Love You",
 'Girls Want Girls',
 'Traitor',
 'Take My Breath',
 'Sharing Locations',
 'Chasing After You',
 'Pepas',
 'Thats What I Want',
 'Wockesha',
 'Cold Beer Calling My Name',
 'Happier Than Ever',
 'Fair Trade',
 'Deja Vu',
 'Cold Heart (PNAU Remix)',
 "Memory I Don't Mess With",
 'A-O-K',
 'Love Nwantiti (Ah Ah Ah)',
 'Intro (Hate On Me)',
 'Leave The Door Open',
 'Gyalis',
 'Peaches',
 'Leave Before You Love Me',
 'Love Again',
 'My Boy',
 'Buy Dirt',
 'Hurricane',
 'I Was On A Boat That Day',
 'Family Ties',
 'Meet Me At Our Spot',
 'Wild Side',
 'Late At Night',
 'Have Mercy',
 'You Should Probably Leave',
 'Whole Lotta Money',
 'Cold As You',
 'You Time',
 "Drunk (And I Don't Wanna Go Home)",
 'Baddest',
 "Thinking 'Bout You",
 'Butter',
 'Too Easy',
 'Hot',
 'Your Heart',
 'Woman',
 '2055',
 'No Friends In The Industry',
 'Champagne Poetry',
 'Expensive Pain',
 'Knowing You',
 'Memory',
 'On My Soul',
 'Thot Shit',
 "Drinkin' Beer. Talkin' God. Amen.",
 'Blue Note$ II',
 'Volvi',
 'Todo de Ti',
 'Jugaste y Sufri',
 'Outside (100 MPH)',
 'Same Boat',
 'Last One Standing',
 'In The Bible',
 'Chosen',
 'Bad Morning',
 'Yonaguni',
 'The Feels',
 'Summer Of Love',
 'Get Into It (Yuh)',
 'Nevada',
 'Waves',
 'Life Support',
 'Me (FWM)',
 'Love Train',
 'Feelin Like Tunechi',
 'One Mississippi',
 'Ghost',
 'Sand In My Boots',
 'Ride For You',
 'Esta Danada',
 'Whiskey And Rain',
 'TSU',
 'Love All',
 'No Where']

In [124]:
Artist_name = []
for a in driver.find_elements_by_xpath('//div[@class="chart-list__wrapper"]/div/ol/li/button/span[2]/span[2]'):
    Artist_name.append(a.text)

Artist_name

['The Kid LAROI & Justin Bieber',
 'Lil Nas X & Jack Harlow',
 'Walker Hayes',
 'Drake Featuring Future & Young Thug',
 'Ed Sheeran',
 'Olivia Rodrigo',
 'Doja Cat Featuring SZA',
 'Dua Lipa',
 'Drake Featuring 21 Savage & Project Pat',
 'Wizkid Featuring Justin Bieber & Tems',
 'Ed Sheeran',
 'Coldplay x BTS',
 'Doja Cat',
 'The Weeknd & Ariana Grande',
 'Glass Animals',
 'Maneskin',
 'Lil Nas X',
 'Doja Cat & The Weeknd',
 'Jason Aldean & Carrie Underwood',
 'Drake Featuring Lil Baby',
 'Olivia Rodrigo',
 'The Weeknd',
 'Meek Mill Featuring Lil Baby & Lil Durk',
 'Ryan Hurd With Maren Morris',
 'Farruko',
 'Lil Nas X',
 'Moneybagg Yo',
 'Jameson Rodgers Featuring Luke Combs',
 'Billie Eilish',
 'Drake Featuring Travis Scott',
 'Olivia Rodrigo',
 'Elton John & Dua Lipa',
 'Lee Brice',
 'Tai Verdes',
 'CKay',
 'Meek Mill',
 'Silk Sonic (Bruno Mars & Anderson .Paak)',
 'Capella Grey',
 'Justin Bieber Featuring Daniel Caesar & Giveon',
 'Marshmello X Jonas Brothers',
 'Dua Lipa',
 'Elvie Shane',
 'Jordan Davis Featuring Luke Bryan',
 'Kanye West',
 'Old Dominion',
 'Baby Keem & Kendrick Lamar',
 'THE ANXIETY: WILLOW & Tyler Cole',
 'Normani Featuring Cardi B',
 'Roddy Ricch',
 'Chloe',
 'Chris Stapleton',
 'BIA Featuring Nicki Minaj',
 'Luke Combs',
 'Scotty McCreery',
 'Elle King & Miranda Lambert',
 'Yung Bleu, Chris Brown & 2 Chainz',
 'Dustin Lynch Featuring Lauren Alaina Or MacKenzie Porter',
 'BTS',
 'Gunna & Future',
 'Meek Mill Featuring Moneybagg Yo',
 'Joyner Lucas & J. Cole',
 'Doja Cat',
 'Sleepy Hallow',
 'Drake',
 'Drake',
 'Meek Mill',
 'Kenny Chesney',
 'Kane Brown X blackbear',
 'Meek Mill',
 'Megan Thee Stallion',
 'Chase Rice Featuring Florida Georgia Line',
 'Meek Mill Featuring Lil Uzi Vert',
 'Aventura x Bad Bunny',
 'Rauw Alejandro',
 'Eslabon Armado Featuring DannyLux',
 'Meek Mill',
 'Zac Brown Band',
 'Skylar Grey, Polo G, Mozzy & Eminem',
 'Drake Featuring Lil Durk & Giveon',
 'Blxst & Tyga Featuring Ty Dolla $ign',
 'YoungBoy Never Broke Again',
 'Bad Bunny',
 'TWICE',
 'Shawn Mendes & Tainy',
 'Doja Cat',
 'YoungBoy Never Broke Again',
 'Luke Bryan',
 'YoungBoy Never Broke Again',
 'Meek Mill Featuring A$AP Ferg',
 'Meek Mill',
 'Lil Wayne Featuring Rich The Kid',
 'Kane Brown',
 'Justin Bieber',
 'Morgan Wallen',
 'Meek Mill Featuring Kehlani',
 'Ivan Cornejo',
 'Michael Ray',
 'Drake',
 'Drake Featuring JAY-Z',
 'YoungBoy Never Broke Again']

In [125]:
lweek_btn = driver.find_element_by_xpath("(//button[@class='chart-sorter__button font--semi-bold text--center text--uppercase'])[3]")
lweek_btn.click()

In [126]:
lweek_Ranks = []
for j in driver.find_elements_by_xpath("//span[@class='chart-element__rank__number']"):
    lweek_Ranks.append(j.text)

lweek_Ranks

['12',
 '1',
 '2',
 '4',
 '3',
 '5',
 '6',
 '7',
 '9',
 '8',
 '10',
 '14',
 '17',
 '11',
 '15',
 '13',
 '20',
 '18',
 '16',
 '27',
 '19',
 '22',
 '30',
 '26',
 '21',
 '28',
 '24',
 '81',
 '25',
 '31',
 '29',
 '61',
 '37',
 '44',
 '34',
 '58',
 '59',
 '40',
 '100',
 '39',
 '46',
 '33',
 '49',
 '32',
 '47',
 '88',
 '45',
 '35',
 '48',
 '52',
 '65',
 '43',
 '50',
 '41',
 '86',
 '64',
 '54',
 '38',
 '53',
 '42',
 '55',
 '87',
 '23',
 '79',
 '70',
 '62',
 '57',
 '56',
 '63',
 '68',
 '51',
 '71',
 '98',
 '73',
 '74',
 '99',
 '82',
 '67',
 '84',
 '85',
 '77',
 '80',
 '36',
 '60',
 '66',
 '69',
 '72',
 '75',
 '76',
 '78',
 '83',
 '89',
 '90',
 '91',
 '92',
 '93',
 '94',
 '95',
 '96',
 '97']

In [127]:
prank_btn = driver.find_element_by_xpath("(//button[@class='chart-sorter__button font--semi-bold text--center text--uppercase'])[4]")
prank_btn.click()

In [128]:
PRank = []
for i in driver.find_elements_by_xpath("//span[@class='chart-element__rank__number']"):
    PRank.append(i.text)

PRank

['1',
 '4',
 '6',
 '12',
 '14',
 '17',
 '37',
 '39',
 '58',
 '2',
 '5',
 '8',
 '20',
 '3',
 '7',
 '30',
 '31',
 '9',
 '65',
 '22',
 '44',
 '79',
 '21',
 '98',
 '10',
 '26',
 '82',
 '99',
 '11',
 '18',
 '29',
 '64',
 '13',
 '48',
 '15',
 '19',
 '16',
 '52',
 '70',
 '46',
 '40',
 '27',
 '49',
 '23',
 '73',
 '24',
 '71',
 '87',
 '25',
 '28',
 '50',
 '81',
 '32',
 '61',
 '74',
 '94',
 '33',
 '34',
 '35',
 '36',
 '38',
 '59',
 '100',
 '41',
 '42',
 '43',
 '47',
 '45',
 '84',
 '88',
 '54',
 '68',
 '51',
 '63',
 '53',
 '55',
 '56',
 '57',
 '86',
 '60',
 '62',
 '66',
 '93',
 '67',
 '85',
 '69',
 '72',
 '92',
 '75',
 '76',
 '77',
 '78',
 '80',
 '83',
 '89',
 '90',
 '91',
 '95',
 '96',
 '97']

In [129]:
weeks_btn = driver.find_element_by_xpath("(//button[@class='chart-sorter__button font--semi-bold text--center text--uppercase'])[5]")
weeks_btn.click()

In [130]:
weeks_on_board = []
for i in driver.find_elements_by_xpath("//span[@class='chart-element__rank__number']"):
    weeks_on_board.append(i.text)

weeks_on_board

['8',
 '14',
 '15',
 '37',
 '39',
 '17',
 '31',
 '7',
 '27',
 '55',
 '24',
 '6',
 '21',
 '40',
 '58',
 '71',
 '74',
 '49',
 '82',
 '13',
 '70',
 '3',
 '87',
 '5',
 '16',
 '18',
 '42',
 '10',
 '28',
 '34',
 '45',
 '51',
 '1',
 '52',
 '68',
 '41',
 '48',
 '63',
 '94',
 '2',
 '19',
 '25',
 '33',
 '29',
 '38',
 '53',
 '54',
 '56',
 '62',
 '73',
 '22',
 '43',
 '85',
 '57',
 '67',
 '84',
 '23',
 '44',
 '46',
 '4',
 '9',
 '20',
 '30',
 '32',
 '64',
 '65',
 '79',
 '98',
 '99',
 '11',
 '47',
 '50',
 '88',
 '26',
 '35',
 '77',
 '12',
 '59',
 '61',
 '72',
 '80',
 '81',
 '86',
 '92',
 '93',
 '100',
 '36',
 '60',
 '66',
 '69',
 '75',
 '76',
 '78',
 '83',
 '89',
 '90',
 '91',
 '95',
 '96',
 '97']

In [131]:
df = pd.DataFrame({})
df["Song Name"] = Song_name
df["Artist Name"] = Artist_name
df["Last Week Rank"] = lweek_Ranks
df["Peak Rank"] = PRank
df["Weeks On Chart"] = weeks_on_board

df

,Song Name,Artist Name,Last Week Rank,Peak Rank,Weeks On Chart
0,Stay,The Kid LAROI & Justin Bieber,12,1,8
1,Industry Baby,Lil Nas X & Jack Harlow,1,4,14
2,Fancy Like,Walker Hayes,2,6,15
3,Way 2 Sexy,Drake Featuring Future & Young Thug,4,12,37
4,Bad Habits,Ed Sheeran,3,14,39
...,...,...,...,...,...
95,Esta Danada,Ivan Cornejo,93,90,90
96,Whiskey And Rain,Michael Ray,94,91,91
97,TSU,Drake,95,95,95
98,Love All,Drake Featuring JAY-Z,96,96,96
99,No Where,YoungBoy Never Broke Again,97,97,97

In [132]:
driver.close()

Q7.Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location

In [133]:
driver=webdriver.Chrome("chromedriver.exe")
url = "https://www.naukri.com/ "
driver.get(url)

In [135]:
driver.maximize_window()

In [136]:
button = driver.find_element_by_xpath('//a[@title="Search Recruiters"]')
driver.get(button.get_attribute('href'))

In [139]:
search=driver.find_elements_by_xpath('//div[@class="inpWrap"][1]/input')
search

[<selenium.webdriver.remote.webelement.WebElement (session="91da4012c638f15b41ac859ae02abfd5", element="919ed3ca-78a6-4f8f-831a-bb24b19be3ac")>,
 <selenium.webdriver.remote.webelement.WebElement (session="91da4012c638f15b41ac859ae02abfd5", element="9c97c93f-e667-4a74-b593-088d469f3d5d")>]

In [140]:
search1=search[0]
search1

search1.send_keys("Data science")

In [142]:
search_btn=driver.find_element_by_xpath('//button[@id="qsbFormBtn"]')

In [143]:
search_btn.click()

In [145]:
Name = []
for i in driver.find_elements_by_xpath('//p[@class="highlightable"]/a/span'):
    Name.append(i.text)

Name

['Aakash Harit',
 'shravan Kumar Gaddam',
 'MARSIAN Technologies LLP',
 'Anik Agrawal',
 'Narasimha',
 'subhas patel',
 'Abhishek - Only Analytics Hiring - India and',
 'Institute for Financial Management and Resear',
 'Balu Ramesh',
 'Asif Lucknowi',
 'InstaFinancials',
 'Priyanka Akiri',
 'Kalpana Dumpala',
 'Mubarak',
 'Kushal Rastogi',
 'Ruchi Dhote',
 'Mahesh Babu Channa',
 'Kapil Devang',
 'Manisha Yadav',
 'Riya Rajesh',
 'Rashmi Bhattacharjee',
 'Faizan Kareem',
 'Rithika dadwal',
 'Sandhya Khandagale',
 'Shaun Rao',
 'Azahar Shaikh',
 'Manas',
 'kumar',
 'Sunil Vedula',
 'Rajat Kumar',
 'Priya Khare',
 'Dhruv Dev Dubey',
 'Jayanth N',
 'SREEDHAR',
 'Ravi Dubey',
 'Radha Manivasagam',
 'Prateek Kumar',
 'Amit Sharma',
 'Kanan',
 'Shashikant Chaudhary',
 'Brad',
 'Rutuja Pawar',
 'Madhusudhan Sridhar',
 'Ankit Sinha',
 'Gaurav Chouhan',
 'Rashi Kacker',
 'Ashwini',
 'Balaji Kolli',
 'Rajani Nagaraj',
 'ROHIT Kumar']

In [146]:
Designation = []
for j in driver.find_elements_by_xpath('//p[@class="highlightable"]/span[1]'):
    Designation.append(j.text)

Designation

['HR Manager',
 'Company Recruiter',
 'Company HR',
 'Company Recruiter',
 'Company Recruiter',
 'Founder CEO',
 'Recruitment Lead Consultant',
 'Programme Manager',
 'HR Administrator',
 'Director',
 'Human Resource',
 'HR Manager',
 'Executive Hiring',
 'Company HR',
 'Company HR',
 'Senior Executive Talent Acquisition',
 'HR Team Lead',
 'HR Manager',
 'HR Executive',
 'Manager Talent Acquisition',
 'HR Head',
 'HR MANAGER',
 'HR Recruiter',
 'HR Recruiter',
 'Manager Human Resources',
 'Company Recruiter',
 'Lead Talent acquisition',
 'Proprietor',
 'CEO',
 'Founder CEO',
 'Senior Manager',
 'Company Recruitment Head',
 'Project Manager',
 'Recruitment Consultant',
 'Recruitment Manager',
 'HR Executive',
 'Head',
 'Consultant',
 'senior technology instructor',
 'HR Recruiter/HR Excutive',
 'Manager, Technical Recruiting',
 'Technical Recruiter',
 'Erp Implementer',
 'Head Analytics',
 'Chief Technical Officer',
 'Sr Product Manager',
 'Director Global Delivery',
 'Co Founder',
 'HR Manager',
 'Architect']

In [147]:
Company = []
for k in driver.find_elements_by_xpath('//p[@class="highlightable"]/a[2]'):
    Company.append(k.text)

Company

['Data Science Network',
 'Shore Infotech India Pvt. Ltd',
 'MARSIAN Technologies LLP',
 'Enerlytics Software Solutions Pvt Ltd',
 'Step Next Private Limited',
 'LibraryXProject',
 'Apidel Technologies Division of Transpower',
 'IFMR',
 'Techvantage Systems Pvt Ltd',
 'Weupskill- Live Wire India',
 'CBL Data Science Private Limited',
 'Infinitive Software Solutions Pvt.Ltd.',
 'Innominds Software',
 'MoneyTap',
 'QuantMagnum Technologies Pvt. Ltd.',
 'Bristlecone India Ltd',
 'SocialPrachar.com',
 'BISP Solutions',
 'Easi Tax',
 'Novelworx Digital Solutions',
 'AXESTRACK SOFTWARE SOLUTIONS PRIVATE...',
 'FirstTech Consaltants Pvt.Ltd',
 'Affine Analytics',
 'Compumatrice Multimedia Pvt Ltd',
 'Exela Technologies',
 'NEAL ANALYTICS SERVICES PVT LTD',
 'Autumn Leaf Consulting Services Private...',
 'trainin',
 'Nanoprecise Sci Corp',
 'R.S Consultancy &amp; Services',
 'Independent Consultant',
 'Confidential',
 'Dollarbird Information Services Pvt, Ltd',
 'JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED',
 'HyrEzy Talent Solutions LLP',
 'Techcovery',
 'Trisect',
 'ASCO consulting',
 'NY INST',
 '3D India Staffing Research &amp; Consulting...',
 'O.C. Tanner',
 'Demand Matrix',
 'MADHUSUDHAN SRIDHAR',
 'Suntech Global',
 'Strategic Consulting Lab',
 'Impel Labs Pvt. Ltd.',
 'MRP Advisers',
 'Saras Solutions India Pvt Ltd',
 'WildJasmine',
 'LNT Private Limited']

In [148]:
Skills= []
for m in driver.find_elements_by_xpath('//div[@class="hireSec highlightable"]'):
    Skills.append(m.text)

Skills

['Classic ASP Developer, Internet Marketing Professional, Data Science SME, Content Writers, SEO Professional, Revenue Professional',
 '.Net, Java, Data Science, Linux Administration, Sql Server Development, Winforms, Wcf Services, Wpf, Telecom Engineering, Technical Management, Software',
 'Data Science, Artificial Intelligence, Machine Learning, Business Analytics',
 'Mean Stack, javascript, angularjs, mongodb, Web Services, rest, express, Node.js, Big Data, iot, Data Science, Cloud Computing, saas, Aws',
 'Data Modeling, Data Wrangling, seaborn, eda, python, r, Data Science, ai, Machine Learning, Deep Learning, Neural Networks',
 'Hadoop, Spark, Digital Strategy, Data Architecture, Command Center, Cdp, Dmp, Kafka, Data Science, Data Analysis, Big Data Analytics, Real Time Analysis, SQL',
 'Analytics, Business Intelligence, Business Analytics, Predictive Modeling, Predictive Analytics, Data Science, Data Analysis, Data Analytics, Big Data, Big',
 'Data Science',
 'Machine Learning, algorithms, Go Getter, Computer Science, spark, Big Data, hdfs, sql, cassandra, hadoop, python, scala, java, Data Science, Front End',
 'Technical Training, Software Development, Presentation Skills, B.tech, M.tech, B.e., mca, msc, Computer Science, freshers, jobs in indore, Data Science, itil',
 'Software Development, It Sales, Account Management, Data Analysis, Customer Service, Sr, Software Engineering, Mvc, Ajax, Asp.net, Html, C#, Javascript',
 'Oracle Dba, Data Science, Data Warehousing, ETL, Jupyter, Numpy, Data Transformation, Snowflake, Teradata, Python, Data Manipulation, Relational Databases',
 'Qa, Ui/ux, Java Developer, Java Architect, C++/qt, Php, Lamp, Api, J2ee, Java, Soa, Esb, Middleware, Bigdata Achitect, Hadoop Architect, Deep',
 'Business Intelligence, Data Warehousing, Data Science, Business Analytics, Customer Support, Business Reporting, Bi',
 'Office Administration, Hr Administration, telecalling, client relationship management, Client Acquisition, Sales, Reception, HR, Recruitment, Onboarding, Human',
 'Qlikview, Qlik Sense, Microsoft Azure, Power Bi, Data Science, Machine Learning',
 'Social Media, digital media maketing, seo, smm, smo, sem, Content Wirting, social media marketing, social media manager, digital media marketing manager',
 'Big Data, Hadoop, Data Analytics, Data Science',
 'Telecalling, Client Interaction, Marketing, Research, Web Development, Social Media Marketing, Data Entry Operation, Excel, Ms Office, Invoicing',
 'Data Science',
 'Corporate Sales, Software Development, Software Sales, Marketing, Creative Designing, Corporate Planning, Senior Management, Crm, Client Relationship',
 'Data Analytics, Data Science, Machine Learning, Deep Learning, Nlp, Data Mining, Python, R, Database Administration, Text Mining',
 'Data Science, Machine Learning, Python, R, Deep Learning, Big Data, Hadoop',
 'Big Data, Data Science, Artificial Intelligence, Hadoop, Ui Development, Php, Freelancing, .Net, Software Testing, Sap, Leadership Hiring',
 'Java, Net, Angularjs, Hr, Infrastructure, Management, Project Management, Business Analysis, Data Science, Information Technology, Technology',
 'Data Science, Artificial Intelligence, Machine Learning, Data Analytics',
 'Software Architecture, Vp Engineering, Product Management, analytics, Data Science, Node.js, Principal Engineer, Big Data, python, angularjs, React.js',
 'Data Science, Hadoop, Rpas, Devops, Python, Aws, Teaching, Big Data',
 'Signal Processing, Machine Learning, Neural Networks, Data Science, Predictive Analytics, Time Series Analysis, Data Visualization, Technical Leadership, Data',
 'Web Technologies, Project Management, Software Architecture, Data Science, Object Oriented Programming, Computer Science, Electrical Engineering, Architecture',
 'Data Science, Artificial Intelligence, analytics, Business Intelligence, python, tableau, Power Bi, qlikview, sql, Data Warehousing, Data Visualization',
 'Server Administartion, Verilog, Vhdl, Digital Marketing, Market Research, Property Research, Legal, It And Non It Recruitment, Logistics, Supply Chain, Bfsi',
 'Data Analytics, Managed Services, Team Leading, python, Machine Learning, Google Analytics, Dmp, Aws, Campaign Analytics, Digital Campaigns, Audience',
 'Data Science, Machine Learning, Big Data Analytics, Spark, Python, R, Networking, Network Engineering, Placement, Training, Sql, Marketing, Mainframes, All',
 'Walmart Interra Skeps Expressstores indifi whitehatJr Practo Zylo Doctalk Medtrail',
 'Python, Artificial Intelligence, Machine Learning, Data Science',
 'Java, Python, Angularjs, Software Testing, Machine Learning, Data Science, Javascript, Django, React.js, Node.js, Augmented Reality, Virtual Reality, Advanced',
 'Machine Learning, Artificial Intelligence, Data Science, Software Engineering, Software Development, Graduate Engineer Trainee, Fresher, Data Analytics, Java',
 'C, C++, Artificial Intelligence, Python, Php, Web Development, Matlab, Data Science, Augmented Reality, C C++',
 'Relationship Management, Retail Sales, Private Banking, Mutual Funds, NISM, Equity, Finance, Financial Products, Financial Services, Verbal, Written',
 'Data Science, Software Engineering',
 'Data Science, Big Data Analytics, Digital Marketing, Content Writing, Ui Development, Database Development, Qa Automation, Python, Project Management',
 'Data Science, Recruitment, Salary',
 'B.Tech, Tableau, Statistics, R, Analytics, Time Series, Data Science, Business Solutions, SQL, Technical Skills, SSAS, SQL Server, Analysis Services, Qlikview',
 'Software Development, Business Intelligence, Big Data Analytics, Database Administration, Data Science, Microsoft Azure, Spark, Cassandra, Object Oriented',
 'Data Science, Node.js, Angularjs',
 'Data Science, Media Marketing, Resource Planning, Managed Services, Display Advertising, Machine Learning, Python, Etl, Sql',
 'Data Analysis, Learning, Data Science, Computer Science, Communication Skills',
 'Java, Hadoop, R, Machine Learning, Spark, Flume, Hdfs, Data Mining, Sas, Big, Data Science, Cloudera, Impala, Bigdata',
 'Software Development, Core Java, Unit Testing, Customer Experience, Problem Solving, Communication Skills, Mysql, Data Science, Sales Management, Analytics']

In [150]:
Location= []
try:
    for n in driver.find_elements_by_xpath('//p[@class="highlightable"]/span[2]'):
        Location.append(n.text)
except NoSuchElementException:
    Location.append("-")
    
Location

['Delhi',
 'Hyderabad / Secunderabad',
 'Pune',
 'Ahmedabad',
 'Hyderabad / Secunderabad',
 'UK - (london)',
 'Vadodara / Baroda',
 'Chennai',
 'Trivandrum',
 'Indore',
 'Bengaluru / Bangalore',
 'Hyderabad',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Pune',
 'Hyderabad / Secunderabad',
 'Bhopal',
 'Navi Mumbai',
 'Cochin',
 'Delhi',
 'Hyderabad / Secunderabad',
 'Pune',
 'Pune',
 'Pune',
 'Pune',
 'Bengaluru / Bangalore',
 'Bengaluru / Bangalore',
 'Delhi',
 'Bengaluru / Bangalore',
 'Bengaluru / Bangalore',
 'Mysoru / Mysore',
 'Hyderabad / Secunderabad',
 'Ghaziabad',
 'Bengaluru / Bangalore',
 'Noida',
 'New Delhi',
 'Chennai',
 'Aligarh',
 'Salt Lake City',
 'Pune',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Indore',
 'Bengaluru / Bangalore',
 'MYSORE',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai']

In [152]:
df = pd.DataFrame({})
df[" Name"] = Name[:10]
df[" Designation"] = Designation[:10]
df["Company"] =Company[:10]
df["Skills"] = Skills[:10]
df["Location"] = Location[:10]
df

,Name,Designation,Company,Skills,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,Narasimha,Company Recruiter,Step Next Private Limited,"Data Modeling, Data Wrangling, seaborn, eda, p...",Hyderabad / Secunderabad
5,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
6,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
7,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
8,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
9,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore

In [153]:
driver.close()

Q8.Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [154]:
driver=webdriver.Chrome("chromedriver.exe")
url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare"
driver.get(url)

In [155]:
driver.maximize_window()

In [156]:
Book_name = []
for i in driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[2]'):
    Book_name.append(i.text)

Book_name

['Da Vinci Code,The',
 'Harry Potter and the Deathly Hallows',
 "Harry Potter and the Philosopher's Stone",
 'Harry Potter and the Order of the Phoenix',
 'Fifty Shades of Grey',
 'Harry Potter and the Goblet of Fire',
 'Harry Potter and the Chamber of Secrets',
 'Harry Potter and the Prisoner of Azkaban',
 'Angels and Demons',
 "Harry Potter and the Half-blood Prince:Children's Edition",
 'Fifty Shades Darker',
 'Twilight',
 'Girl with the Dragon Tattoo,The:Millennium Trilogy',
 'Fifty Shades Freed',
 'Lost Symbol,The',
 'New Moon',
 'Deception Point',
 'Eclipse',
 'Lovely Bones,The',
 'Curious Incident of the Dog in the Night-time,The',
 'Digital Fortress',
 'Short History of Nearly Everything,A',
 'Girl Who Played with Fire,The:Millennium Trilogy',
 'Breaking Dawn',
 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar',
 'Gruffalo,The',
 "Jamie's 30-Minute Meals",
 'Kite Runner,The',
 'One Day',
 'Thousand Splendid Suns,A',
 "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy",
 "Time Traveler's Wife,The",
 'Atonement',
 "Bridget Jones's Diary:A Novel",
 'World According to Clarkson,The',
 "Captain Corelli's Mandolin",
 'Sound of Laughter,The',
 'Life of Pi',
 'Billy Connolly',
 'Child Called It,A',
 "Gruffalo's Child,The",
 "Angela's Ashes:A Memoir of a Childhood",
 'Birdsong',
 'Northern Lights:His Dark Materials S.',
 'Labyrinth',
 'Harry Potter and the Half-blood Prince',
 'Help,The',
 'Man and Boy',
 'Memoirs of a Geisha',
 "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.",
 'Island,The',
 'PS, I Love You',
 'You are What You Eat:The Plan That Will Change Your Life',
 'Shadow of the Wind,The',
 'Tales of Beedle the Bard,The',
 'Broker,The',
 "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P",
 'Subtle Knife,The:His Dark Materials S.',
 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation',
 "Delia's How to Cook:(Bk.1)",
 'Chocolat',
 'Boy in the Striped Pyjamas,The',
 "My Sister's Keeper",
 'Amber Spyglass,The:His Dark Materials S.',
 'To Kill a Mockingbird',
 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin',
 'Dear Fatty',
 'Short History of Tractors in Ukrainian,A',
 'Hannibal',
 'Lord of the Rings,The',
 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio',
 'Interpretation of Murder,The',
 'Sharon Osbourne Extreme:My Autobiography',
 'Alchemist,The:A Fable About Following Your Dream',
 "At My Mother's Knee ...:and Other Low Joints",
 'Notes from a Small Island',
 'Return of the Naked Chef,The',
 'Bridget Jones: The Edge of Reason',
 "Jamie's Italy",
 'I Can Make You Thin',
 'Down Under',
 'Summons,The',
 'Small Island',
 'Nigella Express',
 'Brick Lane',
 "Memory Keeper's Daughter,The",
 'Room on the Broom',
 'About a Boy',
 'My Booky Wook',
 'God Delusion,The',
 '"Beano" Annual,The',
 'White Teeth',
 'House at Riverton,The',
 'Book Thief,The',
 'Nights of Rain and Stars',
 'Ghost,The',
 'Happy Days with the Naked Chef',
 'Hunger Games,The:Hunger Games Trilogy',
 "Lost Boy,The:A Foster Child's Search for the Love of a Family",
 "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours"]

In [157]:
Author_name = []
for i in driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[3]'):
    Author_name.append(i.text)

Author_name

['Brown, Dan',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'James, E. L.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Brown, Dan',
 'Rowling, J.K.',
 'James, E. L.',
 'Meyer, Stephenie',
 'Larsson, Stieg',
 'James, E. L.',
 'Brown, Dan',
 'Meyer, Stephenie',
 'Brown, Dan',
 'Meyer, Stephenie',
 'Sebold, Alice',
 'Haddon, Mark',
 'Brown, Dan',
 'Bryson, Bill',
 'Larsson, Stieg',
 'Meyer, Stephenie',
 'Carle, Eric',
 'Donaldson, Julia',
 'Oliver, Jamie',
 'Hosseini, Khaled',
 'Nicholls, David',
 'Hosseini, Khaled',
 'Larsson, Stieg',
 'Niffenegger, Audrey',
 'McEwan, Ian',
 'Fielding, Helen',
 'Clarkson, Jeremy',
 'Bernieres, Louis de',
 'Kay, Peter',
 'Martel, Yann',
 'Stephenson, Pamela',
 'Pelzer, Dave',
 'Donaldson, Julia',
 'McCourt, Frank',
 'Faulks, Sebastian',
 'Pullman, Philip',
 'Mosse, Kate',
 'Rowling, J.K.',
 'Stockett, Kathryn',
 'Parsons, Tony',
 'Golden, Arthur',
 'McCall Smith, Alexander',
 'Hislop, Victoria',
 'Ahern, Cecelia',
 'McKeith, Gillian',
 'Zafon, Carlos Ruiz',
 'Rowling, J.K.',
 'Grisham, John',
 'Atkins, Robert C.',
 'Pullman, Philip',
 'Truss, Lynne',
 'Smith, Delia',
 'Harris, Joanne',
 'Boyne, John',
 'Picoult, Jodi',
 'Pullman, Philip',
 'Lee, Harper',
 'Gray, John',
 'French, Dawn',
 'Lewycka, Marina',
 'Harris, Thomas',
 'Tolkien, J. R. R.',
 'Moore, Michael',
 'Rubenfeld, Jed',
 'Osbourne, Sharon',
 'Coelho, Paulo',
 "O'Grady, Paul",
 'Bryson, Bill',
 'Oliver, Jamie',
 'Fielding, Helen',
 'Oliver, Jamie',
 'McKenna, Paul',
 'Bryson, Bill',
 'Grisham, John',
 'Levy, Andrea',
 'Lawson, Nigella',
 'Ali, Monica',
 'Edwards, Kim',
 'Donaldson, Julia',
 'Hornby, Nick',
 'Brand, Russell',
 'Dawkins, Richard',
 '0',
 'Smith, Zadie',
 'Morton, Kate',
 'Zusak, Markus',
 'Binchy, Maeve',
 'Harris, Robert',
 'Oliver, Jamie',
 'Collins, Suzanne',
 'Pelzer, Dave',
 'Oliver, Jamie']

In [158]:
Volume_sold = []
for i in driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[4]'):
    Volume_sold.append(i.text)

Volume_sold

['5,094,805',
 '4,475,152',
 '4,200,654',
 '4,179,479',
 '3,758,936',
 '3,583,215',
 '3,484,047',
 '3,377,906',
 '3,193,946',
 '2,950,264',
 '2,479,784',
 '2,315,405',
 '2,233,570',
 '2,193,928',
 '2,183,031',
 '2,152,737',
 '2,062,145',
 '2,052,876',
 '2,005,598',
 '1,979,552',
 '1,928,900',
 '1,852,919',
 '1,814,784',
 '1,787,118',
 '1,783,535',
 '1,781,269',
 '1,743,266',
 '1,629,119',
 '1,616,068',
 '1,583,992',
 '1,555,135',
 '1,546,886',
 '1,539,428',
 '1,508,205',
 '1,489,403',
 '1,352,318',
 '1,310,207',
 '1,310,176',
 '1,231,957',
 '1,217,712',
 '1,208,711',
 '1,204,058',
 '1,184,967',
 '1,181,503',
 '1,181,093',
 '1,153,181',
 '1,132,336',
 '1,130,802',
 '1,126,337',
 '1,115,549',
 '1,108,328',
 '1,107,379',
 '1,104,403',
 '1,092,349',
 '1,090,847',
 '1,087,262',
 '1,054,196',
 '1,037,160',
 '1,023,688',
 '1,015,956',
 '1,009,873',
 '1,004,414',
 '1,003,780',
 '1,002,314',
 '998,213',
 '992,846',
 '986,753',
 '986,115',
 '970,509',
 '967,466',
 '963,353',
 '962,515',
 '959,496',
 '956,114',
 '945,640',
 '931,312',
 '925,425',
 '924,695',
 '906,968',
 '905,086',
 '890,847',
 '869,671',
 '869,659',
 '862,602',
 '856,540',
 '845,858',
 '842,535',
 '828,215',
 '820,563',
 '816,907',
 '816,585',
 '815,586',
 '814,370',
 '809,641',
 '808,900',
 '807,311',
 '794,201',
 '792,187',
 '791,507',
 '791,095']

In [159]:
Publisher = []
for i in driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[5]'):
    Publisher.append(i.text)

Publisher

['Transworld',
 'Bloomsbury',
 'Bloomsbury',
 'Bloomsbury',
 'Random House',
 'Bloomsbury',
 'Bloomsbury',
 'Bloomsbury',
 'Transworld',
 'Bloomsbury',
 'Random House',
 'Little, Brown Book',
 'Quercus',
 'Random House',
 'Transworld',
 'Little, Brown Book',
 'Transworld',
 'Little, Brown Book',
 'Pan Macmillan',
 'Random House',
 'Transworld',
 'Transworld',
 'Quercus',
 'Little, Brown Book',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Bloomsbury',
 'Hodder & Stoughton',
 'Bloomsbury',
 'Quercus',
 'Random House',
 'Random House',
 'Pan Macmillan',
 'Penguin',
 'Random House',
 'Random House',
 'Canongate',
 'HarperCollins',
 'Orion',
 'Pan Macmillan',
 'HarperCollins',
 'Random House',
 'Scholastic Ltd.',
 'Orion',
 'Bloomsbury',
 'Penguin',
 'HarperCollins',
 'Random House',
 'Little, Brown Book',
 'Headline',
 'HarperCollins',
 'Penguin',
 'Orion',
 'Bloomsbury',
 'Random House',
 'Random House',
 'Scholastic Ltd.',
 'Profile Books Group',
 'Random House',
 'Transworld',
 'Random House Childrens Books G',
 'Hodder & Stoughton',
 'Scholastic Ltd.',
 'Random House',
 'HarperCollins',
 'Random House',
 'Penguin',
 'Random House',
 'HarperCollins',
 'Penguin',
 'Headline',
 'Little, Brown Book',
 'HarperCollins',
 'Transworld',
 'Transworld',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Transworld',
 'Transworld',
 'Random House',
 'Headline',
 'Random House',
 'Transworld',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Hodder & Stoughton',
 'Transworld',
 'D.C. Thomson',
 'Penguin',
 'Pan Macmillan',
 'Transworld',
 'Orion',
 'Random House',
 'Penguin',
 'Scholastic Ltd.',
 'Orion',
 'Penguin']

In [160]:
Genre = []
for i in driver.find_elements_by_xpath('//table[@class="in-article sortable"]/tbody/tr/td[6]'):
    Genre.append(i.text)
    
Genre

['Crime, Thriller & Adventure',
 "Children's Fiction",
 "Children's Fiction",
 "Children's Fiction",
 'Romance & Sagas',
 "Children's Fiction",
 "Children's Fiction",
 "Children's Fiction",
 'Crime, Thriller & Adventure',
 "Children's Fiction",
 'Romance & Sagas',
 'Young Adult Fiction',
 'Crime, Thriller & Adventure',
 'Romance & Sagas',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'Popular Science',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'Picture Books',
 'Picture Books',
 'Food & Drink: General',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Humour: Collections & General',
 'General & Literary Fiction',
 'Autobiography: General',
 'General & Literary Fiction',
 'Biography: The Arts',
 'Autobiography: General',
 'Picture Books',
 'Autobiography: General',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Science Fiction & Fantasy',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Fitness & Diet',
 'General & Literary Fiction',
 "Children's Fiction",
 'Crime, Thriller & Adventure',
 'Fitness & Diet',
 'Young Adult Fiction',
 'Usage & Writing Guides',
 'Food & Drink: General',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Popular Culture & Media: General Interest',
 'Autobiography: The Arts',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'Science Fiction & Fantasy',
 'Current Affairs & Issues',
 'Crime, Thriller & Adventure',
 'Autobiography: The Arts',
 'General & Literary Fiction',
 'Autobiography: The Arts',
 'Travel Writing',
 'Food & Drink: General',
 'General & Literary Fiction',
 'National & Regional Cuisine',
 'Fitness & Diet',
 'Travel Writing',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'Food & Drink: General',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Picture Books',
 'General & Literary Fiction',
 'Autobiography: The Arts',
 'Popular Science',
 "Children's Annuals",
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Food & Drink: General',
 'Young Adult Fiction',
 'Biography: General',
 'Food & Drink: General']

In [161]:
df = pd.DataFrame({})
df[" Book_name"] = Book_name
df[" Author_name"] = Author_name
df[" Volume_sold"] = Volume_sold
df["Publisher"] = Publisher
df["Genre"] = Genre
df

,Book_name,Author_name,Volume_sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

Q9.Scrape the details most watched tv series of all time from imdb.com.
 Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Rating
F) VOTES

In [162]:
driver = webdriver.Chrome('chromedriver.exe')
url = "https://www.imdb.com/list/ls095964455/"
driver.get(url)
driver.maximize_window()

In [163]:
name=[]
try:
    for i in driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a"):
        name.append(i.text)
except NoSuchElementException as e:
    print("-")
name

['Game of Thrones',
 'Stranger Things',
 'The Walking Dead',
 '13 Reasons Why',
 'The 100',
 'Orange Is the New Black',
 'Riverdale',
 "Grey's Anatomy",
 'The Flash',
 'Arrow',
 'Money Heist',
 'The Big Bang Theory',
 'Black Mirror',
 'Sherlock',
 'Vikings',
 'Pretty Little Liars',
 'The Vampire Diaries',
 'American Horror Story',
 'Breaking Bad',
 'Lucifer',
 'Supernatural',
 'Prison Break',
 'How to Get Away with Murder',
 'Teen Wolf',
 'The Simpsons',
 'Once Upon a Time',
 'Narcos',
 'Daredevil',
 'Friends',
 'How I Met Your Mother',
 'Suits',
 'Mr. Robot',
 'The Originals',
 'Supergirl',
 'Gossip Girl',
 'Sense8',
 'Gotham',
 'Westworld',
 'Jessica Jones',
 'Modern Family',
 'Rick and Morty',
 'Shadowhunters',
 'The End of the F***ing World',
 'House of Cards',
 'Dark',
 'Elite',
 'Sex Education',
 'Shameless',
 'New Girl',
 'Agents of S.H.I.E.L.D.',
 'You',
 'Dexter',
 'Fear the Walking Dead',
 'Family Guy',
 'The Blacklist',
 'Lost',
 'Peaky Blinders',
 'House',
 'Quantico',
 'Orphan Black',
 'Homeland',
 'Blindspot',
 "DC's Legends of Tomorrow",
 "The Handmaid's Tale",
 'Chilling Adventures of Sabrina',
 'The Good Doctor',
 'Jane the Virgin',
 'Glee',
 'South Park',
 'Brooklyn Nine-Nine',
 'Under the Dome',
 'The Umbrella Academy',
 'True Detective',
 'The OA',
 'Desperate Housewives',
 'Better Call Saul',
 'Bates Motel',
 'The Punisher',
 'Atypical',
 'Dynasty',
 'This Is Us',
 'The Good Place',
 'Iron Fist',
 'The Rain',
 'Mindhunter',
 'Revenge',
 'Luke Cage',
 'Scandal',
 'The Defenders',
 'Big Little Lies',
 'Insatiable',
 'The Mentalist',
 'The Crown',
 'Chernobyl',
 'iZombie',
 'Reign',
 'A Series of Unfortunate Events',
 'Criminal Minds',
 'Scream: The TV Series',
 'The Haunting of Hill House']

In [164]:
year=[]
try: 
    for i in driver.find_elements_by_xpath("//span[@class='lister-item-year text-muted unbold']"):
        year.append(i.text)
except NoSuchElementException as e:
    print("-")

In [165]:
year

['(2011–2019)',
 '(2016– )',
 '(2010–2022)',
 '(2017–2020)',
 '(2014–2020)',
 '(2013–2019)',
 '(2017– )',
 '(2005– )',
 '(2014– )',
 '(2012–2020)',
 '(2017–2021)',
 '(2007–2019)',
 '(2011– )',
 '(2010–2017)',
 '(2013–2020)',
 '(2010–2017)',
 '(2009–2017)',
 '(2011– )',
 '(2008–2013)',
 '(2016–2021)',
 '(2005–2020)',
 '(2005–2017)',
 '(2014–2020)',
 '(2011–2017)',
 '(1989– )',
 '(2011–2018)',
 '(2015–2017)',
 '(2015–2018)',
 '(1994–2004)',
 '(2005–2014)',
 '(2011–2019)',
 '(2015–2019)',
 '(2013–2018)',
 '(2015–2021)',
 '(2007–2012)',
 '(2015–2018)',
 '(2014–2019)',
 '(2016– )',
 '(2015–2019)',
 '(2009–2020)',
 '(2013– )',
 '(2016–2019)',
 '(2017–2019)',
 '(2013–2018)',
 '(2017–2020)',
 '(2018– )',
 '(2019– )',
 '(2011–2021)',
 '(2011–2018)',
 '(2013–2020)',
 '(2018– )',
 '(2006–2013)',
 '(2015– )',
 '(1999– )',
 '(2013– )',
 '(2004–2010)',
 '(2014– )',
 '(2004–2012)',
 '(2015–2018)',
 '(2013–2017)',
 '(2011–2020)',
 '(2015–2020)',
 '(2016– )',
 '(2017– )',
 '(2018–2020)',
 '(2017– )',
 '(2014–2019)',
 '(2009–2015)',
 '(1997– )',
 '(2013–2021)',
 '(2013–2015)',
 '(2019– )',
 '(2014–2019)',
 '(2016–2019)',
 '(2004–2012)',
 '(2015–2022)',
 '(2013–2017)',
 '(2017–2019)',
 '(2017–2021)',
 '(2017– )',
 '(2016–2022)',
 '(2016–2020)',
 '(2017–2018)',
 '(2018–2020)',
 '(2017–2019)',
 '(2011–2015)',
 '(2016–2018)',
 '(2012–2018)',
 '(2017)',
 '(2017–2019)',
 '(2018–2019)',
 '(2008–2015)',
 '(2016– )',
 '(2019)',
 '(2015–2019)',
 '(2013–2017)',
 '(2017–2019)',
 '(2005–2020)',
 '(2015–2019)',
 '(2018)']

In [166]:
genre=[]

try: 
    for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']/p/span[5]"):
        genre.append(i.text)
except NoSuchElementException as e:
    print("-")
    
genre

['Action, Adventure, Drama',
 'Drama, Fantasy, Horror',
 'Drama, Horror, Thriller',
 'Drama, Mystery, Thriller',
 'Drama, Mystery, Sci-Fi',
 'Comedy, Crime, Drama',
 'Crime, Drama, Mystery',
 'Drama, Romance',
 'Action, Adventure, Drama',
 'Action, Adventure, Crime',
 'Action, Crime, Drama',
 'Comedy, Romance',
 'Drama, Sci-Fi, Thriller',
 'Crime, Drama, Mystery',
 'Action, Adventure, Drama',
 'Drama, Mystery, Romance',
 'Drama, Fantasy, Horror',
 'Drama, Horror, Thriller',
 'Crime, Drama, Thriller',
 'Crime, Drama, Fantasy',
 'Drama, Fantasy, Horror',
 'Action, Crime, Drama',
 'Crime, Drama, Mystery',
 'Action, Drama, Fantasy',
 'Animation, Comedy',
 'Adventure, Fantasy, Romance',
 'Biography, Crime, Drama',
 'Action, Crime, Drama',
 'Comedy, Romance',
 'Comedy, Romance',
 'Comedy, Drama',
 'Crime, Drama, Thriller',
 'Drama, Fantasy, Horror',
 'Action, Adventure, Drama',
 'Drama, Romance',
 'Drama, Mystery, Sci-Fi',
 'Action, Crime, Drama',
 'Drama, Mystery, Sci-Fi',
 'Action, Crime, Drama',
 'Comedy, Drama, Romance',
 'Animation, Adventure, Comedy',
 'Action, Drama, Fantasy',
 'Adventure, Comedy, Crime',
 'Drama',
 'Crime, Drama, Mystery',
 'Crime, Drama, Thriller',
 'Comedy, Drama',
 'Comedy, Drama',
 'Comedy',
 'Action, Adventure, Drama',
 'Crime, Drama, Romance',
 'Crime, Drama, Mystery',
 'Drama, Horror, Sci-Fi',
 'Animation, Comedy',
 'Crime, Drama, Mystery',
 'Adventure, Drama, Fantasy',
 'Crime, Drama',
 'Drama, Mystery',
 'Crime, Drama, Mystery',
 'Action, Drama, Sci-Fi',
 'Crime, Drama, Mystery',
 'Action, Crime, Drama',
 'Action, Adventure, Drama',
 'Drama, Sci-Fi, Thriller',
 'Drama, Fantasy, Horror',
 'Drama',
 'Comedy',
 'Comedy, Drama, Music',
 'Animation, Comedy',
 'Comedy, Crime',
 'Drama, Mystery, Sci-Fi',
 'Action, Adventure, Comedy',
 'Crime, Drama, Mystery',
 'Drama, Fantasy, Mystery',
 'Comedy, Drama, Mystery',
 'Crime, Drama',
 'Drama, Horror, Mystery',
 'Action, Crime, Drama',
 'Comedy, Drama',
 'Drama',
 'Comedy, Drama, Romance',
 'Comedy, Drama, Fantasy',
 'Action, Adventure, Crime',
 'Drama, Sci-Fi, Thriller',
 'Crime, Drama, Thriller',
 'Drama, Mystery, Thriller',
 'Action, Crime, Drama',
 'Drama, Thriller',
 'Action, Adventure, Crime',
 'Crime, Drama, Mystery',
 'Comedy, Drama, Thriller',
 'Crime, Drama, Mystery',
 'Biography, Drama, History',
 'Drama, History, Thriller',
 'Comedy, Crime, Drama',
 'Drama, Fantasy',
 'Adventure, Comedy, Drama',
 'Crime, Drama, Mystery',
 'Comedy, Crime, Drama',
 'Drama, Horror, Mystery']

In [167]:
runtime=[]
try:
    for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']/p/span[3]"):
        runtime.append(i.text)
except NoSuchElementException as e:
    print("-") 
    
runtime

['57 min',
 '51 min',
 '44 min',
 '60 min',
 '43 min',
 '59 min',
 '45 min',
 '41 min',
 '43 min',
 '42 min',
 '70 min',
 '22 min',
 '60 min',
 '88 min',
 '44 min',
 '44 min',
 '43 min',
 '60 min',
 '49 min',
 '42 min',
 '44 min',
 '44 min',
 '43 min',
 '41 min',
 '22 min',
 '60 min',
 '49 min',
 '54 min',
 '22 min',
 '22 min',
 '44 min',
 '49 min',
 '45 min',
 '43 min',
 '42 min',
 '60 min',
 '42 min',
 '62 min',
 '56 min',
 '22 min',
 '23 min',
 '42 min',
 '25 min',
 '51 min',
 '60 min',
 '60 min',
 '45 min',
 '46 min',
 '22 min',
 '45 min',
 '45 min',
 '53 min',
 '44 min',
 '22 min',
 '43 min',
 '44 min',
 '60 min',
 '44 min',
 '42 min',
 '44 min',
 '55 min',
 '42 min',
 '42 min',
 '60 min',
 '60 min',
 '41 min',
 '60 min',
 '44 min',
 '22 min',
 '22 min',
 '43 min',
 '60 min',
 '55 min',
 '60 min',
 '45 min',
 '46 min',
 '45 min',
 '53 min',
 '30 min',
 '42 min',
 '45 min',
 '22 min',
 '55 min',
 '45 min',
 '60 min',
 '44 min',
 '55 min',
 '43 min',
 '50 min',
 '60 min',
 '45 min',
 '43 min',
 '58 min',
 '330 min',
 '42 min',
 '42 min',
 '50 min',
 '42 min',
 '45 min',
 '572 min']

In [168]:
rating=[]
try: 
    for i in driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]"):
        rating.append(i.text)
except NoSuchElementException as e:
    print("-")
    
rating

['9.2',
 '8.7',
 '8.2',
 '7.5',
 '7.6',
 '8',
 '6.7',
 '7.5',
 '7.6',
 '7.5',
 '8.2',
 '8.1',
 '8.8',
 '9.1',
 '8.5',
 '7.4',
 '7.7',
 '8',
 '9.4',
 '8.1',
 '8.4',
 '8.3',
 '8.1',
 '7.6',
 '8.6',
 '7.7',
 '8.8',
 '8.6',
 '8.8',
 '8.3',
 '8.4',
 '8.5',
 '8.2',
 '6.2',
 '7.4',
 '8.3',
 '7.8',
 '8.6',
 '7.9',
 '8.4',
 '9.2',
 '6.6',
 '8.1',
 '8.7',
 '8.8',
 '7.5',
 '8.3',
 '8.5',
 '7.7',
 '7.5',
 '7.7',
 '8.6',
 '6.9',
 '8.1',
 '8',
 '8.3',
 '8.8',
 '8.7',
 '6.7',
 '8.3',
 '8.3',
 '7.4',
 '6.8',
 '8.4',
 '7.5',
 '8.1',
 '7.8',
 '6.7',
 '8.7',
 '8.4',
 '6.6',
 '8',
 '8.9',
 '7.8',
 '7.5',
 '8.8',
 '8.1',
 '8.5',
 '8.3',
 '7.3',
 '8.6',
 '8.2',
 '6.4',
 '6.3',
 '8.6',
 '7.8',
 '7.3',
 '7.7',
 '7.3',
 '8.5',
 '6.5',
 '8.1',
 '8.6',
 '9.4',
 '7.8',
 '7.5',
 '7.8',
 '8.1',
 '7.1',
 '8.6']

In [169]:
vote=[]
try: 
    for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']/p[4]/span[2]"):
        vote.append(i.text)
except NoSuchElementException as e:
    print("-")
    
vote

['1,884,117',
 '917,315',
 '905,385',
 '271,133',
 '231,483',
 '287,499',
 '130,318',
 '274,506',
 '325,420',
 '418,054',
 '392,055',
 '753,265',
 '481,400',
 '853,038',
 '472,224',
 '157,866',
 '298,207',
 '295,708',
 '1,591,534',
 '287,915',
 '410,864',
 '499,524',
 '139,302',
 '136,031',
 '381,356',
 '214,793',
 '383,116',
 '381,727',
 '903,039',
 '634,539',
 '380,190',
 '353,739',
 '125,053',
 '117,511',
 '162,443',
 '146,038',
 '218,822',
 '452,780',
 '200,778',
 '387,598',
 '436,258',
 '57,521',
 '163,709',
 '481,578',
 '324,528',
 '63,619',
 '217,760',
 '217,066',
 '204,808',
 '207,592',
 '168,360',
 '677,831',
 '120,231',
 '316,517',
 '219,116',
 '520,007',
 '414,873',
 '431,948',
 '58,874',
 '105,796',
 '326,024',
 '69,791',
 '97,863',
 '204,129',
 '84,733',
 '78,351',
 '43,405',
 '141,677',
 '344,908',
 '266,402',
 '103,544',
 '182,503',
 '523,935',
 '96,850',
 '121,586',
 '359,169',
 '102,009',
 '200,472',
 '77,064',
 '17,532',
 '119,079',
 '132,924',
 '120,987',
 '33,755',
 '244,182',
 '116,131',
 '121,921',
 '69,785',
 '96,451',
 '174,218',
 '25,090',
 '172,521',
 '175,818',
 '616,175',
 '63,433',
 '45,938',
 '56,816',
 '177,573',
 '36,960',
 '204,629']

In [171]:
df = pd.DataFrame({})
df[" Name"] = name
df["Year_span"] = year
df["Genre"] = genre
df["Run_time"] = runtime
df["Ratings"] = rating
df["Votes"] = vote

df

,Name,Year_span,Genre,Run_time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,884,117"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"917,315"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"905,385"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"271,133"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"231,483"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"45,938"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"56,816"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"177,573"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"36,960"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"204,629"

Q10.. Details of Datasets from UCI machine learning repositories.
 Url = https://archive.ics.uci.edu/
 You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year

In [172]:
driver = webdriver.Chrome('chromedriver.exe')
url = "https://archive.ics.uci.edu/"
driver.get(url)
driver.maximize_window()

In [173]:
respository=driver.find_element_by_xpath("//span[@class='normal']/b/a")
respository.click()

In [174]:
Name=[]
try:
    names=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
    for i in names:
        Name.append(i.text)
except NoSuchElementException:
    Name.append('-')
    
Name

['Abalone',
 'Adult',
 'Annealing',
 'Anonymous Microsoft Web Data',
 'Arrhythmia',
 'Artificial Characters',
 'Audiology (Original)',
 'Audiology (Standardized)',
 'Auto MPG',
 'Automobile',
 'Badges',
 'Balance Scale',
 'Balloons',
 'Breast Cancer',
 'Breast Cancer Wisconsin (Original)',
 'Breast Cancer Wisconsin (Prognostic)',
 'Breast Cancer Wisconsin (Diagnostic)',
 'Pittsburgh Bridges',
 'Car Evaluation',
 'Census Income',
 'Chess (King-Rook vs. King-Knight)',
 'Chess (King-Rook vs. King-Pawn)',
 'Chess (King-Rook vs. King)',
 'Chess (Domain Theories)',
 'Bach Chorales',
 'Connect-4',
 'Credit Approval',
 'Japanese Credit Screening',
 'Computer Hardware',
 'Contraceptive Method Choice',
 'Covertype',
 'Cylinder Bands',
 'Dermatology',
 'Diabetes',
 'DGP2 - The Second Data Generation Program',
 'Document Understanding',
 'EBL Domain Theories',
 'Echocardiogram',
 'Ecoli',
 'Flags',
 'Function Finding',
 'Glass Identification',
 "Haberman's Survival",
 'Hayes-Roth',
 'Heart Disease',
 'Hepatitis',
 'Horse Colic',
 'ICU',
 'Image Segmentation',
 'Internet Advertisements',
 'Ionosphere',
 'Iris',
 'ISOLET',
 'Kinship',
 'Labor Relations',
 'LED Display Domain',
 'Lenses',
 'Letter Recognition',
 'Liver Disorders',
 'Logic Theorist',
 'Lung Cancer',
 'Lymphography',
 'Mechanical Analysis',
 'Meta-data',
 'Mobile Robots',
 'Molecular Biology (Promoter Gene Sequences)',
 'Molecular Biology (Protein Secondary Structure)',
 'Molecular Biology (Splice-junction Gene Sequences)',
 "MONK's Problems",
 'Moral Reasoner',
 'Multiple Features',
 'Mushroom',
 'Musk (Version 1)',
 'Musk (Version 2)',
 'Nursery',
 'Othello Domain Theory',
 'Page Blocks Classification',
 'Optical Recognition of Handwritten Digits',
 'Pen-Based Recognition of Handwritten Digits',
 'Post-Operative Patient',
 'Primary Tumor',
 'Prodigy',
 'Qualitative Structure Activity Relationships',
 'Quadruped Mammals',
 'Servo',
 'Shuttle Landing Control',
 'Solar Flare',
 'Soybean (Large)',
 'Soybean (Small)',
 'Challenger USA Space Shuttle O-Ring',
 'Low Resolution Spectrometer',
 'Spambase',
 'SPECT Heart',
 'SPECTF Heart',
 'Sponge',
 'Statlog Project',
 'Student Loan Relational',
 'Teaching Assistant Evaluation',
 'Tic-Tac-Toe Endgame',
 'Thyroid Disease',
 'Trains',
 'University',
 'Congressional Voting Records',
 'Water Treatment Plant',
 'Waveform Database Generator (Version 1)',
 'Waveform Database Generator (Version 2)',
 'Wine',
 'Yeast',
 'Zoo',
 'Undocumented',
 'Twenty Newsgroups',
 'Australian Sign Language signs',
 'Australian Sign Language signs (High Quality)',
 'US Census Data (1990)',
 'Census-Income (KDD)',
 'Coil 1999 Competition Data',
 'Corel Image Features',
 'E. Coli Genes',
 'EEG Database',
 'El Nino',
 'Entree Chicago Recommendation Data',
 'CMU Face Images',
 'Insurance Company Benchmark (COIL 2000)',
 'Internet Usage Data',
 'IPUMS Census Database',
 'Japanese Vowels',
 'KDD Cup 1998 Data',
 'KDD Cup 1999 Data',
 'M. Tuberculosis Genes',
 'Movie',
 'MSNBC.com Anonymous Web Data',
 'NSF Research Award Abstracts 1990-2003',
 'Pioneer-1 Mobile Robot Data',
 'Pseudo Periodic Synthetic Time Series',
 'Reuters-21578 Text Categorization Collection',
 'Robot Execution Failures',
 'Synthetic Control Chart Time Series',
 'Syskill and Webert Web Page Ratings',
 'UNIX User Data',
 'Volcanoes on Venus - JARtool experiment',
 'Statlog (Australian Credit Approval)',
 'Statlog (German Credit Data)',
 'Statlog (Heart)',
 'Statlog (Landsat Satellite)',
 'Statlog (Image Segmentation)',
 'Statlog (Shuttle)',
 'Statlog (Vehicle Silhouettes)',
 'Connectionist Bench (Nettalk Corpus)',
 'Connectionist Bench (Sonar, Mines vs. Rocks)',
 'Connectionist Bench (Vowel Recognition - Deterding Data)',
 'Economic Sanctions',
 'Protein Data',
 'Cloud',
 'CalIt2 Building People Counts',
 'Dodgers Loop Sensor',
 'Poker Hand',
 'MAGIC Gamma Telescope',
 'UJI Pen Characters',
 'Mammographic Mass',
 'Forest Fires',
 'Reuters Transcribed Subset',
 'Bag of Words',
 'Concrete Compressive Strength',
 'Hill-Valley',
 'Arcene',
 'Dexter',
 'Dorothea',
 'Gisette',
 'Madelon',
 'Ozone Level Detection',
 'Abscisic Acid Signaling Network',
 'Parkinsons',
 'Character Trajectories',
 'Blood Transfusion Service Center',
 'UJI Pen Characters (Version 2)',
 'Semeion Handwritten Digit',
 'SECOM',
 'Plants',
 'Libras Movement',
 'Concrete Slump Test',
 'Communities and Crime',
 'Acute Inflammations',
 'Wine Quality',
 'URL Reputation',
 'p53 Mutants',
 'Parkinsons Telemonitoring',
 'Demospongiae',
 'Opinosis Opinion ⁄ Review',
 'Breast Tissue',
 'Cardiotocography',
 'Wall-Following Robot Navigation Data',
 'Spoken Arabic Digit',
 'Localization Data for Person Activity',
 'AutoUniv',
 'Steel Plates Faults',
 'MiniBooNE particle identification',
 'YearPredictionMSD',
 'PEMS-SF',
 'OpinRank Review Dataset',
 'Relative location of CT slices on axial axis',
 'Online Handwritten Assamese Characters Dataset',
 'PubChem Bioassay Data',
 'Record Linkage Comparison Patterns',
 'Communities and Crime Unnormalized',
 'Vertebral Column',
 'EMG Physical Action Data Set',
 'Vicon Physical Action Data Set',
 'Amazon Commerce reviews set',
 'Amazon Access Samples',
 'Reuter_50_50',
 'Farm Ads',
 'DBWorld e-mails',
 'KEGG Metabolic Relation Network (Directed)',
 'KEGG Metabolic Reaction Network (Undirected)',
 'Bank Marketing',
 'YouTube Comedy Slam Preference Data',
 'Gas Sensor Array Drift Dataset',
 'ILPD (Indian Liver Patient Dataset)',
 'OPPORTUNITY Activity Recognition',
 'Nomao',
 'SMS Spam Collection',
 'Skin Segmentation',
 'Planning Relax',
 'PAMAP2 Physical Activity Monitoring',
 'Restaurant & consumer data',
 'CNAE-9',
 'Individual household electric power consumption',
 'seeds',
 'Northix',
 'QtyT40I10D100K',
 'Legal Case Reports',
 'Human Activity Recognition Using Smartphones',
 'One-hundred plant species leaves data set',
 'Energy efficiency',
 'Yacht Hydrodynamics',
 'Fertility',
 'Daphnet Freezing of Gait',
 '3D Road Network (North Jutland, Denmark)',
 'ISTANBUL STOCK EXCHANGE',
 'Buzz in social media',
 'First-order theorem proving',
 'Wearable Computing: Classification of Body Postures and Movements (PUC-Rio)',
 'Gas sensor arrays in open sampling settings',
 'Climate Model Simulation Crashes',
 'MicroMass',
 'QSAR biodegradation',
 'BLOGGER',
 'Daily and Sports Activities',
 'User Knowledge Modeling',
 'Reuters RCV1 RCV2 Multilingual, Multiview Text Categorization Test collection',
 'NYSK',
 'Turkiye Student Evaluation',
 "ser Knowledge Modeling Data (Students' Knowledge Levels on DC Electrical Machines)",
 'EEG Eye State',
 'Physicochemical Properties of Protein Tertiary Structure',
 'seismic-bumps',
 'banknote authentication',
 'USPTO Algorithm Challenge, run by NASA-Harvard Tournament Lab and TopCoder Problem: Pat',
 'YouTube Multiview Video Games Dataset',
 'Gas Sensor Array Drift Dataset at Different Concentrations',
 'Activities of Daily Living (ADLs) Recognition Using Binary Sensors',
 'SkillCraft1 Master Table Dataset',
 'Weight Lifting Exercises monitored with Inertial Measurement Units',
 'SML2010',
 'Bike Sharing Dataset',
 'Predict keywords activities in a online social media',
 'Thoracic Surgery Data',
 'EMG dataset in Lower Limb',
 'SUSY',
 'HIGGS',
 'Qualitative_Bankruptcy',
 'LSVT Voice Rehabilitation',
 'Dataset for ADL Recognition with Wrist-worn Accelerometer',
 'Wilt',
 'User Identification From Walking Activity',
 'Activity Recognition from Single Chest-Mounted Accelerometer',
 'Leaf',
 'Dresses_Attribute_Sales',
 'Tamilnadu Electricity Board Hourly Readings',
 'Airfoil Self-Noise',
 'Wholesale customers',
 'Twitter Data set for Arabic Sentiment Analysis',
 'Combined Cycle Power Plant',
 'Urban Land Cover',
 'Diabetes 130-US hospitals for years 1999-2008',
 'Bach Choral Harmony',
 'StoneFlakes',
 'Tennis Major Tournament Match Statistics',
 'Parkinson Speech Dataset with Multiple Types of Sound Recordings',
 'Gesture Phase Segmentation',
 'Perfume Data',
 'BlogFeedback',
 'REALDISP Activity Recognition Dataset',
 'Newspaper and magazine images segmentation dataset',
 'AAAI 2014 Accepted Papers',
 'Gas sensor array under flow modulation',
 'Gas sensor array exposed to turbulent gas mixtures',
 'UJIIndoorLoc',
 'Sentence Classification',
 'Dow Jones Index',
 'sEMG for Basic Hand movements',
 'AAAI 2013 Accepted Papers',
 'Geographical Original of Music',
 'Condition Based Maintenance of Naval Propulsion Plants',
 'Grammatical Facial Expressions',
 'NoisyOffice',
 'MHEALTH Dataset',
 'Student Performance',
 'ElectricityLoadDiagrams20112014',
 'Gas sensor array under dynamic gas mixtures',
 'microblogPCU',
 'Firm-Teacher_Clave-Direction_Classification',
 'Dataset for Sensorless Drive Diagnosis',
 'TV News Channel Commercial Detection Dataset',
 'Phishing Websites',
 'Greenhouse Gas Observing Network',
 'Diabetic Retinopathy Debrecen Data Set',
 'HIV-1 protease cleavage',
 'Sentiment Labelled Sentences',
 'Online News Popularity',
 'Forest type mapping',
 'wiki4HE',
 'Online Video Characteristics and Transcoding Time Dataset',
 'Chronic_Kidney_Disease',
 'Machine Learning based ZZAlpha Ltd. Stock Recommendations 2012-2014',
 'Folio',
 'Taxi Service Trajectory - Prediction Challenge, ECML PKDD 2015',
 'Cuff-Less Blood Pressure Estimation',
 'Smartphone-Based Recognition of Human Activities and Postural Transitions',
 'Mice Protein Expression',
 'UJIIndoorLoc-Mag',
 'Heterogeneity Activity Recognition',
 'Educational Process Mining (EPM): A Learning Analytics Data Set',
 'HEPMASS',
 'Indoor User Movement Prediction from RSS data',
 'Open University Learning Analytics dataset',
 'default of credit card clients',
 'Mesothelioma’s disease data set',
 'Online Retail',
 'SIFT10M',
 'GPS Trajectories',
 'Detect Malacious Executable(AntiVirus)',
 'Occupancy Detection',
 'Improved Spiral Test Using Digitized Graphics Tablet for Monitoring Parkinson’s Disease',
 'News Aggregator',
 'Air Quality',
 'Twin gas sensor arrays',
 'Gas sensors for home activity monitoring',
 'Facebook Comment Volume Dataset',
 'Smartphone Dataset for Human Activity Recognition (HAR) in Ambient Assisted Living (AAL)',
 'Polish companies bankruptcy data',
 'Activity Recognition system based on Multisensor data fusion (AReM)',
 'Dota2 Games Results',
 'Facebook metrics',
 'UbiqLog (smartphone lifelogging)',
 'NIPS Conference Papers 1987-2015',
 'HTRU2',
 'Drug consumption (quantified)',
 'Appliances energy prediction',
 'Miskolc IIS Hybrid IPS',
 'KDC-4007 dataset Collection',
 'Geo-Magnetic field and WLAN dataset for indoor localisation from wristband and smartphone',
 'DrivFace',
 'Website Phishing',
 'YouTube Spam Collection',
 'Beijing PM2.5 Data',
 'Cargo 2000 Freight Tracking and Tracing',
 'Cervical cancer (Risk Factors)',
 'Quality Assessment of Digital Colposcopies',
 'KASANDR',
 'FMA: A Dataset For Music Analysis',
 'Air quality',
 'Epileptic Seizure Recognition',
 'Devanagari Handwritten Character Dataset',
 'Stock portfolio performance',
 'MoCap Hand Postures',
 'Early biomarkers of Parkinson�s disease based on natural connected speech',
 'Data for Software Engineering Teamwork Assessment in Education Setting',
 'PM2.5 Data of Five Chinese Cities',
 'Parkinson Disease Spiral Drawings Using Digitized Graphics Tablet',
 'Sales_Transactions_Dataset_Weekly',
 'Las Vegas Strip',
 'Eco-hotel',
 'MEU-Mobile KSD',
 'Crowdsourced Mapping',
 'gene expression cancer RNA-Seq',
 'Hybrid Indoor Positioning Dataset from WiFi RSSI, Bluetooth and magnetometer',
 'chestnut – LARVIC',
 'Burst Header Packet (BHP) flooding attack on Optical Burst Switching (OBS) Network',
 'Motion Capture Hand Postures',
 'Anuran Calls (MFCCs)',
 'TTC-3600: Benchmark dataset for Turkish text categorization',
 'Gastrointestinal Lesions in Regular Colonoscopy',
 'Daily Demand Forecasting Orders',
 'Paper Reviews',
 'extention of Z-Alizadeh sani dataset',
 'Z-Alizadeh Sani',
 'Dynamic Features of VirusShare Executables',
 'IDA2016Challenge',
 'DSRC Vehicle Communications',
 'Mturk User-Perceived Clusters over Images',
 'Character Font Images',
 'DeliciousMIL: A Data Set for Multi-Label Multi-Instance Learning with Instance Labels',
 'Autistic Spectrum Disorder Screening Data for Children',
 'Autistic Spectrum Disorder Screening Data for Adolescent',
 'APS Failure at Scania Trucks',
 'Wireless Indoor Localization',
 'HCC Survival',
 'CSM (Conventional and Social Media Movies) Dataset 2014 and 2015',
 'University of Tehran Question Dataset 2016 (UTQD.2016)',
 'Autism Screening Adult',
 'Activity recognition with healthy older people using a batteryless wearable sensor',
 'Immunotherapy Dataset',
 'Cryotherapy Dataset',
 'OCT data & Color Fundus Images of Left & Right Eyes',
 'Discrete Tone Image Dataset',
 'News Popularity in Multiple Social Media Platforms',
 'Ultrasonic flowmeter diagnostics',
 'ICMLA 2014 Accepted Papers Data Set',
 'BLE RSSI Dataset for Indoor localization and Navigation',
 'Container Crane Controller Data Set',
 'Residential Building Data Set',
 'Health News in Twitter',
 'chipseq',
 'SGEMM GPU kernel performance',
 'Repeat Consumption Matrices',
 'detection_of_IoT_botnet_attacks_N_BaIoT',
 'Absenteeism at work',
 'SCADI',
 'Condition monitoring of hydraulic systems',
 'Carbon Nanotubes',
 'Optical Interconnection Network',
 'Sports articles for objectivity analysis',
 'Breast Cancer Coimbra',
 'GNFUV Unmanned Surface Vehicles Sensor Data',
 'Dishonest Internet users Dataset',
 'Victorian Era Authorship Attribution',
 'Simulated Falls and Daily Living Activities Data Set',
 'Multimodal Damage Identification for Humanitarian Computing',
 'EEG Steady-State Visual Evoked Potential Signals',
 'Roman Urdu Data Set',
 'Avila',
 'PANDOR',
 'Drug Review Dataset (Druglib.com)',
 'Drug Review Dataset (Drugs.com)',
 'Physical Unclonable Functions',
 'Superconductivty Data',
 'WESAD (Wearable Stress and Affect Detection)',
 'GNFUV Unmanned Surface Vehicles Sensor Data Set 2',
 'Student Academics Performance',
 'Online Shoppers Purchasing Intention Dataset',
 'PMU-UD',
 "Parkinson's Disease Classification",
 'Electrical Grid Stability Simulated Data',
 'Caesarian Section Classification Dataset',
 'BAUM-1',
 'BAUM-2',
 'Audit Data',
 'BuddyMove Data Set',
 'Real estate valuation data set',
 'Early biomarkers of Parkinson’s disease based on natural connected speech Data Set',
 'Somerville Happiness Survey',
 '2.4 GHZ Indoor Channel Measurements',
 'EMG data for gestures',
 'Parking Birmingham',
 'Behavior of the urban traffic of the city of Sao Paulo in Brazil',
 'Travel Reviews',
 'Tarvel Review Ratings',
 'Rice Leaf Diseases',
 'Gas sensor array temperature modulation',
 'Facebook Live Sellers in Thailand',
 'Parkinson Dataset with replicated acoustic features',
 'Metro Interstate Traffic Volume',
 'Query Analytics Workloads Dataset',
 'Wave Energy Converters',
 'PPG-DaLiA',
 'Alcohol QCM Sensor Dataset',
 'Divorce Predictors data set',
 'Incident management process enriched event log',
 'Opinion Corpus for Lebanese Arabic Reviews (OCLAR)',
 'MEx',
 'Beijing Multi-Site Air-Quality Data',
 'Online Retail II',
 'Hepatitis C Virus (HCV) for Egyptian patients',
 'QSAR fish toxicity',
 'QSAR aquatic toxicity',
 'Human Activity Recognition from Continuous Ambient Sensor Data',
 'WISDM Smartphone and Smartwatch Activity and Biometrics Dataset',
 'QSAR oral toxicity',
 'QSAR androgen receptor',
 'QSAR Bioconcentration classes dataset',
 'QSAR fish bioconcentration factor (BCF)',
 'A study of Asian Religious and Biblical Texts',
 'Real-time Election Results: Portugal 2019',
 'Bias correction of numerical prediction model temperature forecast',
 'Bar Crawl: Detecting Heavy Drinking',
 'Kitsune Network Attack Dataset',
 'Shoulder Implant X-Ray Manufacturer Classification',
 'Speaker Accent Recognition',
 'Heart failure clinical records',
 'Deepfakes: Medical Image Tamper Detection',
 'selfBACK',
 'South German Credit',
 'Exasens',
 'Swarm Behaviour',
 'Crop mapping using fused optical-radar data set',
 'BitcoinHeistRansomwareAddressDataset',
 'Facebook Large Page-Page Network',
 'Amphibians',
 'Early stage diabetes risk prediction dataset.',
 'Turkish Spam V01',
 'Stock keeping units',
 'Demand Forecasting for a store',
 'Detect Malware Types',
 'Wave Energy Converters',
 'Youtube cookery channels viewers comments in Hinglish',
 'Pedestrian in Traffic Dataset',
 'Cervical Cancer Behavior Risk',
 'Sattriya_Dance_Single_Hand_Gestures Dataset',
 'Divorce Predictors data set',
 '3W dataset',
 'Malware static and dynamic features VxHeaven and Virus Total',
 'Internet Firewall Data',
 'User Profiling and Abusive Language Detection Dataset',
 'Estimation of obesity levels based on eating habits and physical condition',
 'Rice (Cammeo and Osmancik)',
 'Vehicle routing and scheduling problems',
 'Algerian Forest Fires Dataset',
 'Breath Metabolomics',
 'Horton General Hospital',
 'UrbanGB, urban road accidents coordinates labelled by the urban center',
 'Gas Turbine CO and NOx Emission Data Set',
 'Activity recognition using wearable physiological measurements',
 'clickstream data for online shopping',
 'CNNpred: CNN-based stock market prediction using a diverse set of variables',
 'Apartment for rent classified',
 ': Simulated Data set of Iraqi tourism places',
 'Nasarian CAD Dataset',
 'Monolithic Columns in Troad and Mysia Region',
 'Bar Crawl: Detecting Heavy Drinking',
 'Seoul Bike Sharing Demand',
 'Person Classification Gait Data',
 'Shill Bidding Dataset',
 'Iranian Churn Dataset',
 'Unmanned Aerial Vehicle (UAV) Intrusion Detection',
 'Bone marrow transplant: children',
 'Exasens',
 'COVID-19 Surveillance',
 'Refractive errors',
 'Shoulder Implant X-Ray Manufacturer Classification',
 'CLINC150',
 'HCV data',
 'Taiwanese Bankruptcy Prediction',
 'South German Credit (UPDATE)',
 'IIWA14-R820-Gazebo-Dataset-10Trajectories',
 'Guitar Chords finger positions',
 'Russian Corpus of Biographical Texts',
 'Codon usage',
 'Intelligent Media Accelerometer and Gyroscope (IM-AccGyro) Dataset',
 'Myocardial infarction complications',
 'Hungarian Chickenpox Cases',
 'Simulated data for survival modelling',
 'Student Performance on an entrance examination',
 'Chemical Composition of Ceramic Samples',
 'Labeled Text Forum Threads Dataset',
 'Stock keeping units',
 'BLE RSSI dataset for Indoor localization',
 'Basketball dataset',
 'GitHub MUSAE',
 'Anticancer peptides',
 'Monolithic Columns in Troad and Mysia Region',
 'Gender by Name',
 'Iranian Churn Dataset',
 'Unmanned Aerial Vehicle (UAV) Intrusion Detection',
 'Shoulder Implant Manufacture Classification',
 'LastFM Asia Social Network',
 'Wheat kernels',
 'Productivity Prediction of Garment Employees',
 'Multi-view Brain Networks',
 'LastFM Asia Social Network',
 'Wisesight Sentiment Corpus',
 'AI4I 2020 Predictive Maintenance Dataset',
 'Dry Bean Dataset',
 'in-vehicle coupon recommendation',
 'Gait Classification',
 'Wikipedia Math Essentials',
 'Wikipedia Math Essentials',
 'Synchronous Machine Data Set']

In [175]:
Type=[]
try:
    types=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
    for i in types[1:]:
        Type.append(i.text)
except NoSuchElementException:
    Type.append('-')
    
Type

['Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Univariate, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Data-Generator ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Univariate, Time-Series ',
 'Multivariate, Spatial ',
 'Multivariate ',
 'Multivariate, Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Data-Generator ',
 ' ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Relational ',
 'Multivariate ',
 'Multivariate, Data-Generator ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Sequential, Domain-Theory ',
 'Sequential ',
 'Sequential, Domain-Theory ',
 'Multivariate ',
 'Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Domain-Theory ',
 'Multivariate, Data-Generator ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Data-Generator ',
 'Multivariate, Data-Generator ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Text ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Relational ',
 'Multivariate, Time-Series ',
 'Spatio-temporal ',
 'Transactional, Sequential ',
 'Image ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Relational ',
 'Multivariate, Relational ',
 'Sequential ',
 'Text ',
 'Multivariate, Time-Series ',
 'Univariate, Time-Series ',
 'Text ',
 'Multivariate, Time-Series ',
 'Time-Series ',
 'Multivariate, Text ',
 'Text, Sequential ',
 'Image ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Domain-Theory ',
 ' ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Text ',
 'Multivariate ',
 'Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate, Time-Series ',
 'Univariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Text ',
 'Domain-Theory ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Time-Series ',
 'Time-Series ',
 'Multivariate, Text, Domain-Theory ',
 'Time-Series, Domain-Theory ',
 'Multivariate, Text, Domain-Theory ',
 'Text ',
 'Text ',
 'Multivariate, Univariate, Text ',
 'Multivariate, Univariate, Text ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Univariate ',
 'Multivariate, Text, Domain-Theory ',
 'Univariate ',
 'Univariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Univariate, Text ',
 'Sequential ',
 'Text ',
 'Multivariate, Time-Series ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Sequential, Text ',
 'Multivariate, Univariate, Time-Series ',
 'Time-Series, Multivariate ',
 'Multivariate ',
 'Sequential ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Multivariate, Text ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series, Text ',
 'Univariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 ' ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Univariate, Sequential, Time-Series ',
 'Univariate, Sequential, Time-Series ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Univariate, Domain-Theory ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 ' ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Text ',
 'Time-Series ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Univariate, Sequential, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series, Domain-Theory ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series, Domain-Theory ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Text ',
 'Multivariate, Text ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Sequential, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 ' ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 ' ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Time-Series ',
 'Text ',
 ' ',
 ' ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Sequential, Text ',
 'Multivariate, Text ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 ' ',
 'Sequential ',
 'Univariate ',
 'Univariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Univariate, Domain-Theory ',
 'Multivariate ',
 'Text ',
 'Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Univariate ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Text ',
 'Time-Series ',
 'Multivariate, Text ',
 'Multivariate, Time-Series ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Univariate ',
 'Multivariate ',
 'Multivariate ',
 'Univariate ',
 'Time-Series ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate, Univariate, Sequential, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Text ',
 'Multivariate, Text ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Univariate ',
 'Multivariate, Sequential ',
 'Text ',
 'Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Time-Series, Text ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series, Text ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate, Univariate ',
 'Multivariate ',
 'Multivariate, Univariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Univariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 ' ',
 'Text ',
 'Text ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Sequential, Time-Series ',
 'Time-Series ',
 'Multivariate ',
 'Sequential ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Time-Series ',
 'Time-Series ',
 'Multivariate ']

In [176]:
Task=[]
try:
    task=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
    for i in task[1:]:
        Task.append(i.text)
except NoSuchElementException:
    Task.append('-')
    
Task

['Classification ',
 'Classification ',
 'Classification ',
 'Recommender-Systems ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Function-Learning ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Relational-Learning ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 ' ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Clustering ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Clustering ',
 'Classification ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Recommender-Systems ',
 'Classification ',
 'Regression, Description ',
 ' ',
 ' ',
 'Classification ',
 'Regression ',
 'Classification ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Clustering ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Causal-Discovery ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Causal-Discovery ',
 'Clustering ',
 'Classification, Clustering ',
 'Regression ',
 'Regression ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 ' ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression, Clustering, Causal-Discovery ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 ' ',
 'Classification ',
 'Regression, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Regression ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Regression, Clustering ',
 'Classification, Regression ',
 'Regression, Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression, Clustering, Causa ',
 'Classification, Clustering ',
 'Regression ',
 'Classification ',
 'Regression ',
 'Regression ',
 ' ',
 'Classification ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression, Clustering ',
 'Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Clustering, Causal-Discovery ',
 'Classification, Regression, Clustering ',
 'Classification, Regression ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Clustering ',
 'Classification, Regression ',
 'Classification, Regression ',
 'Classification, Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Clustering ',
 'Classification, Regression ',
 'Regression ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Classification ',
 'Classification, Regression ',
 'Regression, Clustering ',
 'Classification, Regression ',
 'Classification, Causal-Discovery ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Regression, Clustering, Causal-Discovery ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Clustering, Causal-Discovery ',
 'Classification, Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Causal-Discovery ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification, Clustering ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Causal-Discovery ',
 'Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification, Clustering, Causal-Discovery ',
 'Classification, Regression ',
 'Classification, Regression, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Causal-Discovery ',
 'Classification, Clustering ',
 'Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Classification ',
 'Regression ',
 'Classification, Regression, Clustering ',
 'Clustering ',
 'Classification, Regression ',
 ' ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Clustering ',
 'Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Regression ',
 'Clustering ',
 'Classification ',
 'Regression ',
 'Clustering ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Recommendation ',
 'Classification, Regression, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Regression ',
 'Classification, Regression ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification, Regression ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Regression ',
 'Clustering ',
 'Classification ',
 'Regression ',
 'Regression, Clustering ',
 'Regression ',
 'Regression ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Regression, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Regression ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Regression ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Regression ',
 'Classification, Clustering ',
 'Regression ',
 'Regression ',
 'Classification, Regression ',
 'Classification, Clustering, Causal-Discovery ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Clustering ',
 'Regression ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification, Regression, Causal-Discovery ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Clustering ',
 'Classification, Regression ',
 'Classification, Clustering ',
 'Causal-Discovery ',
 'Clustering ',
 'Regression, Clustering ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification, Regression ',
 'Classification, Regression, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Classification ',
 'Classification, Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Causal-Discovery ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Regression ',
 'Regression ']

In [177]:
Attribute=[]
try:
    attribute=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
    for i in attribute[1:]:
        Attribute.append(i.text)
except NoSuchElementException:
    Attribute.append('-')
    
Attribute

['Categorical, Integer, Real ',
 'Categorical, Integer ',
 'Categorical, Integer, Real ',
 'Categorical ',
 'Categorical, Integer, Real ',
 'Categorical, Integer, Real ',
 'Categorical ',
 'Categorical ',
 'Categorical, Real ',
 'Categorical, Integer, Real ',
 ' ',
 'Categorical ',
 'Categorical ',
 'Categorical ',
 'Integer ',
 'Real ',
 'Real ',
 'Categorical, Integer ',
 'Categorical ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Categorical ',
 'Categorical, Integer ',
 ' ',
 'Categorical, Integer ',
 'Categorical ',
 'Categorical, Integer, Real ',
 'Categorical, Real, Integer ',
 'Integer ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Categorical, Integer, Real ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Real ',
 ' ',
 ' ',
 'Categorical, Integer, Real ',
 'Real ',
 'Categorical, Integer ',
 'Real ',
 'Real ',
 'Integer ',
 'Categorical ',
 'Categorical, Integer, Real ',
 'Categorical, Integer, Real ',
 'Categorical, Integer, Real ',
 'Real ',
 'Real ',
 'Categorical, Integer, Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Categorical ',
 'Categorical, Integer, Real ',
 'Categorical ',
 'Categorical ',
 'Integer ',
 'Categorical, Integer, Real ',
 ' ',
 'Integer ',
 'Categorical ',
 'Categorical, Integer, Real ',
 'Categorical, Integer, Real ',
 'Categorical, Integer, Real ',
 'Categorical ',
 'Categorical ',
 'Categorical ',
 'Categorical ',
 ' ',
 'Integer, Real ',
 'Categorical ',
 'Integer ',
 'Integer ',
 'Categorical ',
 ' ',
 'Integer, Real ',
 'Integer ',
 'Integer ',
 'Categorical, Integer ',
 'Categorical ',
 ' ',
 ' ',
 'Real ',
 'Categorical, Integer ',
 'Categorical ',
 'Categorical ',
 'Categorical ',
 'Categorical ',
 'Integer ',
 'Integer, Real ',
 'Integer, Real ',
 'Categorical ',
 'Integer ',
 'Categorical, Integer ',
 ' ',
 ' ',
 'Categorical, Integer ',
 'Categorical ',
 'Categorical, Real ',
 'Categorical ',
 'Categorical, Integer ',
 'Categorical ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Categorical, Integer ',
 ' ',
 ' ',
 'Categorical, Real ',
 'Real ',
 'Categorical ',
 'Categorical, Integer ',
 'Categorical, Real ',
 'Real ',
 ' ',
 'Categorical, Integer, Real ',
 'Integer, Real ',
 'Categorical ',
 'Integer ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Real ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 ' ',
 ' ',
 'Categorical ',
 ' ',
 'Categorical, Real ',
 ' ',
 'Categorical ',
 'Integer ',
 'Real ',
 'Categorical ',
 ' ',
 ' ',
 'Categorical, Integer, Real ',
 'Categorical, Integer ',
 'Categorical, Real ',
 'Integer ',
 'Real ',
 'Integer ',
 'Integer ',
 'Categorical ',
 'Real ',
 'Real ',
 ' ',
 ' ',
 'Real ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Real ',
 'Integer ',
 'Integer ',
 'Real ',
 ' ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 'Real ',
 'Categorical ',
 'Real ',
 'Real ',
 'Real ',
 'Categorical, Integer ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Categorical, Integer, Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Real ',
 ' ',
 ' ',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 ' ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 ' ',
 ' ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 ' ',
 'Real ',
 'Integer ',
 'Real ',
 ' ',
 ' ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 ' ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Real ',
 ' ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Real ',
 'Real ',
 'Integer ',
 ' ',
 'Real ',
 ' ',
 'Integer ',
 ' ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 ' ',
 ' ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer, Real ',
 ' ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Categorical ',
 ' ',
 'Integer, Real ',
 ' ',
 ' ',
 'Integer, Real ',
 'Real ',
 'Real ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Integer ',
 ' ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 ' ',
 'Integer, Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer ',
 'Integer, Real ',
 'Integer ',
 ' ',
 'Integer, Real ',
 ' ',
 'Real ',
 'Real ',
 ' ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Integer ',
 'Integer ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer ',
 'Integer ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Integer ',
 'Integer ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 ' ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 ' ',
 'Integer, Real ',
 'Real ',
 ' ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer, Real ',
 ' ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'Integer ',
 'Real ',
 ' ',
 ' ',
 'Integer ',
 'Integer ',
 'Integer ',
 ' ',
 'Real ',
 'Categorical ',
 'Integer ',
 'Integer ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 ' ',
 'Integer, Real ',
 ' ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 ' ',
 ' ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Integer ',
 ' ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 ' ',
 ' ',
 ' ',
 'Integer, Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer, Real ',
 ' ',
 'Integer, Real ',
 ' ',
 ' ',
 'Integer, Real ',
 'Integer ',
 ' ',
 'Real ',
 ' ',
 'Real ',
 'Integer ',
 ' ',
 'Integer ',
 'Integer, Real ',
 'Integer, Real ',
 ' ',
 ' ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 ' ',
 ' ',
 ' ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 ' ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 ' ',
 'Integer ',
 'Real ',
 ' ',
 'Integer, Real ',
 'Integer ',
 'Integer, Real ',
 'Integer ',
 ' ',
 ' ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 ' ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Integer ',
 'Integer ',
 ' ',
 ' ',
 'Real ',
 ' ',
 'Integer ',
 'Real ',
 ' ',
 ' ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 ' ',
 ' ',
 'Real ',
 'Integer, Real ',
 ' ',
 'Real ',
 'Real ',
 'Real ',
 'Real ']

In [178]:
No_of_Instance=[]
try:
    instance=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
    for i in instance[1:]:
        No_of_Instance.append(i.text)
except NoSuchElementException:
    No_of_Instance.append('-')
    
No_of_Instance

['4177 ',
 '48842 ',
 '798 ',
 '37711 ',
 '452 ',
 '6000 ',
 '226 ',
 '226 ',
 '398 ',
 '205 ',
 '294 ',
 '625 ',
 '16 ',
 '286 ',
 '699 ',
 '198 ',
 '569 ',
 '108 ',
 '1728 ',
 '48842 ',
 ' ',
 '3196 ',
 '28056 ',
 ' ',
 '100 ',
 '67557 ',
 '690 ',
 '125 ',
 '209 ',
 '1473 ',
 '581012 ',
 '512 ',
 '366 ',
 ' ',
 ' ',
 ' ',
 ' ',
 '132 ',
 '336 ',
 '194 ',
 '352 ',
 '214 ',
 '306 ',
 '160 ',
 '303 ',
 '155 ',
 '368 ',
 ' ',
 '2310 ',
 '3279 ',
 '351 ',
 '150 ',
 '7797 ',
 '104 ',
 '57 ',
 ' ',
 '24 ',
 '20000 ',
 '345 ',
 ' ',
 '32 ',
 '148 ',
 '209 ',
 '528 ',
 ' ',
 '106 ',
 '128 ',
 '3190 ',
 '432 ',
 '202 ',
 '2000 ',
 '8124 ',
 '476 ',
 '6598 ',
 '12960 ',
 ' ',
 '5473 ',
 '5620 ',
 '10992 ',
 '90 ',
 '339 ',
 ' ',
 ' ',
 ' ',
 '167 ',
 '15 ',
 '1389 ',
 '307 ',
 '47 ',
 '23 ',
 '531 ',
 '4601 ',
 '267 ',
 '267 ',
 '76 ',
 ' ',
 '1000 ',
 '151 ',
 '958 ',
 '7200 ',
 '10 ',
 '285 ',
 '435 ',
 '527 ',
 '5000 ',
 '5000 ',
 '178 ',
 '1484 ',
 '101 ',
 ' ',
 '20000 ',
 '6650 ',
 '2565 ',
 '2458285 ',
 '299285 ',
 '340 ',
 '68040 ',
 ' ',
 '122 ',
 '178080 ',
 '50672 ',
 '640 ',
 '9000 ',
 '10104 ',
 '256932 ',
 '640 ',
 '191779 ',
 '4000000 ',
 ' ',
 '10000 ',
 '989818 ',
 '129000 ',
 ' ',
 '100000 ',
 '21578 ',
 '463 ',
 '600 ',
 '332 ',
 ' ',
 ' ',
 '690 ',
 '1000 ',
 '270 ',
 '6435 ',
 '2310 ',
 '58000 ',
 '946 ',
 '20008 ',
 '208 ',
 '528 ',
 ' ',
 ' ',
 '1024 ',
 '10080 ',
 '50400 ',
 '1025010 ',
 '19020 ',
 '1364 ',
 '961 ',
 '517 ',
 '200 ',
 '8000000 ',
 '1030 ',
 '606 ',
 '900 ',
 '2600 ',
 '1950 ',
 '13500 ',
 '4400 ',
 '2536 ',
 '300 ',
 '197 ',
 '2858 ',
 '748 ',
 '11640 ',
 '1593 ',
 '1567 ',
 '22632 ',
 '360 ',
 '103 ',
 '1994 ',
 '120 ',
 '4898 ',
 '2396130 ',
 '16772 ',
 '5875 ',
 '503 ',
 '51 ',
 '106 ',
 '2126 ',
 '5456 ',
 '8800 ',
 '164860 ',
 ' ',
 '1941 ',
 '130065 ',
 '515345 ',
 '440 ',
 ' ',
 '53500 ',
 '8235 ',
 ' ',
 '5749132 ',
 '2215 ',
 '310 ',
 '10000 ',
 '3000 ',
 '1500 ',
 '30000 ',
 '2500 ',
 '4143 ',
 '64 ',
 '53414 ',
 '65554 ',
 '45211 ',
 '1138562 ',
 '13910 ',
 '583 ',
 '2551 ',
 '34465 ',
 '5574 ',
 '245057 ',
 '182 ',
 '3850505 ',
 '138 ',
 '1080 ',
 '2075259 ',
 '210 ',
 '115 ',
 '3960456 ',
 ' ',
 '10299 ',
 '1600 ',
 '768 ',
 '308 ',
 '100 ',
 '237 ',
 '434874 ',
 '536 ',
 '140000 ',
 '6118 ',
 '165632 ',
 '18000 ',
 '540 ',
 '931 ',
 '1055 ',
 '100 ',
 '9120 ',
 '403 ',
 '111740 ',
 '10421 ',
 '5820 ',
 '403 ',
 '14980 ',
 '45730 ',
 '2584 ',
 '1372 ',
 '306 ',
 '120000 ',
 '13910 ',
 '2747 ',
 '3395 ',
 '39242 ',
 '4137 ',
 '17389 ',
 '51 ',
 '470 ',
 '132 ',
 '5000000 ',
 '11000000 ',
 '250 ',
 '126 ',
 ' ',
 '4889 ',
 ' ',
 ' ',
 '340 ',
 '501 ',
 '45781 ',
 '1503 ',
 '440 ',
 '2000 ',
 '9568 ',
 '168 ',
 '100000 ',
 '5665 ',
 '79 ',
 '127 ',
 '1040 ',
 '9900 ',
 '560 ',
 '60021 ',
 '1419 ',
 '101 ',
 '399 ',
 '58 ',
 '180 ',
 '21048 ',
 ' ',
 '750 ',
 '3000 ',
 '150 ',
 '1059 ',
 '11934 ',
 '27965 ',
 '216 ',
 '120 ',
 '649 ',
 '370 ',
 '4178504 ',
 '221579 ',
 '10800 ',
 '58509 ',
 '129685 ',
 '2456 ',
 '2921 ',
 '1151 ',
 '6590 ',
 '3000 ',
 '39797 ',
 '326 ',
 '913 ',
 '168286 ',
 '400 ',
 '314080 ',
 '637 ',
 '1710671 ',
 '12000 ',
 '10929 ',
 '1080 ',
 '40000 ',
 '43930257 ',
 '230318 ',
 '10500000 ',
 '13197 ',
 ' ',
 '30000 ',
 '324 ',
 '541909 ',
 '11164866 ',
 '163 ',
 '373 ',
 '20560 ',
 '40 ',
 '422937 ',
 '9358 ',
 '640 ',
 '919438 ',
 '40949 ',
 '5744 ',
 '10503 ',
 '42240 ',
 '102944 ',
 '500 ',
 '9782222 ',
 '11463 ',
 '17898 ',
 '1885 ',
 '19735 ',
 '1540 ',
 '4007 ',
 '153540 ',
 '606 ',
 '1353 ',
 '1956 ',
 '43824 ',
 '3942 ',
 '858 ',
 '287 ',
 '17764280 ',
 '106574 ',
 '9358 ',
 '11500 ',
 '92000 ',
 '315 ',
 '78095 ',
 '130 ',
 '74 ',
 '52854 ',
 '77 ',
 '811 ',
 '504 ',
 '401 ',
 '2856 ',
 '10546 ',
 '801 ',
 '1540 ',
 '1451 ',
 '1075 ',
 '78095 ',
 '7195 ',
 '3600 ',
 '76 ',
 '60 ',
 '405 ',
 '303 ',
 '303 ',
 '107888 ',
 '76000 ',
 '10000 ',
 '180 ',
 '745000 ',
 '12234 ',
 '292 ',
 '104 ',
 '60000 ',
 '2000 ',
 '165 ',
 '217 ',
 '1175 ',
 '704 ',
 '75128 ',
 '90 ',
 '90 ',
 '50 ',
 '71 ',
 '93239 ',
 '540 ',
 '105 ',
 '6611 ',
 '15 ',
 '372 ',
 '58000 ',
 '4960 ',
 '241600 ',
 '130000 ',
 '7062606 ',
 '740 ',
 '70 ',
 '2205 ',
 '10721 ',
 '640 ',
 '1000 ',
 '116 ',
 '1672 ',
 '322 ',
 '93600 ',
 '3060 ',
 '5879 ',
 '9200 ',
 '20000 ',
 '20867 ',
 ' ',
 '4143 ',
 '215063 ',
 '6000000 ',
 '21263 ',
 '63000000 ',
 '10190 ',
 '300 ',
 '12330 ',
 '5180 ',
 '756 ',
 '10000 ',
 '80 ',
 '1184 ',
 '1047 ',
 '777 ',
 '249 ',
 '414 ',
 ' ',
 '143 ',
 '7840 ',
 '30000 ',
 '35717 ',
 '135 ',
 '980 ',
 '5456 ',
 '120 ',
 '4095000 ',
 '7051 ',
 '240 ',
 '48204 ',
 '260000 ',
 '288000 ',
 '8300000 ',
 '125 ',
 '170 ',
 '141712 ',
 '3916 ',
 '6262 ',
 '420768 ',
 '1067371 ',
 '1385 ',
 '908 ',
 '546 ',
 '13956534 ',
 '15630426 ',
 '8992 ',
 '1687 ',
 '779 ',
 '1056 ',
 '590 ',
 '21643 ',
 '7750 ',
 '14057567 ',
 '27170754 ',
 '597 ',
 '329 ',
 '299 ',
 '20000 ',
 '26136 ',
 '1000 ',
 '399 ',
 '24017 ',
 '325834 ',
 '2916697 ',
 '22470 ',
 '189 ',
 '520 ',
 '826 ',
 '2279 ',
 '28764 ',
 '7107 ',
 '288000 ',
 '9800 ',
 '4760 ',
 '72 ',
 '1450 ',
 '170 ',
 '1984 ',
 '2955 ',
 '65532 ',
 '65919 ',
 '2111 ',
 '3810 ',
 '18 ',
 '244 ',
 '104 ',
 '139 ',
 '360177 ',
 '36733 ',
 '4480 ',
 '165474 ',
 '1985 ',
 '10000 ',
 '232 ',
 '150 ',
 '11 ',
 '14057567 ',
 '8760 ',
 '48 ',
 '6321 ',
 '3150 ',
 '17256 ',
 '187 ',
 '399 ',
 '14 ',
 '467 ',
 '597 ',
 '23700 ',
 '615 ',
 '6819 ',
 '1000 ',
 ' ',
 '2633 ',
 '200 ',
 '13028 ',
 '800 ',
 '1700 ',
 '521 ',
 '120000 ',
 '666 ',
 '88 ',
 '200 ',
 '2279 ',
 '23570 ',
 '10000 ',
 '37700 ',
 '1850 ',
 '11 ',
 '147270 ',
 '3150 ',
 '17256 ',
 '597 ',
 '7624 ',
 '314 ',
 '1197 ',
 '70 ',
 '7624 ',
 '26737 ',
 '10000 ',
 '13611 ',
 '12684 ',
 '48 ',
 '731 ',
 '731 ',
 '557 ']

In [179]:
No_of_Attribute=[]
try:
    attr=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
    for i in attr[1:]:
        No_of_Attribute.append(i.text)
except NoSuchElementException:
    No_of_Attribute.append('-')
    
No_of_Attribute

['8 ',
 '14 ',
 '38 ',
 '294 ',
 '279 ',
 '7 ',
 ' ',
 '69 ',
 '8 ',
 '26 ',
 '1 ',
 '4 ',
 '4 ',
 '9 ',
 '10 ',
 '34 ',
 '32 ',
 '13 ',
 '6 ',
 '14 ',
 '22 ',
 '36 ',
 '6 ',
 ' ',
 '6 ',
 '42 ',
 '15 ',
 ' ',
 '9 ',
 '9 ',
 '54 ',
 '39 ',
 '33 ',
 '20 ',
 ' ',
 ' ',
 ' ',
 '12 ',
 '8 ',
 '30 ',
 ' ',
 '10 ',
 '3 ',
 '5 ',
 '75 ',
 '19 ',
 '27 ',
 ' ',
 '19 ',
 '1558 ',
 '34 ',
 '4 ',
 '617 ',
 '12 ',
 '16 ',
 '7 ',
 '4 ',
 '16 ',
 '7 ',
 ' ',
 '56 ',
 '18 ',
 '8 ',
 '22 ',
 ' ',
 '58 ',
 ' ',
 '61 ',
 '7 ',
 ' ',
 '649 ',
 '22 ',
 '168 ',
 '168 ',
 '8 ',
 ' ',
 '10 ',
 '64 ',
 '16 ',
 '8 ',
 '17 ',
 ' ',
 ' ',
 '72 ',
 '4 ',
 '6 ',
 '10 ',
 '35 ',
 '35 ',
 '4 ',
 '102 ',
 '57 ',
 '22 ',
 '44 ',
 '45 ',
 ' ',
 ' ',
 '5 ',
 '9 ',
 '21 ',
 '32 ',
 '17 ',
 '16 ',
 '38 ',
 '21 ',
 '40 ',
 '13 ',
 '8 ',
 '17 ',
 ' ',
 ' ',
 '15 ',
 '22 ',
 '68 ',
 '40 ',
 '17 ',
 '89 ',
 ' ',
 '4 ',
 '12 ',
 ' ',
 ' ',
 '86 ',
 '72 ',
 '61 ',
 '12 ',
 '481 ',
 '42 ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 '5 ',
 '90 ',
 ' ',
 '5 ',
 ' ',
 ' ',
 '14 ',
 '20 ',
 '13 ',
 '36 ',
 '19 ',
 '9 ',
 '18 ',
 '4 ',
 '60 ',
 '10 ',
 ' ',
 ' ',
 '10 ',
 '4 ',
 '3 ',
 '11 ',
 '11 ',
 ' ',
 '6 ',
 '13 ',
 ' ',
 '100000 ',
 '9 ',
 '101 ',
 '10000 ',
 '20000 ',
 '100000 ',
 '5000 ',
 '500 ',
 '73 ',
 '43 ',
 '23 ',
 '3 ',
 '5 ',
 ' ',
 '256 ',
 '591 ',
 '70 ',
 '91 ',
 '10 ',
 '128 ',
 '6 ',
 '12 ',
 '3231961 ',
 '5409 ',
 '26 ',
 ' ',
 ' ',
 '10 ',
 '23 ',
 '24 ',
 '13 ',
 '8 ',
 ' ',
 '27 ',
 '50 ',
 '90 ',
 '138672 ',
 ' ',
 '386 ',
 ' ',
 ' ',
 '12 ',
 '147 ',
 '6 ',
 '8 ',
 '27 ',
 '10000 ',
 '20000 ',
 '10000 ',
 '54877 ',
 '4702 ',
 '24 ',
 '29 ',
 '17 ',
 '3 ',
 '128 ',
 '10 ',
 '242 ',
 '120 ',
 ' ',
 '4 ',
 '13 ',
 '52 ',
 '47 ',
 '857 ',
 '9 ',
 '7 ',
 '200 ',
 '4 ',
 ' ',
 '561 ',
 '64 ',
 '8 ',
 '7 ',
 '10 ',
 '9 ',
 '4 ',
 '8 ',
 '77 ',
 '51 ',
 '18 ',
 '1950000 ',
 '18 ',
 '1300 ',
 '41 ',
 '6 ',
 '5625 ',
 '5 ',
 ' ',
 '7 ',
 '33 ',
 '5 ',
 '15 ',
 '9 ',
 '19 ',
 '5 ',
 '5 ',
 '1000000 ',
 '129 ',
 ' ',
 '20 ',
 '152 ',
 '24 ',
 '16 ',
 '35 ',
 '17 ',
 '5 ',
 '18 ',
 '28 ',
 '7 ',
 '309 ',
 '3 ',
 '6 ',
 ' ',
 ' ',
 '16 ',
 '13 ',
 '5 ',
 '6 ',
 '8 ',
 '2 ',
 '4 ',
 '148 ',
 '55 ',
 '17 ',
 '8 ',
 '42 ',
 '26 ',
 '50 ',
 '2 ',
 '281 ',
 '120 ',
 ' ',
 '6 ',
 '120432 ',
 '150000 ',
 '529 ',
 ' ',
 '16 ',
 '2500 ',
 '5 ',
 '68 ',
 '16 ',
 '100 ',
 '216 ',
 '23 ',
 '33 ',
 '140256 ',
 '19 ',
 '20 ',
 '20 ',
 '49 ',
 '12 ',
 '30 ',
 '5232 ',
 '20 ',
 '1 ',
 ' ',
 '61 ',
 '27 ',
 '53 ',
 '11 ',
 '25 ',
 '0 ',
 '20 ',
 '9 ',
 '3 ',
 '561 ',
 '82 ',
 '13 ',
 '16 ',
 '13 ',
 '28 ',
 '4 ',
 ' ',
 '24 ',
 '34 ',
 '8 ',
 '128 ',
 '15 ',
 '513 ',
 '7 ',
 '7 ',
 '5 ',
 '15 ',
 '480000 ',
 '11 ',
 '54 ',
 '561 ',
 '64 ',
 '6 ',
 '116 ',
 '19 ',
 ' ',
 '5812 ',
 '9 ',
 '32 ',
 '29 ',
 '67 ',
 ' ',
 '25 ',
 '6400 ',
 '10 ',
 '5 ',
 '13 ',
 '98 ',
 '36 ',
 '69 ',
 '2158859 ',
 '518 ',
 '15 ',
 '179 ',
 ' ',
 '12 ',
 '38 ',
 '65 ',
 '102 ',
 '86 ',
 '7 ',
 '53 ',
 '20 ',
 '1 ',
 '71 ',
 '29 ',
 '20531 ',
 '65 ',
 '3 ',
 '22 ',
 '38 ',
 '22 ',
 '4814 ',
 '698 ',
 '13 ',
 '10 ',
 '59 ',
 '56 ',
 '482 ',
 '171 ',
 '5 ',
 '500 ',
 '411 ',
 '8519 ',
 '21 ',
 '21 ',
 '171 ',
 '7 ',
 '49 ',
 '12 ',
 '3 ',
 '21 ',
 '9 ',
 '8 ',
 '7 ',
 '2 ',
 '11 ',
 '11 ',
 '173 ',
 '5 ',
 '15 ',
 '3 ',
 '105 ',
 '25000 ',
 ' ',
 '18 ',
 '21000 ',
 '115 ',
 '21 ',
 '206 ',
 '43680 ',
 '8 ',
 '10 ',
 '59 ',
 '10 ',
 '5 ',
 '5 ',
 '1000 ',
 '138 ',
 ' ',
 '16 ',
 '2 ',
 '10 ',
 ' ',
 '8 ',
 '6 ',
 '129 ',
 '81 ',
 '12 ',
 '6 ',
 '22 ',
 '18 ',
 '9 ',
 '754 ',
 '14 ',
 '5 ',
 ' ',
 ' ',
 '18 ',
 '7 ',
 '7 ',
 ' ',
 '7 ',
 '5 ',
 '6 ',
 '4 ',
 '18 ',
 '11 ',
 '25 ',
 ' ',
 '20 ',
 '12 ',
 '46 ',
 '9 ',
 '8 ',
 '49 ',
 '11 ',
 '8 ',
 '54 ',
 '36 ',
 '3916 ',
 '710 ',
 '18 ',
 '8 ',
 '29 ',
 '7 ',
 '9 ',
 '37 ',
 '6 ',
 '1024 ',
 '1024 ',
 '14 ',
 '7 ',
 '8265 ',
 '29 ',
 '25 ',
 '3 ',
 '115 ',
 '1 ',
 '12 ',
 '13 ',
 '200000 ',
 '6 ',
 '21 ',
 '4 ',
 '2400 ',
 '175 ',
 '10 ',
 '4714 ',
 '23 ',
 '17 ',
 '2 ',
 '9 ',
 '8 ',
 '280 ',
 '49 ',
 '3 ',
 '14 ',
 '19 ',
 ' ',
 '54 ',
 '8 ',
 '1087 ',
 '12 ',
 '3 ',
 '17 ',
 '8 ',
 '9 ',
 '12 ',
 '1656 ',
 '6 ',
 '2 ',
 '11 ',
 '533 ',
 '14 ',
 '84 ',
 '22 ',
 '16 ',
 '52 ',
 '19 ',
 '3 ',
 '14 ',
 '321 ',
 '13 ',
 '13 ',
 '55 ',
 '39 ',
 '4 ',
 '7 ',
 '79 ',
 '1 ',
 ' ',
 '14 ',
 '96 ',
 '21 ',
 ' ',
 '5 ',
 '2 ',
 '69 ',
 '9 ',
 '124 ',
 '20 ',
 '25 ',
 '11 ',
 '19 ',
 '9 ',
 '9 ',
 '5 ',
 '7 ',
 '4006 ',
 '2 ',
 '19 ',
 '4 ',
 '13 ',
 '55 ',
 '1 ',
 '7842 ',
 '15 ',
 '15 ',
 '70 ',
 '7842 ',
 '4 ',
 '14 ',
 '17 ',
 '23 ',
 '321 ',
 '1068 ',
 '1068 ',
 '5 ']

In [180]:
Year=[]
try:
    year=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")
    for i in year[1:]:
        Year.append(i.text)
except NoSuchElementException:
    Year.append('-')
    
Year

['1995 ',
 '1996 ',
 ' ',
 '1998 ',
 '1998 ',
 '1992 ',
 '1987 ',
 '1992 ',
 '1993 ',
 '1987 ',
 '1994 ',
 '1994 ',
 ' ',
 '1988 ',
 '1992 ',
 '1995 ',
 '1995 ',
 '1990 ',
 '1997 ',
 '1996 ',
 '1988 ',
 '1989 ',
 '1994 ',
 ' ',
 ' ',
 '1995 ',
 ' ',
 '1992 ',
 '1987 ',
 '1997 ',
 '1998 ',
 '1995 ',
 '1998 ',
 ' ',
 ' ',
 '1994 ',
 ' ',
 '1989 ',
 '1996 ',
 '1990 ',
 '1990 ',
 '1987 ',
 '1999 ',
 '1989 ',
 '1988 ',
 '1988 ',
 '1989 ',
 ' ',
 '1990 ',
 '1998 ',
 '1989 ',
 '1988 ',
 '1994 ',
 '1990 ',
 '1988 ',
 '1988 ',
 '1990 ',
 '1991 ',
 '1990 ',
 ' ',
 '1992 ',
 '1988 ',
 '1990 ',
 '1996 ',
 '1995 ',
 '1990 ',
 ' ',
 '1992 ',
 '1992 ',
 '1994 ',
 ' ',
 '1987 ',
 '1994 ',
 '1994 ',
 '1997 ',
 '1991 ',
 '1995 ',
 '1998 ',
 '1998 ',
 '1993 ',
 '1988 ',
 ' ',
 ' ',
 '1992 ',
 '1993 ',
 '1988 ',
 '1989 ',
 '1988 ',
 '1987 ',
 '1993 ',
 '1988 ',
 '1999 ',
 '2001 ',
 '2001 ',
 ' ',
 '1992 ',
 '1993 ',
 '1997 ',
 '1991 ',
 '1987 ',
 '1994 ',
 '1988 ',
 '1987 ',
 '1993 ',
 '1988 ',
 '1988 ',
 '1991 ',
 '1996 ',
 '1990 ',
 ' ',
 '1999 ',
 '1999 ',
 '2002 ',
 ' ',
 '2000 ',
 '1999 ',
 '1999 ',
 '2001 ',
 '1999 ',
 '1999 ',
 '2000 ',
 '1999 ',
 '2000 ',
 '1999 ',
 '1999 ',
 ' ',
 '1998 ',
 '1999 ',
 '2001 ',
 '1999 ',
 ' ',
 '2003 ',
 '1999 ',
 '1999 ',
 '1997 ',
 '1999 ',
 '1999 ',
 '1998 ',
 ' ',
 ' ',
 ' ',
 '1994 ',
 ' ',
 '1993 ',
 '1990 ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 '1989 ',
 '2006 ',
 '2006 ',
 '2007 ',
 '2007 ',
 '2007 ',
 '2007 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2007 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2009 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2009 ',
 '2009 ',
 '2009 ',
 '2009 ',
 '2009 ',
 '2009 ',
 '2010 ',
 '2009 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2014 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2013 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2015 ',
 '2014 ',
 '2014 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2014 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2016 ',
 '2016 ',
 '2015 ',
 '2016 ',
 '2016 ',
 '2015 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2016 ',
 '2017 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2017 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2018 ',
 '2018 ',
 '2016 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2019 ',
 '2019 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2021 ',
 '2018 ',
 '2018 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2021 ',
 '2021 ',
 '2021 ']

In [181]:
df = pd.DataFrame({})
df["Name"] = Name
df[" Data type"] =Type
df["Task"] = Task
df["Attribute type"] = Attribute
df["No of instances"] = No_of_Instance
df[" No of attribute"] = No_of_Attribute
df["Year"] = Year
df

,Name,Data type,Task,Attribute type,No of instances,No of attribute,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
583,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
584,Gait Classification,Multivariate,Classification,Real,48,321,2020
585,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
586,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
587,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021